table bd_depositos
	lineageTag: 69aeb7f6-1c6f-4575-9a9f-3c397f4e26f8

	column 'Nome da Origem'
		dataType: string
		lineageTag: 56f46d4a-5108-4c4e-abb4-8abd24f5db89
		summarizeBy: none
		sourceColumn: Nome da Origem

		annotation SummarizationSetBy = Automatic

	column userid
		dataType: string
		lineageTag: e6e62409-6a61-48ea-8f8c-ad70e34fb4be
		summarizeBy: none
		sourceColumn: userid

		annotation SummarizationSetBy = Automatic

	column data_deposito
		dataType: dateTime
		formatString: Long Date
		lineageTag: 59288c75-c20c-4e08-ad9c-7c7fdd028ae6
		summarizeBy: none
		sourceColumn: data_deposito

		variation Variation
			isDefault
			relationship: 0a24f243-5bb6-4762-809c-672ae7db8193
			defaultHierarchy: LocalDateTable_73c834bf-ed64-4052-942a-99373ea9a0a6.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column data_status
		dataType: dateTime
		formatString: Long Date
		lineageTag: a5b9007f-3d3b-4407-bd0e-92c7a38c87b0
		summarizeBy: none
		sourceColumn: data_status

		variation Variation
			isDefault
			relationship: c7170886-4160-4478-86ef-1e55803caa96
			defaultHierarchy: LocalDateTable_c260fe73-0c1f-49dc-9950-edcd9654ba2b.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column status
		dataType: string
		lineageTag: 12a7e0b2-1e8b-4797-9b67-354ad36c7564
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	column processor
		dataType: string
		lineageTag: c9d4d1ab-5d4b-49d4-8bbd-d0e883a103dc
		summarizeBy: none
		sourceColumn: processor

		annotation SummarizationSetBy = Automatic

	column utm_source_cadastro
		dataType: string
		lineageTag: 3a47637e-ccdf-431b-99fe-607b39cbbb41
		summarizeBy: none
		sourceColumn: utm_source_cadastro

		annotation SummarizationSetBy = Automatic

	column utm_medium_cadastro
		dataType: string
		lineageTag: 0710eacb-a717-4e21-9f6d-17590fbd76aa
		summarizeBy: none
		sourceColumn: utm_medium_cadastro

		annotation SummarizationSetBy = Automatic

	column utm_campaign_cadastro
		dataType: string
		lineageTag: 7c9390df-1750-414b-8f6a-16a2aadf4293
		summarizeBy: none
		sourceColumn: utm_campaign_cadastro

		annotation SummarizationSetBy = Automatic

	column utm_content_cadastro
		dataType: string
		lineageTag: a9e996b5-3cc4-422b-bc04-b8ebcd24f074
		summarizeBy: none
		sourceColumn: utm_content_cadastro

		annotation SummarizationSetBy = Automatic

	column utm_term_cadastro
		dataType: string
		lineageTag: e6e24242-9577-4e67-a28c-5f02f5e3b5cc
		summarizeBy: none
		sourceColumn: utm_term_cadastro

		annotation SummarizationSetBy = Automatic

	column utm_source_deposito
		dataType: string
		lineageTag: ceceaf29-c588-4d25-b542-1e7af02bbbe6
		summarizeBy: none
		sourceColumn: utm_source_deposito

		annotation SummarizationSetBy = Automatic

	column utm_medium_deposito
		dataType: string
		lineageTag: bddfe430-3d50-446d-8133-dc3eb0f02e83
		summarizeBy: none
		sourceColumn: utm_medium_deposito

		annotation SummarizationSetBy = Automatic

	column utm_campaign_deposito
		dataType: string
		lineageTag: 78ac117c-5a8f-405c-8bc4-b282ccfa6be7
		summarizeBy: none
		sourceColumn: utm_campaign_deposito

		annotation SummarizationSetBy = Automatic

	column utm_content_deposito
		dataType: string
		lineageTag: 5f7c5f0b-9b13-44cf-8a15-141562b71336
		summarizeBy: none
		sourceColumn: utm_content_deposito

		annotation SummarizationSetBy = Automatic

	column utm_term_deposito
		dataType: string
		lineageTag: 22e29d56-c5e2-43d8-b05a-d53c64288734
		summarizeBy: none
		sourceColumn: utm_term_deposito

		annotation SummarizationSetBy = Automatic

	column tier_l30d
		dataType: int64
		formatString: 0
		lineageTag: 975fc449-68fd-43a3-a9ea-da0323792e32
		summarizeBy: sum
		sourceColumn: tier_l30d

		annotation SummarizationSetBy = Automatic

	column tier_high_lifetime
		dataType: int64
		formatString: 0
		lineageTag: 0a6b487b-565f-4e17-925f-26805c722e14
		summarizeBy: sum
		sourceColumn: tier_high_lifetime

		annotation SummarizationSetBy = Automatic

	column hora_atualizacao
		dataType: dateTime
		formatString: General Date
		lineageTag: 5bd08676-e677-4bc7-b78d-6185ba1804f1
		summarizeBy: none
		sourceColumn: hora_atualizacao

		variation Variation
			isDefault
			relationship: f2368386-7cda-4c89-8497-362652ce7f9a
			defaultHierarchy: LocalDateTable_0278a9ac-76bf-4684-8be5-c386d9239436.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column qtd_depositos
		dataType: int64
		formatString: 0
		lineageTag: faab9df7-32c2-4ce6-a591-3848ac53df25
		summarizeBy: sum
		sourceColumn: qtd_depositos

		annotation SummarizationSetBy = Automatic

	column total_depositos
		dataType: double
		lineageTag: 552dce12-56a3-493c-a4c3-75019b3b8ac4
		summarizeBy: sum
		sourceColumn: total_depositos

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ano_semana_deposito = WEEKNUM(bd_depositos[data_deposito], 2)
		formatString: 0
		lineageTag: 9343680d-a803-4b1b-965a-d83cb18dadb6
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column ano_semana_status = WEEKNUM(bd_depositos[data_status], 2)
		formatString: 0
		lineageTag: 286ad3a2-3312-42b4-a620-75c4c5cc9d4a
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Data_Unificada = ```
			
			IF (
			    MONTH ( bd_depositos[data_deposito] ) >= 4,
			    bd_depositos[data_deposito],
			    bd_depositos[data_status]
			)
			
			```
		formatString: General Date
		lineageTag: 7528195f-ec3c-4632-a96f-e02352b3e246
		summarizeBy: none

		variation Variation
			isDefault
			relationship: 90cff078-d138-46dd-856e-d1a057e800b7
			defaultHierarchy: LocalDateTable_4dedc774-db0c-4096-8b8f-1800178efac9.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column ano_semana_unificado = WEEKNUM(bd_depositos[Data_Unificada], 2)
		formatString: 0
		lineageTag: c5bc3214-05bb-42ce-8fed-42dc0939df5d
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column LinkUserID = "https://admin-ai.kingpanda.com/users?userid=" & [userid]
		lineageTag: b8e4dfac-0965-4cbf-ba6d-46c9bcc44f88
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition bd_depositos = m
		mode: import
		source =
				let
				    Fonte = AzureStorage.DataLake("https://kplakehouse.dfs.core.windows.net/gold/depositos"),
				    #"Linhas Filtradas" = Table.SelectRows(Fonte, each ([Extension] = ".parquet")),
				    #"Arquivos Ocultos Filtrados1" = Table.SelectRows(#"Linhas Filtradas", each [Attributes]?[Hidden]? <> true),
				    #"Invocar Função Personalizada1" = Table.AddColumn(#"Arquivos Ocultos Filtrados1", "Transformar Arquivo (9)", each #"Transformar Arquivo (9)"([Content])),
				    #"Colunas Renomeadas1" = Table.RenameColumns(#"Invocar Função Personalizada1", {"Name", "Nome da Origem"}),
				    #"Outras Colunas Removidas1" = Table.SelectColumns(#"Colunas Renomeadas1", {"Nome da Origem", "Transformar Arquivo (9)"}),
				    #"Coluna de Tabela Expandida1" = Table.ExpandTableColumn(#"Outras Colunas Removidas1", "Transformar Arquivo (9)", Table.ColumnNames(#"Transformar Arquivo (9)"(#"Arquivo de Amostra (9)"))),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Coluna de Tabela Expandida1",{{"Nome da Origem", type text}, {"userid", type text}, {"data_deposito", type date}, {"data_status", type date}, {"status", type text}, {"processor", type text}, {"utm_source_cadastro", type text}, {"utm_medium_cadastro", type text}, {"utm_campaign_cadastro", type text}, {"utm_content_cadastro", type text}, {"utm_term_cadastro", type text}, {"utm_source_deposito", type text}, {"utm_medium_deposito", type text}, {"utm_campaign_deposito", type text}, {"utm_content_deposito", type text}, {"utm_term_deposito", type text}, {"tier_l30d", Int64.Type}, {"tier_high_lifetime", Int64.Type}, {"hora_atualizacao", type datetime}, {"qtd_depositos", Int64.Type}, {"total_depositos", type number}}),
				    #"Valor Substituído" = Table.ReplaceValue(#"Tipo Alterado",null,"none",Replacer.ReplaceValue,{"utm_source_deposito", "utm_medium_deposito", "utm_campaign_deposito", "utm_content_deposito", "utm_term_deposito"})
				in
				    #"Valor Substituído"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

