table bd_kpc_acumulado
	lineageTag: 9561b02a-26e0-44c3-91ab-09e5a45a15e1

	column 'Nome da Origem'
		dataType: string
		lineageTag: 6294aa2e-2f6f-46e4-af37-a743dc8829d4
		summarizeBy: none
		sourceColumn: Nome da Origem

		annotation SummarizationSetBy = Automatic

	column userid
		dataType: string
		lineageTag: cdcfaf1b-8dc4-43c4-8a31-62af04f41c0c
		summarizeBy: none
		sourceColumn: userid

		annotation SummarizationSetBy = Automatic

	column utm_source
		dataType: string
		lineageTag: 3353a34b-1403-4500-8170-f81138cd53a2
		summarizeBy: none
		sourceColumn: utm_source

		annotation SummarizationSetBy = Automatic

	column utm_medium
		dataType: string
		lineageTag: ae260fe1-de48-4c6a-8515-36533795d7d2
		summarizeBy: none
		sourceColumn: utm_medium

		annotation SummarizationSetBy = Automatic

	column utm_campaign
		dataType: string
		lineageTag: c0200971-530d-4817-888e-3fb8aabb1a53
		summarizeBy: none
		sourceColumn: utm_campaign

		annotation SummarizationSetBy = Automatic

	column utm_content
		dataType: string
		lineageTag: 58315433-64e7-45c5-8120-778d34653be0
		summarizeBy: none
		sourceColumn: utm_content

		annotation SummarizationSetBy = Automatic

	column utm_term
		dataType: string
		lineageTag: 18479d7d-f7e0-413f-afe5-81bcf23bc452
		summarizeBy: none
		sourceColumn: utm_term

		annotation SummarizationSetBy = Automatic

	column saldo_hoje
		dataType: int64
		formatString: 0
		lineageTag: 480c7144-10a2-4780-a01a-228681ce0e5d
		summarizeBy: sum
		sourceColumn: saldo_hoje

		annotation SummarizationSetBy = Automatic

	column value_kpc
		dataType: double
		lineageTag: 691b490c-7e40-4874-9bf2-8fd7d696323f
		summarizeBy: sum
		sourceColumn: value_kpc

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column status
		dataType: string
		lineageTag: c324bc52-d18b-4fcd-a575-f094f36f314e
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	column source
		dataType: string
		lineageTag: 850ce821-9397-4286-a8de-42d66d27f705
		summarizeBy: none
		sourceColumn: source

		annotation SummarizationSetBy = Automatic

	column updated_brt
		dataType: string
		lineageTag: b2322d21-f1b9-4a43-be00-567fd632dd07
		summarizeBy: none
		sourceColumn: updated_brt

		annotation SummarizationSetBy = Automatic

	column tier_l30d
		dataType: string
		lineageTag: 36260b67-89bd-4c6f-9273-73b75055f4e1
		summarizeBy: none
		sourceColumn: tier_l30d

		annotation SummarizationSetBy = Automatic

	column tier_high_lifetime
		dataType: string
		lineageTag: 1f491d3c-6b74-49c5-bca7-fc1a18ed68b5
		summarizeBy: none
		sourceColumn: tier_high_lifetime

		annotation SummarizationSetBy = Automatic

	column created_brt
		dataType: dateTime
		formatString: Long Date
		lineageTag: 88d1a3d5-183e-4e57-a722-1c25df44b9d7
		summarizeBy: none
		sourceColumn: created_brt

		variation Variation
			isDefault
			relationship: c02c86f0-0df2-4c49-81c3-a33c920d1a1b
			defaultHierarchy: LocalDateTable_c1116331-c76d-448c-a62e-1df1b6ebc8ef.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column hora_atualizacao
		dataType: dateTime
		formatString: General Date
		lineageTag: 461942f2-6c95-4909-9f6a-0077adb76f9e
		summarizeBy: none
		sourceColumn: hora_atualizacao

		variation Variation
			isDefault
			relationship: b2211950-270f-4db4-90fe-5d99bc16a909
			defaultHierarchy: LocalDateTable_7be2533f-3bcc-4695-943e-bf8f3da8689a.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column ano_semana_created = WEEKNUM(bd_kpc_acumulado[created_brt], 2)
		formatString: 0
		lineageTag: 3c0b9510-7618-40d4-83a9-edcc15b4bc07
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column ano_semana_updated = WEEKNUM(bd_kpc_acumulado[updated_brt], 2)
		formatString: 0
		lineageTag: 5b0f0e4d-e79d-409a-8ca9-73f63de4843a
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column LinkUserID = "https://admin-ai.kingpanda.com/users?userid=" & [userid]
		lineageTag: 533cfa91-3933-4b19-8bd6-70227f85e981
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition bd_kpc_acumulado = m
		mode: import
		source =
				let
				    Fonte = AzureStorage.DataLake("https://kplakehouse.dfs.core.windows.net/gold/kpc_acumulo"),
				    #"Linhas Filtradas" = Table.SelectRows(Fonte, each ([Extension] = ".parquet")),
				    #"Arquivos Ocultos Filtrados1" = Table.SelectRows(#"Linhas Filtradas", each [Attributes]?[Hidden]? <> true),
				    #"Invocar Função Personalizada1" = Table.AddColumn(#"Arquivos Ocultos Filtrados1", "Transformar Arquivo (46)", each #"Transformar Arquivo (46)"([Content])),
				    #"Colunas Renomeadas1" = Table.RenameColumns(#"Invocar Função Personalizada1", {"Name", "Nome da Origem"}),
				    #"Outras Colunas Removidas1" = Table.SelectColumns(#"Colunas Renomeadas1", {"Nome da Origem", "Transformar Arquivo (46)"}),
				    #"Coluna de Tabela Expandida1" = Table.ExpandTableColumn(#"Outras Colunas Removidas1", "Transformar Arquivo (46)", Table.ColumnNames(#"Transformar Arquivo (46)"(#"Arquivo de Amostra (46)"))),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Coluna de Tabela Expandida1",{{"Nome da Origem", type text}, {"userid", type text}, {"utm_source", type text}, {"utm_medium", type text}, {"utm_campaign", type text}, {"utm_content", type text}, {"utm_term", type text}, {"saldo_hoje", Int64.Type}, {"value_kpc", type number}, {"status", type any}, {"source", type any}, {"updated_brt", type any}, {"tier_l30d", type any}, {"tier_high_lifetime", type any}, {"created_brt", type date}, {"hora_atualizacao", type datetime}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

