table dim_data
	lineageTag: 1d0901d2-b519-4c00-a459-4dcaa3d85775

	column data
		dataType: dateTime
		formatString: Long Date
		lineageTag: 81c4f2f7-afd8-47d1-b5a7-3635d55e46e7
		summarizeBy: none
		sourceColumn: data

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ano_semana = WEEKNUM(dim_data[data], 2)
		formatString: 0
		lineageTag: a88394e4-7cd2-4e02-a4d0-30cfc0486ff1
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column utm_source_cadastro
		dataType: string
		lineageTag: 9af20d5f-d139-48aa-a5ac-142050dc24c6
		summarizeBy: none
		sourceColumn: utm_source_cadastro

		annotation SummarizationSetBy = Automatic

	column utm_medium_cadastro
		dataType: string
		lineageTag: e7ab61a9-50f9-4df8-99e9-7a55e02c0b68
		summarizeBy: none
		sourceColumn: utm_medium_cadastro

		annotation SummarizationSetBy = Automatic

	column utm_campaign_cadastro
		dataType: string
		lineageTag: 7c37c8a6-be4c-4fe0-a054-71b089658207
		summarizeBy: none
		sourceColumn: utm_campaign_cadastro

		annotation SummarizationSetBy = Automatic

	column utm_content_cadastro
		dataType: string
		lineageTag: 9af97a8a-cf37-43d0-bbd7-ccdc3a3f83e0
		summarizeBy: none
		sourceColumn: utm_content_cadastro

		annotation SummarizationSetBy = Automatic

	column utm_term_cadastro
		dataType: string
		lineageTag: 6415a360-ed22-4c8a-846d-887c88736bf0
		summarizeBy: none
		sourceColumn: utm_term_cadastro

		annotation SummarizationSetBy = Automatic

	column utm_source_deposito
		dataType: string
		lineageTag: e76efcaf-5397-4332-9889-61a562236484
		summarizeBy: none
		sourceColumn: utm_source_deposito

		annotation SummarizationSetBy = Automatic

	column utm_medium_deposito
		dataType: string
		lineageTag: 860835cd-b216-434b-a91b-930ad25b68cf
		summarizeBy: none
		sourceColumn: utm_medium_deposito

		annotation SummarizationSetBy = Automatic

	column utm_campaign_deposito
		dataType: string
		lineageTag: 7aeb0fe5-c1c0-4e38-8121-87c90df816f5
		summarizeBy: none
		sourceColumn: utm_campaign_deposito

		annotation SummarizationSetBy = Automatic

	column utm_content_deposito
		dataType: string
		lineageTag: e0fef3fc-905f-4cd4-b63e-ec58834ac4c6
		summarizeBy: none
		sourceColumn: utm_content_deposito

		annotation SummarizationSetBy = Automatic

	column utm_term_deposito
		dataType: string
		lineageTag: fa66c424-f8d2-4533-8594-ad0f45a81e3b
		summarizeBy: none
		sourceColumn: utm_term_deposito

		annotation SummarizationSetBy = Automatic

	column apostas_aberto
		dataType: string
		lineageTag: 2bcf086c-c9fa-4ee7-a810-1a130979253d
		summarizeBy: none
		sourceColumn: apostas_aberto

		annotation SummarizationSetBy = Automatic

	partition dim_data = m
		mode: import
		source =
				let
				    Fonte = AzureStorage.DataLake("https://kplakehouse.dfs.core.windows.net/gold/resumo_executivo_por_user"),
				    #"Linhas Filtradas" = Table.SelectRows(Fonte, each ([Extension] = ".parquet")),
				    #"Arquivos Ocultos Filtrados1" = Table.SelectRows(#"Linhas Filtradas", each [Attributes]?[Hidden]? <> true),
				    #"Invocar Função Personalizada1" = Table.AddColumn(#"Arquivos Ocultos Filtrados1", "Transformar Arquivo (15)", each #"Transformar Arquivo (15)"([Content])),
				    #"Colunas Renomeadas1" = Table.RenameColumns(#"Invocar Função Personalizada1", {"Name", "Nome da Origem"}),
				    #"Outras Colunas Removidas1" = Table.SelectColumns(#"Colunas Renomeadas1", {"Nome da Origem", "Transformar Arquivo (15)"}),
				    #"Coluna de Tabela Expandida1" = Table.ExpandTableColumn(#"Outras Colunas Removidas1", "Transformar Arquivo (15)", Table.ColumnNames(#"Transformar Arquivo (15)"(#"Arquivo de Amostra (15)"))),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Coluna de Tabela Expandida1",{{"Nome da Origem", type text}, {"userid", type text}, {"data", type date}, {"utm_source_cadastro", type text}, {"utm_medium_cadastro", type text}, {"utm_campaign_cadastro", type text}, {"utm_content_cadastro", type text}, {"utm_term_cadastro", type text}, {"utm_source_deposito", type text}, {"utm_medium_deposito", type text}, {"utm_campaign_deposito", type text}, {"utm_content_deposito", type text}, {"utm_term_deposito", type text}, {"usuarios_migrados", Int64.Type}, {"contas_novas", Int64.Type}, {"contas_depositantes", Int64.Type}, {"clientes_ativos", Int64.Type}, {"contas_ftd", Int64.Type}, {"deposito", Int64.Type}, {"qtd_depositos", Int64.Type}, {"qtd_saques", Int64.Type}, {"qtd_aposta_cassino", Int64.Type}, {"qtd_aposta_sportsbook", Int64.Type}, {"qtd_aposta_lb", Int64.Type}, {"saques", Int64.Type}, {"total_vip_proprio", Int64.Type}, {"total_vip_referral", Int64.Type}, {"total_vip_programa", Int64.Type}, {"total_crazy_friday", Int64.Type}, {"migracao_saldo", Int64.Type}, {"ajuste_saldo_manual", Int64.Type}, {"aposta_cassino", type number}, {"aposta_sportsbook", type number}, {"aposta_lb", Int64.Type}, {"premio_cassino", type number}, {"premio_sportsbook", Int64.Type}, {"premio_lb", Int64.Type}, {"ggr_cassino", type number}, {"ggr_sportsbook", type number}, {"ggr_lb", Int64.Type}, {"ngr", type number}, {"reward", type number}, {"premios_freespins", type number}, {"qtd_usuarios_com_premio_freespins", Int64.Type}, {"saldo_conta", type number}, {"hora_atualizacao", type datetime}, {"status_ativo_90d", Int64.Type}, {"media_l30d", type number}, {"tier_l30d", Int64.Type}, {"tier_high_lifetime", Int64.Type}, {"media_high_lifetime", Int64.Type}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Tipo Alterado",{"Nome da Origem", "userid", "usuarios_migrados", "contas_novas", "contas_depositantes", "clientes_ativos", "contas_ftd", "deposito", "qtd_depositos", "qtd_saques", "qtd_aposta_cassino", "qtd_aposta_sportsbook", "qtd_aposta_lb", "saques", "total_vip_proprio", "total_vip_referral", "total_vip_programa", "total_crazy_friday", "migracao_saldo", "ajuste_saldo_manual", "aposta_cassino", "aposta_sportsbook", "aposta_lb", "premio_cassino", "premio_sportsbook", "premio_lb", "ggr_cassino", "ggr_sportsbook", "ggr_lb", "ngr", "reward", "premios_freespins", "qtd_usuarios_com_premio_freespins", "saldo_conta", "hora_atualizacao", "status_ativo_90d", "media_l30d", "tier_l30d", "tier_high_lifetime", "media_high_lifetime"}),
				    #"Duplicatas Removidas" = Table.Distinct(#"Colunas Removidas"),
				    #"Duplicatas Removidas1" = Table.Distinct(#"Duplicatas Removidas", {"data"})
				in
				    #"Duplicatas Removidas1"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

