table fato_qtd_depositos
	lineageTag: 4b5e0607-5e82-4fa9-a492-b70aebca4db8

	column 'Nome da Origem'
		dataType: string
		lineageTag: f1dbaeef-0ddf-437a-a9c6-8b7371038466
		summarizeBy: none
		sourceColumn: Nome da Origem

		annotation SummarizationSetBy = Automatic

	column userid
		dataType: string
		lineageTag: 51263ece-bbfe-433f-9e0f-79b1d39b9e09
		summarizeBy: none
		sourceColumn: userid

		annotation SummarizationSetBy = Automatic

	column data
		dataType: dateTime
		formatString: Long Date
		lineageTag: 93868ac0-6156-4753-8e30-b6d30562e45d
		summarizeBy: none
		sourceColumn: data

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column qtd_depositos
		dataType: int64
		formatString: 0
		lineageTag: 68cb4557-1299-4b99-aea9-bef28e09d697
		summarizeBy: sum
		sourceColumn: qtd_depositos

		annotation SummarizationSetBy = Automatic

	column status_ativo_90d
		dataType: int64
		formatString: 0
		lineageTag: 14f06b67-8125-4969-b78e-69df78feb71d
		summarizeBy: sum
		sourceColumn: status_ativo_90d

		annotation SummarizationSetBy = Automatic

	column media_l30d
		dataType: double
		lineageTag: c9befe28-4450-4b7f-846e-8be032e9ee2d
		summarizeBy: sum
		sourceColumn: media_l30d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column tier_l30d
		dataType: int64
		formatString: 0
		lineageTag: 863fa90a-6712-4829-a669-6eec6e729f1a
		summarizeBy: sum
		sourceColumn: tier_l30d

		annotation SummarizationSetBy = Automatic

	column tier_high_lifetime
		dataType: int64
		formatString: 0
		lineageTag: cbf38554-2282-4791-a318-3efb1f74ec6d
		summarizeBy: sum
		sourceColumn: tier_high_lifetime

		annotation SummarizationSetBy = Automatic

	column media_high_lifetime
		dataType: double
		lineageTag: b96382ab-d57a-4862-a80f-00552142ddbe
		summarizeBy: sum
		sourceColumn: media_high_lifetime

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column hora_atualizacao
		dataType: dateTime
		formatString: General Date
		lineageTag: 4f36d225-5419-40a2-b7ca-f5eb4d8b1661
		summarizeBy: none
		sourceColumn: hora_atualizacao

		variation Variation
			isDefault
			relationship: 546c9803-85e1-4911-b653-1f556d7a7ba2
			defaultHierarchy: LocalDateTable_f77f53a1-8cc6-4ad4-be7b-c27d0e66bb54.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column data_replica = fato_qtd_depositos[data]
		formatString: General Date
		lineageTag: 1b3a1478-4876-49dc-b252-78a6d320164e
		summarizeBy: none

		variation Variation
			isDefault
			relationship: ffc34b73-b855-4389-82eb-e03ced1de4c1
			defaultHierarchy: LocalDateTable_f2aae8f3-44ae-488c-b7ee-a0d83a4c4342.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column ano_semana = WEEKNUM(fato_qtd_depositos[data], 2)
		formatString: 0
		lineageTag: b801c706-361c-4d46-839d-8815509f645c
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition fato_qtd_depositos = m
		mode: import
		source =
				let
				    Fonte = AzureStorage.DataLake("https://kplakehouse.dfs.core.windows.net/gold/datasets_linkados/qtd_depositos"),
				    #"Linhas Filtradas" = Table.SelectRows(Fonte, each ([Extension] = ".parquet")),
				    #"Arquivos Ocultos Filtrados1" = Table.SelectRows(#"Linhas Filtradas", each [Attributes]?[Hidden]? <> true),
				    #"Invocar Função Personalizada1" = Table.AddColumn(#"Arquivos Ocultos Filtrados1", "Transformar Arquivo (33)", each #"Transformar Arquivo (33)"([Content])),
				    #"Colunas Renomeadas1" = Table.RenameColumns(#"Invocar Função Personalizada1", {"Name", "Nome da Origem"}),
				    #"Outras Colunas Removidas1" = Table.SelectColumns(#"Colunas Renomeadas1", {"Nome da Origem", "Transformar Arquivo (33)"}),
				    #"Coluna de Tabela Expandida1" = Table.ExpandTableColumn(#"Outras Colunas Removidas1", "Transformar Arquivo (33)", Table.ColumnNames(#"Transformar Arquivo (33)"(#"Arquivo de Amostra (33)"))),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Coluna de Tabela Expandida1",{{"Nome da Origem", type text}, {"userid", type text}, {"data", type date}, {"qtd_depositos", Int64.Type}, {"status_ativo_90d", Int64.Type}, {"media_l30d", type number}, {"tier_l30d", Int64.Type}, {"tier_high_lifetime", Int64.Type}, {"media_high_lifetime", type number}, {"hora_atualizacao", type datetime}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

