table fato_ftd
	lineageTag: 5586fa9a-0f5f-467a-9103-dde6a50b9243

	column 'Nome da Origem'
		dataType: string
		lineageTag: 3dee8c63-d778-4fe4-9561-9c36026c45f1
		summarizeBy: none
		sourceColumn: Nome da Origem

		annotation SummarizationSetBy = Automatic

	column userid
		dataType: string
		lineageTag: f0ed0876-1581-4886-80dc-3d8347de9c41
		summarizeBy: none
		sourceColumn: userid

		annotation SummarizationSetBy = Automatic

	column data
		dataType: dateTime
		formatString: Long Date
		lineageTag: f51fa938-0919-414c-95c5-afac59709e0a
		summarizeBy: none
		sourceColumn: data

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column contas_ftd
		dataType: int64
		formatString: 0
		lineageTag: 1248d645-c796-4dfc-98f9-9e7df3aa4f79
		summarizeBy: sum
		sourceColumn: contas_ftd

		annotation SummarizationSetBy = Automatic

	column status_ativo_90d
		dataType: int64
		formatString: 0
		lineageTag: 00bc39f4-3e3f-4c98-955d-aa806dc917cd
		summarizeBy: sum
		sourceColumn: status_ativo_90d

		annotation SummarizationSetBy = Automatic

	column media_l30d
		dataType: double
		lineageTag: 694dcc3e-6b11-4347-8ba1-3faa6dce7500
		summarizeBy: sum
		sourceColumn: media_l30d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column tier_l30d
		dataType: int64
		formatString: 0
		lineageTag: af571172-9b26-4af1-9422-bfa1695c5ea2
		summarizeBy: sum
		sourceColumn: tier_l30d

		annotation SummarizationSetBy = Automatic

	column tier_high_lifetime
		dataType: int64
		formatString: 0
		lineageTag: bbb6191d-8011-4842-b166-a516c0f1d7b7
		summarizeBy: sum
		sourceColumn: tier_high_lifetime

		annotation SummarizationSetBy = Automatic

	column media_high_lifetime
		dataType: double
		lineageTag: e432574c-de9e-4e51-a7ea-789ae54f15ae
		summarizeBy: sum
		sourceColumn: media_high_lifetime

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column hora_atualizacao
		dataType: dateTime
		formatString: General Date
		lineageTag: 976d0c6e-da61-4a2c-87f2-09d60134072b
		summarizeBy: none
		sourceColumn: hora_atualizacao

		variation Variation
			isDefault
			relationship: 5ba13074-8311-44d9-bec4-2ea288795c6c
			defaultHierarchy: LocalDateTable_8576adda-ce27-4187-b584-43df18cad42c.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column data_replica = fato_ftd[data]
		formatString: General Date
		lineageTag: 10866789-34bf-470d-93bd-da7c304d17bb
		summarizeBy: none

		variation Variation
			isDefault
			relationship: 2aa07f21-a7f2-458c-8ddc-c065d3247cbe
			defaultHierarchy: LocalDateTable_2f9fc419-2d9b-47ca-8628-ac885868fa4d.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column ano_semana = WEEKNUM(fato_ftd[data], 2)
		formatString: 0
		lineageTag: 484884d3-96b9-49b8-b13a-0a8f1a0a684f
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition fato_ftd = m
		mode: import
		source =
				let
				    Fonte = AzureStorage.DataLake("https://kplakehouse.dfs.core.windows.net/gold/datasets_linkados/contas_ftd"),
				    #"Linhas Filtradas" = Table.SelectRows(Fonte, each ([Extension] = ".parquet")),
				    #"Arquivos Ocultos Filtrados2" = Table.SelectRows(#"Linhas Filtradas", each [Attributes]?[Hidden]? <> true),
				    #"Invocar Função Personalizada2" = Table.AddColumn(#"Arquivos Ocultos Filtrados2", "Transformar Arquivo (7)", each #"Transformar Arquivo (7)"([Content])),
				    #"Colunas Renomeadas2" = Table.RenameColumns(#"Invocar Função Personalizada2", {"Name", "Nome da Origem"}),
				    #"Outras Colunas Removidas2" = Table.SelectColumns(#"Colunas Renomeadas2", {"Nome da Origem", "Transformar Arquivo (7)"}),
				    #"Coluna de Tabela Expandida2" = Table.ExpandTableColumn(#"Outras Colunas Removidas2", "Transformar Arquivo (7)", Table.ColumnNames(#"Transformar Arquivo (7)"(#"Arquivo de Amostra (7)"))),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Coluna de Tabela Expandida2",{{"Nome da Origem", type text}, {"userid", type text}, {"data", type date}, {"contas_ftd", Int64.Type}, {"status_ativo_90d", Int64.Type}, {"media_l30d", type number}, {"tier_l30d", Int64.Type}, {"tier_high_lifetime", Int64.Type}, {"media_high_lifetime", type number}, {"hora_atualizacao", type datetime}}),
				    #"Arquivos Ocultos Filtrados1" = Table.SelectRows(#"Tipo Alterado1", each [Attributes]?[Hidden]? <> true),
				    #"Invocar Função Personalizada1" = Table.AddColumn(#"Arquivos Ocultos Filtrados1", "Transformar Arquivo (30)", each #"Transformar Arquivo (30)"([Content])),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Invocar Função Personalizada1",{"Transformar Arquivo (30)"})
				in
				    #"Colunas Removidas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

