table Top5_Aposta_Rollback_producer
	lineageTag: 755be70c-30ba-4795-b6b0-badd2787562a

	measure 'Aposta Rollback (Top5 dinâmico)' = ```
			
			VAR Base =
			    SUMMARIZE (                          -- cria provedor + total do contexto
			        ALLSELECTED ( 'bd_softswiss'[producer] ),
			        'bd_softswiss'[producer],
			        "ApostaRollback", [aposta_rollback_com_outros]
			    )
			
			VAR TopTable =                          -- mantém só os 5 maiores
			    TOPN ( 5, Base, [ApostaRollback], DESC )
			
			/* ► Novo passo: extrai APENAS a coluna provider  ◄ */
			VAR TopProv =
			    SELECTCOLUMNS ( TopTable,            -- agora vira tabela de 1 coluna
			        "producer", [producer] )
			
			VAR SelProv =
			    SELECTEDVALUE ( Top5_Aposta_Rollback_producer[producer] ) -- provedor/“Outros” clicado
			
			RETURN
			SWITCH (
			    TRUE(),
			    /* --- Bloco “Outros” ----------------------------------------------- */
			    SelProv = "Outros",
			        CALCULATE (
			            [aposta_rollback_com_outros],
			            /* aplica filtro-tabela com EXCEPT (ambas 1 coluna) */
			            KEEPFILTERS (
			                EXCEPT (
			                    ALLSELECTED ( 'bd_softswiss'[producer] ),   -- universo
			                    TopProv                                     -- tira Top 5
			                )
			            )
			        ),
			    /* --- Quando é um provedor específico ------------------------------ */
			    CALCULATE (
			        [aposta_rollback_com_outros],
			        'bd_softswiss'[producer] = SelProv
			    )
			)
			
			```
		lineageTag: 7ae493bb-b55b-4d58-aa57-bdbd46f69028

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Aposta Rollback Producer (Top 5 dinâmico c/ “Outros”)' = ```
			
			/* ------------------------------------------------------------------ */
			/* 1. Monta a lista já filtrada de provedores e calcula seu total     */
			VAR Base =
			    SUMMARIZE (
			        VALUES ( 'bd_softswiss'[producer] ),         -- mantém filtro atual
			        'bd_softswiss'[producer],
			        "ApostaRollback", [aposta_rollback_com_outros]
			    )
			
			/* 2. Pega os 5 maiores valores dentro desse subconjunto              */
			VAR TopTable =
			    TOPN ( 5, Base, [ApostaRollback], DESC )
			
			/* 3. Converte em tabela de 1 coluna para comparação/EXCEPT           */
			VAR TopProv =
			    SELECTCOLUMNS ( TopTable, "producer", [producer] )
			
			/* 4. Quem é a linha que o visual está pedindo no momento?            */
			VAR SelProv =
			    SELECTEDVALUE ( Top5_Aposta_Rollback_producer[producer] )
			
			/* 5. SelProv está ou não no Top 5?                                   */
			VAR IsInTop =
			    CONTAINS ( TopProv, [producer], SelProv )
			
			/* ------------------------------------------------------------------ */
			RETURN
			SWITCH (
			    TRUE(),
			
			    /* --- Linha “Outros” -------------------------------------------- */
			    SelProv = "Outros",
			        CALCULATE (
			            [aposta_rollback_com_outros],
			            KEEPFILTERS (
			                EXCEPT (                       -- tudo que não for Top 5
			                    VALUES ( 'bd_softswiss'[producer] ),
			                    TopProv
			                )
			            )
			        ),
			
			    /* --- Linha que faz parte do Top 5 ------------------------------ */
			    IsInTop,
			        CALCULATE (
			            [aposta_rollback_com_outros],
			            'bd_softswiss'[producer] = SelProv
			        ),
			
			    /* --- Qualquer outra linha (não Top 5 nem “Outros”) ------------- */
			    BLANK()
			)
			
			```
		lineageTag: f3444fe9-fc5c-4230-96d2-2f725335c913

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column producer
		lineageTag: 37417715-56de-4633-8f50-8544dd8a9c94
		summarizeBy: none
		isNameInferred
		sourceColumn: [producer]

		annotation SummarizationSetBy = Automatic

	partition Top5_Aposta_Rollback_producer = calculated
		mode: import
		source = ```
				
				UNION (
				    SELECTCOLUMNS (
				        DISTINCT ( 'bd_softswiss'[producer] ),   -- um por provedor
				        "producer", 'bd_softswiss'[producer]
				    ),
				    DATATABLE (                                   -- adiciona a linha “Outros”
				        "producer", STRING, { { "Outros" } }
				    )
				)
				
				```

	annotation PBI_Id = a89fdf8886a14596b9554971c372331f

