table Top5_Premio_Rollback_producer
	lineageTag: 93b2bf48-6b44-4a2b-b2df-00614ede5b8a

	measure 'Premio Rollback (Top5 dinâmico)' = ```
			
			VAR Base =
			    SUMMARIZE (                          -- cria provedor + total do contexto
			        ALLSELECTED ( 'bd_softswiss'[producer] ),
			        'bd_softswiss'[producer],
			        "PremioRollback", [premio_rollback_com_outros]
			    )
			
			VAR TopTable =                          -- mantém só os 5 maiores
			    TOPN ( 5, Base, [PremioRollback], DESC )
			
			/* ► Novo passo: extrai APENAS a coluna provider  ◄ */
			VAR TopProv =
			    SELECTCOLUMNS ( TopTable,            -- agora vira tabela de 1 coluna
			        "producer", [producer] )
			
			VAR SelProv =
			    SELECTEDVALUE ( Top5_Premio_Rollback_producer[producer] ) -- provedor/“Outros” clicado
			
			RETURN
			SWITCH (
			    TRUE(),
			    /* --- Bloco “Outros” ----------------------------------------------- */
			    SelProv = "Outros",
			        CALCULATE (
			            [premio_rollback_com_outros],
			            /* aplica filtro-tabela com EXCEPT (ambas 1 coluna) */
			            KEEPFILTERS (
			                EXCEPT (
			                    ALLSELECTED ( 'bd_softswiss'[producer] ),   -- universo
			                    TopProv                                     -- tira Top 5
			                )
			            )
			        ),
			    /* --- Quando é um provedor específico ------------------------------ */
			    CALCULATE (
			        [premio_rollback_com_outros],
			        'bd_softswiss'[producer] = SelProv
			    )
			)
			
			```
		formatString: 0
		lineageTag: 2345ac5b-cc9f-4012-8be9-2c91641b7220

	measure 'Prêmio Rollback Producer (Top 5 dinâmico c/"Outros")' = ```
			
			/* ------------------------------------------------------------------ */
			/* 1. Monta a lista já filtrada de provedores e calcula seu total     */
			VAR Base =
			    SUMMARIZE (
			        VALUES ( 'bd_softswiss'[producer] ),         -- mantém filtro atual
			        'bd_softswiss'[producer],
			        "PremioRollback", [premio_rollback_com_outros]
			    )
			
			/* 2. Pega os 5 maiores valores dentro desse subconjunto              */
			VAR TopTable =
			    TOPN ( 5, Base, [PremioRollback], DESC )
			
			/* 3. Converte em tabela de 1 coluna para comparação/EXCEPT           */
			VAR TopProv =
			    SELECTCOLUMNS ( TopTable, "producer", [producer] )
			
			/* 4. Quem é a linha que o visual está pedindo no momento?            */
			VAR SelProv =
			    SELECTEDVALUE ( Top5_Premio_Rollback_producer[producer] )
			
			/* 5. SelProv está ou não no Top 5?                                   */
			VAR IsInTop =
			    CONTAINS ( TopProv, [producer], SelProv )
			
			/* ------------------------------------------------------------------ */
			RETURN
			SWITCH (
			    TRUE(),
			
			    /* --- Linha “Outros” -------------------------------------------- */
			    SelProv = "Outros",
			        CALCULATE (
			            [premio_rollback_com_outros],
			            KEEPFILTERS (
			                EXCEPT (                       -- tudo que não for Top 5
			                    VALUES ( 'bd_softswiss'[producer] ),
			                    TopProv
			                )
			            )
			        ),
			
			    /* --- Linha que faz parte do Top 5 ------------------------------ */
			    IsInTop,
			        CALCULATE (
			            [premio_rollback_com_outros],
			            'bd_softswiss'[producer] = SelProv
			        ),
			
			    /* --- Qualquer outra linha (não Top 5 nem “Outros”) ------------- */
			    BLANK()
			)
			
			```
		lineageTag: f84d7515-78e5-4438-a271-8676fdaaef31

	column producer
		lineageTag: 4fd1d889-961e-4773-b0ba-f670ea70ae19
		summarizeBy: none
		isNameInferred
		sourceColumn: [producer]

		annotation SummarizationSetBy = Automatic

	partition Top5_Premio_Rollback_producer = calculated
		mode: import
		source =
				
				UNION (
				    SELECTCOLUMNS (
				        DISTINCT ( 'bd_softswiss'[producer] ),   -- um por provedor
				        "producer", 'bd_softswiss'[producer]
				    ),
				    DATATABLE (                                   -- adiciona a linha “Outros”
				        "producer", STRING, { { "Outros" } }
				    )
				)

	annotation PBI_Id = a0ee5ddc1a19439aa48e88485b52a1b6

