table Top5_Clientes_Ativos_producer
	lineageTag: 73b3d782-351e-4444-bca2-1c3895e6c195

	measure 'Clientes Ativos (Top5 dinâmico)' = ```
			
			VAR Base =
			    SUMMARIZE (                          -- cria provedor + total do contexto
			        ALLSELECTED ( 'bd_softswiss'[producer] ),
			        'bd_softswiss'[producer],
			        "ClientesAtivos", [clientes_ativos_com_outros]
			    )
			
			VAR TopTable =                          -- mantém só os 5 maiores
			    TOPN ( 5, Base, [ClientesAtivos], DESC )
			
			/* ► Novo passo: extrai APENAS a coluna provider  ◄ */
			VAR TopProv =
			    SELECTCOLUMNS ( TopTable,            -- agora vira tabela de 1 coluna
			        "producer", [producer] )
			
			VAR SelProv =
			    SELECTEDVALUE ( Top5_Clientes_Ativos_producer[producer] ) -- provedor/“Outros” clicado
			
			RETURN
			SWITCH (
			    TRUE(),
			    /* --- Bloco “Outros” ----------------------------------------------- */
			    SelProv = "Outros",
			        CALCULATE (
			            [clientes_ativos_com_outros],
			            /* aplica filtro-tabela com EXCEPT (ambas 1 coluna) */
			            KEEPFILTERS (
			                EXCEPT (
			                    ALLSELECTED ( 'bd_softswiss'[producer] ),   -- universo
			                    TopProv                                     -- tira Top 5
			                )
			            )
			        ),
			    /* --- Quando é um provedor específico ------------------------------ */
			    CALCULATE (
			        [clientes_ativos_com_outros],
			        'bd_softswiss'[producer] = SelProv
			    )
			)
			
			```
		formatString: 0
		lineageTag: 9faad6a9-7a9f-48b1-a4e3-4dfc18292ebf

	measure 'Clientes Ativos Producer (Top 5 dinâmico c/"Outros")' = ```
			
			/* ------------------------------------------------------------------ */
			/* 1. Monta a lista já filtrada de provedores e calcula seu total     */
			VAR Base =
			    SUMMARIZE (
			        VALUES ( 'bd_softswiss'[producer] ),         -- mantém filtro atual
			        'bd_softswiss'[producer],
			        "ClientesAtivos", [clientes_ativos_com_outros]
			    )
			
			/* 2. Pega os 5 maiores valores dentro desse subconjunto              */
			VAR TopTable =
			    TOPN ( 5, Base, [ClientesAtivos], DESC )
			
			/* 3. Converte em tabela de 1 coluna para comparação/EXCEPT           */
			VAR TopProv =
			    SELECTCOLUMNS ( TopTable, "producer", [producer] )
			
			/* 4. Quem é a linha que o visual está pedindo no momento?            */
			VAR SelProv =
			    SELECTEDVALUE ( Top5_Clientes_Ativos_producer[producer] )
			
			/* 5. SelProv está ou não no Top 5?                                   */
			VAR IsInTop =
			    CONTAINS ( TopProv, [producer], SelProv )
			
			/* ------------------------------------------------------------------ */
			RETURN
			SWITCH (
			    TRUE(),
			
			    /* --- Linha “Outros” -------------------------------------------- */
			    SelProv = "Outros",
			        CALCULATE (
			            [clientes_ativos_com_outros],
			            KEEPFILTERS (
			                EXCEPT (                       -- tudo que não for Top 5
			                    VALUES ( 'bd_softswiss'[producer] ),
			                    TopProv
			                )
			            )
			        ),
			
			    /* --- Linha que faz parte do Top 5 ------------------------------ */
			    IsInTop,
			        CALCULATE (
			            [clientes_ativos_com_outros],
			            'bd_softswiss'[producer] = SelProv
			        ),
			
			    /* --- Qualquer outra linha (não Top 5 nem “Outros”) ------------- */
			    BLANK()
			)
			
			```
		formatString: 0
		lineageTag: 16e8b5e3-0a7b-44c7-84a5-72fbfc72c081

	column producer
		lineageTag: f6fa0e12-f248-4a27-bd40-a95f4bc66b25
		summarizeBy: none
		isNameInferred
		sourceColumn: [producer]

		annotation SummarizationSetBy = Automatic

	partition Top5_Clientes_Ativos_producer = calculated
		mode: import
		source =
				
				UNION (
				    SELECTCOLUMNS (
				        DISTINCT ( 'bd_softswiss'[producer] ),   -- um por provedor
				        "producer", 'bd_softswiss'[producer]
				    ),
				    DATATABLE (                                   -- adiciona a linha “Outros”
				        "producer", STRING, { { "Outros" } }
				    )
				)

	annotation PBI_Id = b6f7f24a9f2a4999a824c6179b338f1f

