table 'Valor Depósito'
	lineageTag: 2a259832-101a-4763-adcc-6513e95c20a9

	measure 'Valor Valor Depósito' = SELECTEDVALUE('Valor Depósito'[Valor Depósito], 0)
		formatString: 0
		lineageTag: 2d0113cd-2639-453c-8c90-51cff39af94e

	column 'Valor Depósito'
		formatString: #,0
		lineageTag: a42ec12f-d29e-4b8a-8126-9e6e920d4dea
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition 'Valor Depósito' = calculated
		mode: import
		source = GENERATESERIES(0, 50000000, 100000)

	annotation PBI_Id = 83151ffbbaaf421186593cceac899960

