table bd_ajuste_saldo_manual
	lineageTag: 49195b99-195b-4ff3-b898-41f58191386e

	column 'Nome da Origem'
		dataType: string
		lineageTag: cc8d8c08-bb93-4657-9e13-dc36952dee82
		summarizeBy: none
		sourceColumn: Nome da Origem

		annotation SummarizationSetBy = Automatic

	column userid
		dataType: string
		lineageTag: a4d7a933-7953-40c7-8e37-8c47c6caa376
		summarizeBy: none
		sourceColumn: userid

		annotation SummarizationSetBy = Automatic

	column data
		dataType: dateTime
		formatString: General Date
		lineageTag: f66775c9-fbc8-43e9-a1db-fb00e98b7329
		summarizeBy: none
		sourceColumn: data

		variation Variation
			isDefault
			relationship: fe72a520-de05-4d37-b265-c1658f1ab50c
			defaultHierarchy: LocalDateTable_5b3b89ad-1a82-4127-b48f-165b5055501e.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column utm_campaign
		dataType: string
		lineageTag: e9f9e52f-91c8-4cc8-b8e3-4a87ae35b6cf
		summarizeBy: none
		sourceColumn: utm_campaign

		annotation SummarizationSetBy = Automatic

	column utm_source
		dataType: string
		lineageTag: 2ea43232-720e-4444-9ee3-7c2b36429b41
		summarizeBy: none
		sourceColumn: utm_source

		annotation SummarizationSetBy = Automatic

	column utm_medium
		dataType: string
		lineageTag: ad1b8e5d-2af2-4ca1-bb24-ae8e5202f818
		summarizeBy: none
		sourceColumn: utm_medium

		annotation SummarizationSetBy = Automatic

	column utm_content
		dataType: string
		lineageTag: 85d3c3e1-3cf2-41cc-85a8-284e3b88376e
		summarizeBy: none
		sourceColumn: utm_content

		annotation SummarizationSetBy = Automatic

	column utm_term
		dataType: string
		lineageTag: 6d23289e-20fe-4c13-948f-c3f77793b205
		summarizeBy: none
		sourceColumn: utm_term

		annotation SummarizationSetBy = Automatic

	column sigap_type
		dataType: string
		lineageTag: 9f709e25-a867-4c6e-bde2-338928d39f48
		summarizeBy: none
		sourceColumn: sigap_type

		annotation SummarizationSetBy = Automatic

	column amount
		dataType: double
		lineageTag: 9dc9e659-abc9-44f5-9c90-20cf90ba448b
		summarizeBy: sum
		sourceColumn: amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column hora_atualizacao
		dataType: dateTime
		formatString: General Date
		lineageTag: c7aefdbf-be6f-4009-9399-e948514ff667
		summarizeBy: none
		sourceColumn: hora_atualizacao

		variation Variation
			isDefault
			relationship: c5f7d6ee-d632-4bbe-b46d-4572ffa560fb
			defaultHierarchy: LocalDateTable_93d58e86-e035-4f0c-a256-f18a1c0c4aa0.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column LinkUserID = "https://admin-ai.kingpanda.com/users?userid=" & [userid]
		lineageTag: 88eeb6b5-31d0-4a0f-8692-f9c5cae181fa
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition bd_ajuste_saldo_manual = m
		mode: import
		source =
				let
				    Fonte = AzureStorage.DataLake("https://kplakehouse.dfs.core.windows.net/gold/ajuste_saldo_manual"),
				    #"Linhas Filtradas" = Table.SelectRows(Fonte, each ([Extension] = ".parquet")),
				    #"Arquivos Ocultos Filtrados1" = Table.SelectRows(#"Linhas Filtradas", each [Attributes]?[Hidden]? <> true),
				    #"Invocar Função Personalizada1" = Table.AddColumn(#"Arquivos Ocultos Filtrados1", "Transformar Arquivo", each #"Transformar Arquivo"([Content])),
				    #"Colunas Renomeadas1" = Table.RenameColumns(#"Invocar Função Personalizada1", {"Name", "Nome da Origem"}),
				    #"Outras Colunas Removidas1" = Table.SelectColumns(#"Colunas Renomeadas1", {"Nome da Origem", "Transformar Arquivo"}),
				    #"Coluna de Tabela Expandida1" = Table.ExpandTableColumn(#"Outras Colunas Removidas1", "Transformar Arquivo", Table.ColumnNames(#"Transformar Arquivo"(#"Arquivo de Amostra"))),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Coluna de Tabela Expandida1",{{"Nome da Origem", type text}, {"userid", type text}, {"data", type datetime}, {"utm_campaign", type text}, {"utm_source", type text}, {"utm_medium", type text}, {"utm_content", type text}, {"utm_term", type text}, {"sigap_type", type text}, {"amount", type number}, {"hora_atualizacao", type datetime}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

