table bd_cohort
	lineageTag: c68c5a60-6a16-48fb-af9f-c5c6f0dc5e39

	measure usuarios_cadastros =
			
			CALCULATE(
			    DISTINCTCOUNT([userid]),
			    FILTER(
			        bd_cohort,
			        [MesesDesdeCadastro] = 0
			    )
			)
		formatString: 0
		lineageTag: c285a4c3-e07a-488f-9d3d-d6950af17946

	measure usuarios_retidos = DISTINCTCOUNT([userid])
		formatString: 0
		lineageTag: eae450e4-918d-49bf-b1bc-c722ffe9e3bb

	measure usuario_retencao =
			
			DIVIDE(
			    [usuarios_retidos],
			    [usuarios_cadastros],
			    0
			)
		lineageTag: 0cba7664-4032-4246-9074-b79e14519a00

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column utm_source
		lineageTag: d16cbe0a-0dcf-460a-b58c-d6d397c3e156
		summarizeBy: none
		isNameInferred
		sourceColumn: [utm_source]

		annotation SummarizationSetBy = Automatic

	column utm_medium
		lineageTag: aefbe3b8-d1ba-4aec-9c21-9db86be21025
		summarizeBy: none
		isNameInferred
		sourceColumn: [utm_medium]

		annotation SummarizationSetBy = Automatic

	column utm_content
		lineageTag: 9487d111-9723-4359-a316-f1f0391bec25
		summarizeBy: none
		isNameInferred
		sourceColumn: [utm_content]

		annotation SummarizationSetBy = Automatic

	column utm_campaign
		lineageTag: 7a49f40d-66a2-4e9a-a0d0-469d116882e8
		summarizeBy: none
		isNameInferred
		sourceColumn: [utm_campaign]

		annotation SummarizationSetBy = Automatic

	column utm_term
		lineageTag: 1f3d2aca-a112-4a3f-afba-87b3696e7d76
		summarizeBy: none
		isNameInferred
		sourceColumn: [utm_term]

		annotation SummarizationSetBy = Automatic

	column created_brt_date
		formatString: General Date
		lineageTag: 30bf2c4c-e786-4b7e-afa3-65a60a824382
		summarizeBy: none
		isNameInferred
		sourceColumn: [created_brt_date]

		variation Variation
			isDefault
			relationship: addbf99a-39aa-4c72-80d1-2a11d2b9cfa3
			defaultHierarchy: LocalDateTable_76247cfe-658f-4901-a3ae-1b5cf92d10bb.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column data_ftd_brt_date
		formatString: General Date
		lineageTag: c6aeab16-10a7-49a9-b47d-d3a17d6d1f75
		summarizeBy: none
		isNameInferred
		sourceColumn: [data_ftd_brt_date]

		variation Variation
			isDefault
			relationship: 890af73f-50e4-4884-ab51-9c76b11a3fab
			defaultHierarchy: LocalDateTable_0e2117ae-2a95-47a1-b5c5-c8faf90f83af.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column userid
		lineageTag: ae087e3e-0327-43c5-a485-53426cde4a0f
		summarizeBy: none
		isNameInferred
		sourceColumn: [userid]

		annotation SummarizationSetBy = Automatic

	column MesCadastro
		lineageTag: 6216fd94-489b-4668-9791-2350f0894a23
		summarizeBy: none
		isNameInferred
		sourceColumn: [MesCadastro]

		annotation SummarizationSetBy = Automatic

	column MesAtividade
		lineageTag: 1eacbcc4-d0f3-4651-b1b0-f977e06888be
		summarizeBy: none
		isNameInferred
		sourceColumn: [MesAtividade]

		annotation SummarizationSetBy = Automatic

	column MesesDesdeCadastro
		formatString: 0
		lineageTag: d38b4361-e70a-478f-96c8-d4622038a244
		summarizeBy: sum
		isNameInferred
		sourceColumn: [MesesDesdeCadastro]

		annotation SummarizationSetBy = Automatic

	partition bd_cohort = calculated
		mode: import
		source = ```
				
				SELECTCOLUMNS(bd_growth, 
				    "utm_source", [utm_source],
				    "utm_medium", [utm_medium],
				    "utm_content", [utm_content],
				    "utm_campaign", [utm_campaign],
				    "utm_term", [utm_term],
				    "created_brt_date", [created_brt_date],
				    "data_ftd_brt_date", [data_ftd_brt_date],
				    "userid", [userid],
				    "MesCadastro", FORMAT([created_brt], "YYYY-MM"),
				    "MesAtividade", FORMAT([data_ftd_brt_date], "YYYY-MM"),
				    "MesesDesdeCadastro", DATEDIFF([created_brt], [data_ftd_brt], MONTH)
				)
				
				```

	annotation PBI_Id = d1189d639c9d4dd8b9bd653c17c58790

