table bd_comparativo
	lineageTag: 8dec9627-124f-4023-80d5-101629d690af

	column 'Nome da Origem'
		dataType: string
		lineageTag: 892bd08d-322a-4368-8f2b-f172e494754e
		summarizeBy: none
		sourceColumn: Nome da Origem

		annotation SummarizationSetBy = Automatic

	column data
		dataType: dateTime
		formatString: Long Date
		lineageTag: 230941c3-579f-41e8-99da-09bead5e50c7
		summarizeBy: none
		sourceColumn: data

		variation Variation
			isDefault
			relationship: dfc5fd63-bf48-499d-b1b8-cc737284c655
			defaultHierarchy: LocalDateTable_96bb169f-8ccd-43c4-a730-16727817bd0e.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column userid
		dataType: string
		lineageTag: 051686a1-8798-4535-927a-88dab41b07d5
		summarizeBy: none
		sourceColumn: userid

		annotation SummarizationSetBy = Automatic

	column deposito
		dataType: int64
		formatString: 0
		lineageTag: 1e746d53-39c4-4777-9750-ac14c5479342
		summarizeBy: sum
		sourceColumn: deposito

		annotation SummarizationSetBy = Automatic

	column contas_depositantes
		dataType: int64
		formatString: 0
		lineageTag: 023c4c1f-b991-4d45-922a-5ff1abb6f058
		summarizeBy: sum
		sourceColumn: contas_depositantes

		annotation SummarizationSetBy = Automatic

	column contas_novas
		dataType: int64
		formatString: 0
		lineageTag: d2419a6a-3efa-4a7d-8a04-2a787097339c
		summarizeBy: sum
		sourceColumn: contas_novas

		annotation SummarizationSetBy = Automatic

	column contas_ftd
		dataType: int64
		formatString: 0
		lineageTag: de18f747-308d-4d7c-b5a0-6285236b0ccb
		summarizeBy: sum
		sourceColumn: contas_ftd

		annotation SummarizationSetBy = Automatic

	column utm_source_cadastro
		dataType: string
		lineageTag: 02bbec9a-9972-45b4-8c13-cc3913ccac22
		summarizeBy: none
		sourceColumn: utm_source_cadastro

		annotation SummarizationSetBy = Automatic

	column utm_medium_cadastro
		dataType: string
		lineageTag: 9b061cf6-b62d-42be-8047-ea2f789664d6
		summarizeBy: none
		sourceColumn: utm_medium_cadastro

		annotation SummarizationSetBy = Automatic

	column utm_campaign_cadastro
		dataType: string
		lineageTag: 9a5921db-2954-437d-ae62-b880739f7f4d
		summarizeBy: none
		sourceColumn: utm_campaign_cadastro

		annotation SummarizationSetBy = Automatic

	column utm_content_cadastro
		dataType: string
		lineageTag: c555a71e-d387-4272-8fbf-433684d06ea8
		summarizeBy: none
		sourceColumn: utm_content_cadastro

		annotation SummarizationSetBy = Automatic

	column utm_term_cadastro
		dataType: string
		lineageTag: 6c032572-4b2c-484f-b742-51f58d33d001
		summarizeBy: none
		sourceColumn: utm_term_cadastro

		annotation SummarizationSetBy = Automatic

	column utm_source_deposito
		dataType: string
		lineageTag: d5c83dfc-4644-4461-9ae0-7d0bcf0d3345
		summarizeBy: none
		sourceColumn: utm_source_deposito

		annotation SummarizationSetBy = Automatic

	column utm_medium_deposito
		dataType: string
		lineageTag: 9bac0ef7-956d-44b1-a773-2db7aa6317ce
		summarizeBy: none
		sourceColumn: utm_medium_deposito

		annotation SummarizationSetBy = Automatic

	column utm_campaign_deposito
		dataType: string
		lineageTag: 63f3722f-64f6-4de2-bcb3-d86b64477f62
		summarizeBy: none
		sourceColumn: utm_campaign_deposito

		annotation SummarizationSetBy = Automatic

	column utm_content_deposito
		dataType: string
		lineageTag: d050ecd6-5902-4de4-be9f-fef95d2e7393
		summarizeBy: none
		sourceColumn: utm_content_deposito

		annotation SummarizationSetBy = Automatic

	column utm_term_deposito
		dataType: string
		lineageTag: aaed7de5-8497-497e-96e5-a8ae401025c2
		summarizeBy: none
		sourceColumn: utm_term_deposito

		annotation SummarizationSetBy = Automatic

	column tier_l30d
		dataType: int64
		formatString: 0
		lineageTag: 7306ceb1-6646-4b80-b126-44a6148c33bf
		summarizeBy: sum
		sourceColumn: tier_l30d

		annotation SummarizationSetBy = Automatic

	column tier_high_lifetime
		dataType: int64
		formatString: 0
		lineageTag: 5241412c-d52a-4002-9161-77bee7c3284a
		summarizeBy: sum
		sourceColumn: tier_high_lifetime

		annotation SummarizationSetBy = Automatic

	column hora_atualizacao
		dataType: dateTime
		formatString: General Date
		lineageTag: ef854a20-b04b-48f9-a803-66981a35b95d
		summarizeBy: none
		sourceColumn: hora_atualizacao

		variation Variation
			isDefault
			relationship: b7daa82a-43e6-480b-9caa-4381dc8bcdb9
			defaultHierarchy: LocalDateTable_af2653dd-ca79-447d-8f2c-b1a63411640e.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column Conta_nova_mes = ```
			
			VAR MesCriacao =
			    CALCULATE (
			        MIN ( bd_comparativo[data] ),
			        bd_comparativo[contas_novas] = 1,
			        ALLEXCEPT ( bd_comparativo, bd_comparativo[userid] )
			    )
			RETURN
			IF (
			    YEAR ( bd_comparativo[data] ) = YEAR ( MesCriacao ) &&
			    MONTH ( bd_comparativo[data] ) = MONTH ( MesCriacao ),
			    1,
			    0
			)
			
			```
		formatString: 0
		lineageTag: 9d6c9635-3c6b-4fa9-8342-900c98b5772b
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition bd_comparativo = m
		mode: import
		source =
				let
				    Fonte = AzureStorage.DataLake("https://kplakehouse.dfs.core.windows.net/gold/comparativo_mkt"),
				    #"Linhas Filtradas1" = Table.SelectRows(Fonte, each ([Extension] = ".parquet")),
				    #"Arquivos Ocultos Filtrados1" = Table.SelectRows(#"Linhas Filtradas1", each [Attributes]?[Hidden]? <> true),
				    #"Invocar Função Personalizada1" = Table.AddColumn(#"Arquivos Ocultos Filtrados1", "Transformar Arquivo (51)", each #"Transformar Arquivo (51)"([Content])),
				    #"Colunas Renomeadas1" = Table.RenameColumns(#"Invocar Função Personalizada1", {"Name", "Nome da Origem"}),
				    #"Outras Colunas Removidas1" = Table.SelectColumns(#"Colunas Renomeadas1", {"Nome da Origem", "Transformar Arquivo (51)"}),
				    #"Coluna de Tabela Expandida1" = Table.ExpandTableColumn(#"Outras Colunas Removidas1", "Transformar Arquivo (51)", Table.ColumnNames(#"Transformar Arquivo (51)"(#"Arquivo de Amostra (51)"))),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Coluna de Tabela Expandida1",{{"Nome da Origem", type text}, {"data", type date}, {"userid", type text}, {"deposito", Int64.Type}, {"contas_depositantes", Int64.Type}, {"contas_novas", Int64.Type}, {"contas_ftd", Int64.Type}, {"utm_source_cadastro", type text}, {"utm_medium_cadastro", type text}, {"utm_campaign_cadastro", type text}, {"utm_content_cadastro", type text}, {"utm_term_cadastro", type text}, {"utm_source_deposito", type text}, {"utm_medium_deposito", type text}, {"utm_campaign_deposito", type text}, {"utm_content_deposito", type text}, {"utm_term_deposito", type text}, {"tier_l30d", Int64.Type}, {"tier_high_lifetime", Int64.Type}, {"hora_atualizacao", type datetime}}),
				    #"Valor Substituído" = Table.ReplaceValue(#"Tipo Alterado","0","none",Replacer.ReplaceText,{"utm_source_deposito", "utm_medium_deposito", "utm_campaign_deposito", "utm_content_deposito", "utm_term_deposito"})
				in
				    #"Valor Substituído"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

