table bd_depositos_recorrentes
	lineageTag: 5881cea4-4177-4381-a7c5-1f1bef37e867

	column 'Nome da Origem'
		dataType: string
		lineageTag: f2696c3f-2a2e-4af4-bcdd-8991aa93490d
		summarizeBy: none
		sourceColumn: Nome da Origem

		annotation SummarizationSetBy = Automatic

	column userid
		dataType: string
		lineageTag: 441c0c94-0925-44ae-960e-577212479027
		summarizeBy: none
		sourceColumn: userid

		annotation SummarizationSetBy = Automatic

	column deposito_ordem
		dataType: int64
		formatString: 0
		lineageTag: fe1749dc-9f8c-4b63-b158-051fb74a4fca
		summarizeBy: sum
		sourceColumn: deposito_ordem

		annotation SummarizationSetBy = Automatic

	column date_brt
		dataType: dateTime
		formatString: General Date
		lineageTag: c235b794-795d-40ec-8c04-3b85df77b26d
		summarizeBy: none
		sourceColumn: date_brt

		variation Variation
			isDefault
			relationship: b56b2449-e847-4f87-af87-8e616613037d
			defaultHierarchy: LocalDateTable_915aadc1-f759-459c-a14b-8b80b9e80926.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column amount
		dataType: double
		lineageTag: cc606545-39c5-458a-9739-2d65d07776aa
		summarizeBy: sum
		sourceColumn: amount

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column utm_source
		dataType: string
		lineageTag: 57a1366f-f5b5-49d3-ae1d-6717dfaf9b95
		summarizeBy: none
		sourceColumn: utm_source

		annotation SummarizationSetBy = Automatic

	column utm_medium
		dataType: string
		lineageTag: 8172e03f-4d53-4189-b5d6-41e94a435b4d
		summarizeBy: none
		sourceColumn: utm_medium

		annotation SummarizationSetBy = Automatic

	column utm_campaign
		dataType: string
		lineageTag: f706b439-139f-4959-b765-e52124f592d5
		summarizeBy: none
		sourceColumn: utm_campaign

		annotation SummarizationSetBy = Automatic

	column utm_content
		dataType: string
		lineageTag: 2d5262c1-17ad-4615-a703-16ffa0432110
		summarizeBy: none
		sourceColumn: utm_content

		annotation SummarizationSetBy = Automatic

	column utm_term
		dataType: string
		lineageTag: 395ccf61-ba1e-49d4-8e70-0d3c09ec0256
		summarizeBy: none
		sourceColumn: utm_term

		annotation SummarizationSetBy = Automatic

	column status_ativo_90d
		dataType: string
		lineageTag: 49bab356-aefb-49df-9285-6bfb191b8f20
		summarizeBy: none
		sourceColumn: status_ativo_90d

		annotation SummarizationSetBy = Automatic

	column media_l30d
		dataType: string
		lineageTag: bfde998b-b3a2-4543-bcae-93f7c3ee3c7d
		summarizeBy: none
		sourceColumn: media_l30d

		annotation SummarizationSetBy = Automatic

	column tier_l30d
		dataType: string
		lineageTag: a711a7bd-9894-4965-9fe8-0401cfeed23c
		summarizeBy: none
		sourceColumn: tier_l30d

		annotation SummarizationSetBy = Automatic

	column tier_high_lifetime
		dataType: string
		lineageTag: ac5e6b1a-c3bb-4641-84e5-157b11fddb4c
		summarizeBy: none
		sourceColumn: tier_high_lifetime

		annotation SummarizationSetBy = Automatic

	column media_high_lifetime
		dataType: string
		lineageTag: 70f0a7ee-5f17-4c48-8857-750d4b1c6117
		summarizeBy: none
		sourceColumn: media_high_lifetime

		annotation SummarizationSetBy = Automatic

	column Hora_Deposito_Formatada = FORMAT(HOUR('bd_depositos_recorrentes'[date_brt]), "00") & ":00"
		lineageTag: 378a8e8d-600e-4f7e-b448-1e077a1a59f3
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Dia_Semana_Num = WEEKDAY ( [date_brt], 2 )
		formatString: 0
		lineageTag: eb4c9804-482d-4ee8-b27a-7ee3455cb075
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column dia_da_semana =
			
			SWITCH (
			    [Dia_Semana_Num],
			    1, "Segunda",
			    2, "Terça",
			    3, "Quarta",
			    4, "Quinta",
			    5, "Sexta",
			    6, "Sábado",
			    7, "Domingo"
			)
		lineageTag: 5bed7cc9-5157-427d-9c0f-aa46152a62ae
		summarizeBy: none
		sortByColumn: Dia_Semana_Num

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column ano_semana = ```
			
			VAR numSemana = WEEKNUM ( [date_brt], 2 )                
			RETURN
			YEAR ( [date_brt] ) & "-" & FORMAT ( numSemana, "00" )
			
			```
		lineageTag: fb404e72-5fb7-443f-97cc-59bf92b09740
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column order_bloco_deposito = ```
			
			VAR h = HOUR (bd_depositos_recorrentes[date_brt])
			RETURN
			    SWITCH (
			        TRUE(),
			        h < 6,          1,
			        h < 12,         2,
			        h < 18,         3,
			                        4
			    )
			
			```
		formatString: 0
		lineageTag: d25b2fbf-e13a-4473-b334-ce5e64ffe70b
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Bloco_Horario_Deposito = ```
			
			VAR h = HOUR (bd_depositos_recorrentes[date_brt])
			RETURN
			    SWITCH (
			        TRUE(),
			        h < 6,          "Madrugada (00h-06h)",
			        h < 12,         "Manhã (06h-12h)",
			        h < 18,         "Tarde (12h-18h)",
			                        "Noite (18h-23h)"
			    )
			
			```
		lineageTag: 35438d07-4dd7-442a-821d-8368cad02034
		summarizeBy: none
		sortByColumn: order_bloco_deposito

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column semana_ano = WEEKNUM(bd_depositos_recorrentes[date_brt], 2)
		formatString: 0
		lineageTag: 53938627-79cc-47ca-9490-c310680f86a0
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column data_replica = bd_depositos_recorrentes[date_brt]
		formatString: Long Date
		lineageTag: f68553bc-1398-4300-9cd9-23c6ef5fb551
		summarizeBy: none

		variation Variation
			isDefault
			relationship: fefda7ac-48ff-4f15-b470-3d9861988cfb
			defaultHierarchy: LocalDateTable_d3b396df-2ddb-4577-8893-2287565686fb.'Hierarquia de datas'

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column LinkUserID = "https://admin-ai.kingpanda.com/users?userid=" & [userid]
		lineageTag: a451639c-e360-4f68-9a4c-8586a1030ba2
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition bd_depositos_recorrentes = m
		mode: import
		source =
				let
				    Fonte = AzureStorage.DataLake("https://kplakehouse.dfs.core.windows.net/gold/depositos_recorrentes"),
				    #"Linhas Filtradas" = Table.SelectRows(Fonte, each ([Extension] = ".parquet")),
				    #"Arquivos Ocultos Filtrados1" = Table.SelectRows(#"Linhas Filtradas", each [Attributes]?[Hidden]? <> true),
				    #"Invocar Função Personalizada1" = Table.AddColumn(#"Arquivos Ocultos Filtrados1", "Transformar Arquivo (10)", each #"Transformar Arquivo (10)"([Content])),
				    #"Colunas Renomeadas1" = Table.RenameColumns(#"Invocar Função Personalizada1", {"Name", "Nome da Origem"}),
				    #"Outras Colunas Removidas1" = Table.SelectColumns(#"Colunas Renomeadas1", {"Nome da Origem", "Transformar Arquivo (10)"}),
				    #"Coluna de Tabela Expandida1" = Table.ExpandTableColumn(#"Outras Colunas Removidas1", "Transformar Arquivo (10)", Table.ColumnNames(#"Transformar Arquivo (10)"(#"Arquivo de Amostra (10)"))),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Coluna de Tabela Expandida1",{{"Nome da Origem", type text}, {"userid", type text}, {"deposito_ordem", Int64.Type}, {"date_brt", type datetime}, {"amount", type number}, {"utm_source", type text}, {"utm_medium", type text}, {"utm_campaign", type text}, {"utm_content", type text}, {"utm_term", type text}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

