table bd_depositos_sankey
	lineageTag: fd272be7-5fc6-4c61-802e-4119fb9e0e29

	column 'Nome da Origem'
		dataType: string
		lineageTag: 8e1bb99a-3a15-4341-b414-f2520c3785f2
		summarizeBy: none
		sourceColumn: Nome da Origem

		annotation SummarizationSetBy = Automatic

	column userid
		dataType: string
		lineageTag: 340ff0fd-608e-4987-80c0-8bf17ce9b92e
		summarizeBy: none
		sourceColumn: userid

		annotation SummarizationSetBy = Automatic

	column utm_source_cadastro
		dataType: string
		lineageTag: 2e68c3b6-ba3c-4c87-8d04-9156cb7edd5a
		summarizeBy: none
		sourceColumn: utm_source_cadastro

		annotation SummarizationSetBy = Automatic

	column utm_medium_cadastro
		dataType: string
		lineageTag: d368a790-6941-4585-83f7-7603f9f026f2
		summarizeBy: none
		sourceColumn: utm_medium_cadastro

		annotation SummarizationSetBy = Automatic

	column utm_campaign_cadastro
		dataType: string
		lineageTag: c9d5d09f-18ae-4fc4-88ea-02ba22cb970b
		summarizeBy: none
		sourceColumn: utm_campaign_cadastro

		annotation SummarizationSetBy = Automatic

	column utm_content_cadastro
		dataType: string
		lineageTag: 7e422b22-f3bc-4991-b157-d1c57d4e2fe5
		summarizeBy: none
		sourceColumn: utm_content_cadastro

		annotation SummarizationSetBy = Automatic

	column utm_term_cadastro
		dataType: string
		lineageTag: 65a3fe9b-f6c2-4977-8fca-6913fbaf82b8
		summarizeBy: none
		sourceColumn: utm_term_cadastro

		annotation SummarizationSetBy = Automatic

	column data_cadastro
		dataType: dateTime
		formatString: General Date
		lineageTag: 8615d306-dda8-480a-b9fc-d0c288f48a96
		summarizeBy: none
		sourceColumn: data_cadastro

		variation Variation
			isDefault
			relationship: 6a18a028-a804-47b8-a034-0e0a08bb9573
			defaultHierarchy: LocalDateTable_187f00be-da14-4a3a-89c8-142d2ed3a42e.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column data_ftd_dim_usuarios
		dataType: dateTime
		formatString: General Date
		lineageTag: c3e6382b-7cf6-497e-894d-99be0132edd2
		summarizeBy: none
		sourceColumn: data_ftd_dim_usuarios

		variation Variation
			isDefault
			relationship: 5da146c8-a82d-4a61-8ca4-62aecb759c25
			defaultHierarchy: LocalDateTable_753aa433-c547-45b4-863d-23ba6effcc08.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column utm_source_ftd
		dataType: string
		lineageTag: 4a90c3a3-db6b-4924-9010-88b4115598da
		summarizeBy: none
		sourceColumn: utm_source_ftd

		annotation SummarizationSetBy = Automatic

	column utm_medium_ftd
		dataType: string
		lineageTag: c8c86603-1dfd-46cb-9ca8-97910f1744ec
		summarizeBy: none
		sourceColumn: utm_medium_ftd

		annotation SummarizationSetBy = Automatic

	column utm_campaign_ftd
		dataType: string
		lineageTag: c84c1327-7163-44ec-942c-279060c2ad97
		summarizeBy: none
		sourceColumn: utm_campaign_ftd

		annotation SummarizationSetBy = Automatic

	column utm_content_ftd
		dataType: string
		lineageTag: eca51b6c-2fa3-4f31-b187-f13b1c2a76f8
		summarizeBy: none
		sourceColumn: utm_content_ftd

		annotation SummarizationSetBy = Automatic

	column utm_term_ftd
		dataType: string
		lineageTag: 4afa7cba-84e0-4036-a730-1cc978cc4232
		summarizeBy: none
		sourceColumn: utm_term_ftd

		annotation SummarizationSetBy = Automatic

	column data_ftd
		dataType: dateTime
		formatString: Long Date
		lineageTag: e0e2b7b1-e630-420c-8023-1690ec959a8c
		summarizeBy: none
		sourceColumn: data_ftd

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column valor_ftd
		dataType: double
		lineageTag: 4bdecb9d-6e2c-4177-8978-5e7552a6b58a
		summarizeBy: sum
		sourceColumn: valor_ftd

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column utm_source_2dep
		dataType: string
		lineageTag: 29a1e1b5-5c04-4e15-b4f0-c3fcb938e96d
		summarizeBy: none
		sourceColumn: utm_source_2dep

		annotation SummarizationSetBy = Automatic

	column utm_medium_2dep
		dataType: string
		lineageTag: d7f69492-afd2-4abd-aa42-52305c256388
		summarizeBy: none
		sourceColumn: utm_medium_2dep

		annotation SummarizationSetBy = Automatic

	column utm_campaign_2dep
		dataType: string
		lineageTag: 4181d013-5a16-431f-b9ce-7364627a9c30
		summarizeBy: none
		sourceColumn: utm_campaign_2dep

		annotation SummarizationSetBy = Automatic

	column utm_content_2dep
		dataType: string
		lineageTag: bf233d38-2bcc-4e2c-bc88-341bd80a6ca0
		summarizeBy: none
		sourceColumn: utm_content_2dep

		annotation SummarizationSetBy = Automatic

	column utm_term_2dep
		dataType: string
		lineageTag: 5eaaa5c1-bfcd-4729-80eb-8a34c9e03ad7
		summarizeBy: none
		sourceColumn: utm_term_2dep

		annotation SummarizationSetBy = Automatic

	column data_2dep
		dataType: dateTime
		formatString: General Date
		lineageTag: 4eea9465-fba9-4163-92af-926d78496a1a
		summarizeBy: none
		sourceColumn: data_2dep

		variation Variation
			isDefault
			relationship: 6dedad28-c2c1-4782-b313-9a9d4bc86caa
			defaultHierarchy: LocalDateTable_050792db-36c4-4454-9518-d595bccbaa4b.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column valor_2dep
		dataType: double
		lineageTag: 913b3234-2a68-4ed2-936c-11f0736ec6e6
		summarizeBy: sum
		sourceColumn: valor_2dep

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column utm_source_3dep
		dataType: string
		lineageTag: e927d759-c45f-4579-b3a6-a94cd67f94af
		summarizeBy: none
		sourceColumn: utm_source_3dep

		annotation SummarizationSetBy = Automatic

	column utm_medium_3dep
		dataType: string
		lineageTag: 6bd517a2-a44a-4d43-be69-3f90ebd631e9
		summarizeBy: none
		sourceColumn: utm_medium_3dep

		annotation SummarizationSetBy = Automatic

	column utm_campaign_3dep
		dataType: string
		lineageTag: 10d9e573-b09f-48a8-a31c-5fdc0fbcd796
		summarizeBy: none
		sourceColumn: utm_campaign_3dep

		annotation SummarizationSetBy = Automatic

	column utm_content_3dep
		dataType: string
		lineageTag: c04c69ad-2c31-4f2a-b0cb-1da72d22a91a
		summarizeBy: none
		sourceColumn: utm_content_3dep

		annotation SummarizationSetBy = Automatic

	column utm_term_3dep
		dataType: string
		lineageTag: e6c63de2-3b75-4769-ad9a-4d86f2450936
		summarizeBy: none
		sourceColumn: utm_term_3dep

		annotation SummarizationSetBy = Automatic

	column data_3dep
		dataType: dateTime
		formatString: General Date
		lineageTag: b9c5bea4-e1c8-49cd-a56c-9c08c591b215
		summarizeBy: none
		sourceColumn: data_3dep

		variation Variation
			isDefault
			relationship: 463f5a13-e141-4aa9-8fef-e9e6e5ffebb4
			defaultHierarchy: LocalDateTable_4154666d-b2ef-461a-a86b-a4ecd5b5d50c.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column valor_3dep
		dataType: int64
		formatString: 0
		lineageTag: 09cdf8c2-7839-4f4b-b164-9aa8d5b7f0a9
		summarizeBy: sum
		sourceColumn: valor_3dep

		annotation SummarizationSetBy = Automatic

	column hora_atualizacao
		dataType: dateTime
		formatString: General Date
		lineageTag: 104d5847-4c12-4e14-b6b2-9dbd9d1572f9
		summarizeBy: none
		sourceColumn: hora_atualizacao

		variation Variation
			isDefault
			relationship: 220ba3bd-967c-4235-a016-ed145cbd60ea
			defaultHierarchy: LocalDateTable_d17f0900-c2cb-455d-9f29-a07661ff711e.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column migrado
		dataType: int64
		formatString: 0
		lineageTag: b261ca27-272b-4565-bc5e-e80315bfc605
		summarizeBy: sum
		sourceColumn: migrado

		annotation SummarizationSetBy = Automatic

	column tier_l30d_ftd
		dataType: string
		lineageTag: 7dd924b0-6011-41bb-8349-24fceb634e21
		summarizeBy: none
		sourceColumn: tier_l30d_ftd

		annotation SummarizationSetBy = Automatic

	column tier_high_lifetime_ftd
		dataType: string
		lineageTag: bff61eed-0ad8-45ec-97fd-a0eed67c3776
		summarizeBy: none
		sourceColumn: tier_high_lifetime_ftd

		annotation SummarizationSetBy = Automatic

	column tier_l30d_2dep
		dataType: string
		lineageTag: bb542a37-7013-43b5-8476-63e929e2b5c4
		summarizeBy: none
		sourceColumn: tier_l30d_2dep

		annotation SummarizationSetBy = Automatic

	column tier_high_lifetime_2dep
		dataType: string
		lineageTag: f65caaaf-8158-425e-af92-0e135fbf5d20
		summarizeBy: none
		sourceColumn: tier_high_lifetime_2dep

		annotation SummarizationSetBy = Automatic

	column tier_l30d_3dep
		dataType: string
		lineageTag: fb56eba4-cb60-4cae-b723-2b68f2ce1f73
		summarizeBy: none
		sourceColumn: tier_l30d_3dep

		annotation SummarizationSetBy = Automatic

	column tier_high_lifetime_3dep
		dataType: string
		lineageTag: 92cd5002-55c8-46ae-b58b-ff6ed5ac151c
		summarizeBy: none
		sourceColumn: tier_high_lifetime_3dep

		annotation SummarizationSetBy = Automatic

	column data_ftd_replica = bd_depositos_sankey[data_ftd]
		formatString: General Date
		lineageTag: 8e502294-7bd0-490a-a192-20ae2d9a24c6
		summarizeBy: none

		variation Variation
			isDefault
			relationship: 3dbf639f-2f72-4a43-a22a-35afd0ed669e
			defaultHierarchy: LocalDateTable_35ba3530-6104-4f74-ac5a-fa70c37b8446.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	partition bd_depositos_sankey = m
		mode: import
		source =
				let
				    Fonte = AzureStorage.DataLake("https://kplakehouse.dfs.core.windows.net/gold/depositos_sankey"),
				    #"Linhas Filtradas" = Table.SelectRows(Fonte, each ([Extension] = ".parquet")),
				    #"Arquivos Ocultos Filtrados1" = Table.SelectRows(#"Linhas Filtradas", each [Attributes]?[Hidden]? <> true),
				    #"Invocar Função Personalizada1" = Table.AddColumn(#"Arquivos Ocultos Filtrados1", "Transformar Arquivo (49)", each #"Transformar Arquivo (49)"([Content])),
				    #"Colunas Renomeadas1" = Table.RenameColumns(#"Invocar Função Personalizada1", {"Name", "Nome da Origem"}),
				    #"Outras Colunas Removidas1" = Table.SelectColumns(#"Colunas Renomeadas1", {"Nome da Origem", "Transformar Arquivo (49)"}),
				    #"Coluna de Tabela Expandida1" = Table.ExpandTableColumn(#"Outras Colunas Removidas1", "Transformar Arquivo (49)", Table.ColumnNames(#"Transformar Arquivo (49)"(#"Arquivo de Amostra (49)"))),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Coluna de Tabela Expandida1",{{"Nome da Origem", type text}, {"userid", type text}, {"utm_source_cadastro", type text}, {"utm_medium_cadastro", type text}, {"utm_campaign_cadastro", type text}, {"utm_content_cadastro", type text}, {"utm_term_cadastro", type text}, {"data_cadastro", type datetime}, {"data_ftd_dim_usuarios", type datetime}, {"utm_source_ftd", type text}, {"utm_medium_ftd", type text}, {"utm_campaign_ftd", type text}, {"utm_content_ftd", type text}, {"utm_term_ftd", type any}, {"data_ftd", type date}, {"valor_ftd", type number}, {"utm_source_2dep", type text}, {"utm_medium_2dep", type text}, {"utm_campaign_2dep", type text}, {"utm_content_2dep", type text}, {"utm_term_2dep", type any}, {"data_2dep", type datetime}, {"valor_2dep", type number}, {"utm_source_3dep", type text}, {"utm_medium_3dep", type text}, {"utm_campaign_3dep", type any}, {"utm_content_3dep", type text}, {"utm_term_3dep", type any}, {"data_3dep", type datetime}, {"valor_3dep", Int64.Type}, {"hora_atualizacao", type datetime}, {"migrado", Int64.Type}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

