table bd_growth
	lineageTag: 84a3ced9-8a01-4bb5-a199-7ca339b80dfd

	measure data_atual = NOW()
		formatString: General Date
		lineageTag: 24a979a0-d02c-4254-8bbb-d7fb0004c42f

	column userid
		dataType: string
		lineageTag: ce13df72-166e-4a8e-9873-a284c71226ff
		summarizeBy: none
		sourceColumn: userid

		annotation SummarizationSetBy = Automatic

	column created_brt
		dataType: dateTime
		formatString: General Date
		lineageTag: 6823fa0c-456d-402a-8ae6-66f6f9cd8029
		summarizeBy: none
		sourceColumn: created_brt

		variation Variation
			isDefault
			relationship: 23198888-d037-4a5a-92ca-0a9b2948d912
			defaultHierarchy: LocalDateTable_342ee2b1-d45e-4e20-8c1f-bf162e09ec26.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column utm_campaign
		dataType: string
		lineageTag: f548ea5e-7eba-4f9a-9cb8-df5f64dd58ff
		summarizeBy: none
		sourceColumn: utm_campaign

		annotation SummarizationSetBy = Automatic

	column utm_source
		dataType: string
		lineageTag: 75047173-3175-461b-b236-c67c048893b9
		summarizeBy: none
		sourceColumn: utm_source

		annotation SummarizationSetBy = Automatic

	column utm_medium
		dataType: string
		lineageTag: 621c1cb5-59f3-4803-ab7d-73ffd5112fbc
		summarizeBy: none
		sourceColumn: utm_medium

		annotation SummarizationSetBy = Automatic

	column utm_content
		dataType: string
		lineageTag: 0b5fc750-ba64-4350-8b9a-fe60999c3f18
		summarizeBy: none
		sourceColumn: utm_content

		annotation SummarizationSetBy = Automatic

	column utm_term
		dataType: string
		lineageTag: 664cfe36-1a81-4f3f-bf10-e6a04a478190
		summarizeBy: none
		sourceColumn: utm_term

		annotation SummarizationSetBy = Automatic

	column data_ftd_brt
		dataType: dateTime
		formatString: Long Date
		lineageTag: 94e2fab9-efc4-4b02-8784-240cf1664e08
		summarizeBy: none
		sourceColumn: data_ftd_brt

		variation Variation
			isDefault
			relationship: 2ee15084-6b36-4dc1-98cf-a7aa442b63e1
			defaultHierarchy: LocalDateTable_5f3e6ae8-9569-4034-bf95-3c0daaf9d127.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column deposito_24h
		dataType: double
		lineageTag: 1613fb7c-945e-45f3-afb0-f1105c83a7ad
		summarizeBy: sum
		sourceColumn: deposito_24h

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column aposta_cassino_24h
		dataType: double
		lineageTag: ed5ef96c-6153-49d0-9ab0-e42c80e324e6
		summarizeBy: sum
		sourceColumn: aposta_cassino_24h

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column aposta_sportsbook_24h
		dataType: double
		lineageTag: 57fe06f9-bd9a-42de-add8-b3e6bed17f02
		summarizeBy: sum
		sourceColumn: aposta_sportsbook_24h

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column aposta_lb_24h
		dataType: double
		formatString: 0
		lineageTag: 15aa783f-bf9d-4dd0-87c6-bb739f4f90cb
		summarizeBy: sum
		sourceColumn: aposta_lb_24h

		annotation SummarizationSetBy = Automatic

	column created_brt_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 5250def0-280e-473b-b8a2-f118e7de5cc7
		summarizeBy: none
		sourceColumn: created_brt_date

		variation Variation
			isDefault
			relationship: e8c9569a-c431-48c0-ad3d-69e566ccb961
			defaultHierarchy: LocalDateTable_b1274b59-31c8-4a84-a0dd-4b5d3c301b05.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column data_ftd_brt_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: ab4dd320-f78e-42ed-8f9d-fc4e3db329dc
		summarizeBy: none
		sourceColumn: data_ftd_brt_date

		variation Variation
			isDefault
			relationship: 1f774dd4-1e9e-4082-8f81-e9a2a2371704
			defaultHierarchy: LocalDateTable_12c0e005-8a9c-472f-b411-c630e6ad92a3.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column hora_atualizacao
		dataType: dateTime
		formatString: General Date
		lineageTag: c41815fd-aac0-491e-aff4-fdfbfe73575b
		summarizeBy: none
		sourceColumn: hora_atualizacao

		variation Variation
			isDefault
			relationship: 455fc16c-919b-492f-8cc9-a1fbbf0b0a49
			defaultHierarchy: LocalDateTable_79442d9c-94dc-4d2f-92a8-14efa9b41da9.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column data
		dataType: dateTime
		formatString: Long Date
		lineageTag: 01a70409-3ff7-4fe4-a6ff-ec9468b47744
		summarizeBy: none
		sourceColumn: data

		variation Variation
			isDefault
			relationship: 622994e1-acf1-4844-99c6-9b28144fc6f2
			defaultHierarchy: LocalDateTable_7cd1972b-2f23-4d02-bd0d-9d8908a7d5bd.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column deposito
		dataType: double
		lineageTag: 234f9e7a-4f2c-45c7-ab7c-dadef09a21b1
		summarizeBy: sum
		sourceColumn: deposito

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column aposta_cassino
		dataType: double
		lineageTag: f6b087ce-ab63-4b0d-aaa7-8494cb036f45
		summarizeBy: sum
		sourceColumn: aposta_cassino

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column aposta_sportsbook
		dataType: double
		lineageTag: fbcf3a2b-f1d5-4242-9903-13fd02ea3336
		summarizeBy: sum
		sourceColumn: aposta_sportsbook

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column aposta_lb
		dataType: double
		lineageTag: c597151e-03a4-4b5d-9ec6-980ff12a4ae2
		summarizeBy: sum
		sourceColumn: aposta_lb

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column premio_cassino
		dataType: double
		lineageTag: 48d02db2-f527-4470-85b7-09ae758764a5
		summarizeBy: sum
		sourceColumn: premio_cassino

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column premio_sportsbook
		dataType: double
		lineageTag: 0e0786e7-cc74-4791-85c4-38b1f5531887
		summarizeBy: sum
		sourceColumn: premio_sportsbook

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column premio_lb
		dataType: double
		lineageTag: 983c762c-f45e-4b2c-98b1-014299bc3c9f
		summarizeBy: sum
		sourceColumn: premio_lb

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ggr_cassino
		dataType: double
		lineageTag: 9ce677a1-e65f-410e-bf63-7d303d451e29
		summarizeBy: sum
		sourceColumn: ggr_cassino

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ggr_sportsbook
		dataType: double
		lineageTag: e82a151a-8d8b-4bca-890f-07e1a7f04e79
		summarizeBy: sum
		sourceColumn: ggr_sportsbook

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ggr_lb
		dataType: double
		lineageTag: ce9f5d23-6bd9-4b5a-84fb-dfb086cbe060
		summarizeBy: sum
		sourceColumn: ggr_lb

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ngr
		dataType: double
		lineageTag: ab0032ee-ccfc-4634-8046-6cef20f93c15
		summarizeBy: sum
		sourceColumn: ngr

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SemanaAno = WEEKNUM(bd_growth[data], 2)
		formatString: 0
		lineageTag: 3c5aad91-e660-4a14-8da0-7a781d46b071
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column status_ativo_90d
		dataType: int64
		formatString: 0
		lineageTag: 44b1a7af-ce6d-464e-879e-4df4cb6e1fc8
		summarizeBy: sum
		sourceColumn: status_ativo_90d

		annotation SummarizationSetBy = Automatic

	column media_l30d
		dataType: double
		lineageTag: 60f55ba0-a706-4bfa-b021-6e42113051fd
		summarizeBy: sum
		sourceColumn: media_l30d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column tier_l30d
		dataType: int64
		lineageTag: 8469530e-8d18-4c52-961e-448889cf1545
		summarizeBy: sum
		sourceColumn: tier_l30d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column tier_high_lifetime
		dataType: int64
		lineageTag: 572a677a-19b3-4a21-90b2-77484e74e3b4
		summarizeBy: sum
		sourceColumn: tier_high_lifetime

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column media_high_lifetime
		dataType: double
		lineageTag: 807c8d7a-66ce-40d2-949a-31942e34796b
		summarizeBy: sum
		sourceColumn: media_high_lifetime

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition bd_growth = m
		mode: import
		source =
				let
				    // 1. Conecta diretamente na subpasta resumo_executivo
				    Source = AzureStorage.DataLake(
				        "https://kplakehouse.dfs.core.windows.net/gold/growth",
				        [HierarchicalNavigation = true]
				    ),
				
				    // 2. Filtra apenas arquivos .parquet
				    ParquetFiles = Table.SelectRows(
				        Source,
				        each [Extension] = ".parquet"
				    ),
				
				    // 3. Pega o primeiro arquivo da lista
				    FirstFile = ParquetFiles{0}[Content],
				
				    // 4. Carrega o Parquet como uma tabela
				    Data = Parquet.Document(FirstFile),
				    #"Data Inserida" = Table.AddColumn(Data, "Data", each DateTime.Date([created_brt]), type date),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Data Inserida",{{"Data", "created_brt_date"}}),
				    #"Data Inserida1" = Table.AddColumn(#"Colunas Renomeadas", "Data", each DateTime.Date([data_ftd_brt]), type date),
				    #"Colunas Renomeadas1" = Table.RenameColumns(#"Data Inserida1",{{"Data", "data_ftd_brt_date"}}),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Colunas Renomeadas1",{{"tier_l30d", Int64.Type}, {"tier_high_lifetime", Int64.Type}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

