table bd_resumo_executivo_user
	lineageTag: 7da8d2f5-13dc-4c56-8035-39c46897be69

	measure usuario_freespin_para_filtro =
			
			CALCULATE(
			    DISTINCTCOUNT(bd_resumo_executivo_user[userid]),
			    bd_resumo_executivo_user[qtd_usuarios_com_premio_freespins] > 0
			)
		formatString: 0
		lineageTag: fb67b70d-f455-4ab9-98a7-f6698e31775a

	column 'Nome da Origem'
		dataType: string
		lineageTag: 92beac73-a399-476a-8407-52296d0166b1
		summarizeBy: none
		sourceColumn: Nome da Origem

		annotation SummarizationSetBy = Automatic

	column data
		dataType: dateTime
		formatString: Long Date
		lineageTag: 57d7a7dc-d7c3-482b-b4a2-4c3c0c2315db
		summarizeBy: none
		sourceColumn: data

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column userid
		dataType: string
		lineageTag: 17966d29-e1d7-45e0-90c3-40cf6ad71bb8
		summarizeBy: none
		sourceColumn: userid

		annotation SummarizationSetBy = Automatic

	column usuarios_migrados
		dataType: int64
		formatString: 0
		lineageTag: fd3295f2-fc03-46c4-a5b3-ec07ffa6d7da
		summarizeBy: sum
		sourceColumn: usuarios_migrados

		annotation SummarizationSetBy = Automatic

	column contas_novas
		dataType: int64
		formatString: 0
		lineageTag: 7096f991-5127-4b69-bfe4-bdb5b9128c7d
		summarizeBy: sum
		sourceColumn: contas_novas

		annotation SummarizationSetBy = Automatic

	column contas_depositantes
		dataType: int64
		formatString: 0
		lineageTag: a86456ae-9d12-4c61-8674-3dd5e40ab2fc
		summarizeBy: sum
		sourceColumn: contas_depositantes

		annotation SummarizationSetBy = Automatic

	column clientes_ativos
		dataType: int64
		formatString: 0
		lineageTag: 906da74b-a004-4770-8ee4-8f4d9bd8dd22
		summarizeBy: sum
		sourceColumn: clientes_ativos

		annotation SummarizationSetBy = Automatic

	column contas_ftd
		dataType: int64
		formatString: 0
		lineageTag: 7678e1db-3834-46c6-8cd2-e36ddb009beb
		summarizeBy: sum
		sourceColumn: contas_ftd

		annotation SummarizationSetBy = Automatic

	column deposito
		dataType: double
		lineageTag: e29e5b12-fa29-4e39-b8c7-49e7768899d3
		summarizeBy: sum
		sourceColumn: deposito

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column saques
		dataType: double
		lineageTag: 8fa832b1-b280-42b0-8baf-bda53add63e2
		summarizeBy: sum
		sourceColumn: saques

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column total_vip_proprio
		dataType: double
		formatString: 0
		lineageTag: d40144fb-ffa7-4881-8e9b-c84239c57ce6
		summarizeBy: sum
		sourceColumn: total_vip_proprio

		annotation SummarizationSetBy = Automatic

	column total_vip_referral
		dataType: double
		formatString: 0
		lineageTag: b42149a2-752c-4c16-b4c0-509ce3f3280e
		summarizeBy: sum
		sourceColumn: total_vip_referral

		annotation SummarizationSetBy = Automatic

	column total_vip_programa
		dataType: double
		formatString: 0
		lineageTag: 0441e913-4c09-439d-af95-9f6211aba4ad
		summarizeBy: sum
		sourceColumn: total_vip_programa

		annotation SummarizationSetBy = Automatic

	column total_crazy_friday
		dataType: double
		lineageTag: 37a57dcc-7c79-49a4-9dc9-6174da4ed22e
		summarizeBy: sum
		sourceColumn: total_crazy_friday

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column saldo_conta
		dataType: double
		lineageTag: 83bf4a83-2ccf-4333-9996-29a3c0f3878e
		summarizeBy: sum
		sourceColumn: saldo_conta

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column migracao_saldo
		dataType: double
		formatString: 0
		lineageTag: c923944d-366a-4ff0-9a1b-717da3d5f7a9
		summarizeBy: sum
		sourceColumn: migracao_saldo

		annotation SummarizationSetBy = Automatic

	column ajuste_saldo_manual
		dataType: double
		formatString: 0
		lineageTag: d37914b5-1e07-41d8-bb0f-026360b3d886
		summarizeBy: sum
		sourceColumn: ajuste_saldo_manual

		annotation SummarizationSetBy = Automatic

	column aposta_cassino
		dataType: double
		lineageTag: 9cc70baa-b0fd-4068-b585-bfa64dddd922
		summarizeBy: sum
		sourceColumn: aposta_cassino

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column aposta_sportsbook
		dataType: double
		lineageTag: 28fa3bd8-0a6c-4859-bb99-44edb40ac949
		summarizeBy: sum
		sourceColumn: aposta_sportsbook

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column aposta_lb
		dataType: double
		formatString: 0
		lineageTag: aa528a26-d88b-4e40-b02c-a6de0b085fa5
		summarizeBy: sum
		sourceColumn: aposta_lb

		annotation SummarizationSetBy = Automatic

	column premio_cassino
		dataType: double
		lineageTag: 617a1e79-bee3-4082-9f84-8b7a917d867b
		summarizeBy: sum
		sourceColumn: premio_cassino

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column premio_sportsbook
		dataType: double
		lineageTag: 488a1c58-226f-4231-a464-7b8b75e8c110
		summarizeBy: sum
		sourceColumn: premio_sportsbook

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column premio_lb
		dataType: double
		lineageTag: 5b50516c-e03e-4d74-a82e-9689fa36c503
		summarizeBy: sum
		sourceColumn: premio_lb

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ggr_cassino
		dataType: double
		lineageTag: afd6f9fd-5c35-4b3f-9fcb-46e0ea68b84c
		summarizeBy: sum
		sourceColumn: ggr_cassino

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ggr_sportsbook
		dataType: double
		lineageTag: 7bdd6ae6-9f49-43d8-a828-34a9cb1e6b1c
		summarizeBy: sum
		sourceColumn: ggr_sportsbook

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ggr_lb
		dataType: double
		lineageTag: 1440a75a-0e0d-454e-b83a-b727dc3d8d67
		summarizeBy: sum
		sourceColumn: ggr_lb

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ngr
		dataType: double
		lineageTag: f68d6937-59a5-4580-aca5-14c0bdb691b3
		summarizeBy: sum
		sourceColumn: ngr

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column reward
		dataType: double
		lineageTag: 039df1b9-b026-4d9c-be81-3dc578a74252
		summarizeBy: sum
		sourceColumn: reward

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column premios_freespins
		dataType: double
		lineageTag: f06ee212-2680-4bba-a689-13804aeb4a84
		summarizeBy: sum
		sourceColumn: premios_freespins

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column qtd_usuarios_com_premio_freespins
		dataType: int64
		formatString: 0
		lineageTag: a2187b6c-ebbd-4311-904d-319e78554d6f
		summarizeBy: sum
		sourceColumn: qtd_usuarios_com_premio_freespins

		annotation SummarizationSetBy = Automatic

	column hora_atualizacao
		dataType: dateTime
		formatString: General Date
		lineageTag: fc4fad43-8033-4160-9981-4f58108dc82f
		summarizeBy: none
		sourceColumn: hora_atualizacao

		variation Variation
			isDefault
			relationship: d23ee12b-5fb9-4825-8008-fae1cb670e2f
			defaultHierarchy: LocalDateTable_b26a3cce-78a4-4637-84d6-e038085b7d6a.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column data_duplicada = bd_resumo_executivo_user[data]
		formatString: General Date
		lineageTag: 29bfd567-2dcd-4822-b09d-29b311c5094d
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column qtd_depositos
		dataType: int64
		formatString: 0
		lineageTag: f78c37d9-eda0-4219-a158-ac495466b3ae
		summarizeBy: sum
		sourceColumn: qtd_depositos

		annotation SummarizationSetBy = Automatic

	column LinkUserID = "https://admin-ai.kingpanda.com/users?userid=" & [userid]
		lineageTag: 07c74dd5-e2a9-4365-9704-a04d24d708fe
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column qtd_saques
		dataType: int64
		formatString: 0
		lineageTag: ca68dbc5-92e4-4c0c-8336-b00a98673580
		summarizeBy: sum
		sourceColumn: qtd_saques

		annotation SummarizationSetBy = Automatic

	column qtd_aposta_cassino
		dataType: int64
		formatString: 0
		lineageTag: 3b64c30f-237a-435d-91e4-21dcc33cdcc9
		summarizeBy: sum
		sourceColumn: qtd_aposta_cassino

		annotation SummarizationSetBy = Automatic

	column qtd_aposta_sportsbook
		dataType: int64
		formatString: 0
		lineageTag: 72cada0a-da4b-482a-b965-c2088801a402
		summarizeBy: sum
		sourceColumn: qtd_aposta_sportsbook

		annotation SummarizationSetBy = Automatic

	column qtd_aposta_lb
		dataType: int64
		formatString: 0
		lineageTag: f23a1226-b1b9-41a6-b802-b953245c2ece
		summarizeBy: sum
		sourceColumn: qtd_aposta_lb

		annotation SummarizationSetBy = Automatic

	column FTD_Date = ```
			
			CALCULATE (
			    MIN ( bd_resumo_executivo_user[data] ),
			    FILTER (
			        bd_resumo_executivo_user,
			        bd_resumo_executivo_user[userid]      = EARLIER ( bd_resumo_executivo_user[userid] )
			        && bd_resumo_executivo_user[contas_ftd] > 0      -- linha onde houve FTD
			    )
			)
			
			```
		formatString: General Date
		lineageTag: 406adfb2-0444-497f-9f4a-b3ef397cc1ce
		summarizeBy: none

		variation Variation
			isDefault
			relationship: 80f9f231-43c1-49a5-b98d-be9b3aed30be
			defaultHierarchy: LocalDateTable_ff6dc923-5201-4e80-8973-5884bb11d3e0.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column FTD_YearWeek = ```
			
			VAR numSemana = WEEKNUM ( [FTD_Date], 2 )                -- ISO, semana começa na 2ª-feira
			RETURN
			YEAR ( [FTD_Date] ) & "-" & FORMAT ( numSemana, "00" )
			
			```
		lineageTag: e8ece284-8a14-4fc5-9ad8-603d68a8d689
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column AnoSemana_FTD_Cohort = ```
			
			VAR MondayFTD =
			    [FTD_Date] - WEEKDAY ( [FTD_Date], 2 ) + 1   -- volta até a 2ª-feira do FTD
			VAR MondayData =
			    bd_resumo_executivo_user[data]
			        - WEEKDAY ( bd_resumo_executivo_user[data], 2 ) + 1
			RETURN
			    DATEDIFF ( MondayFTD, MondayData, WEEK )
			
			```
		formatString: 0
		lineageTag: 20eaa2f6-d607-4d40-8f63-957be5b0ddc7
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Ranking =
			
			RANKX(
			    FILTER(
			        bd_resumo_executivo_user,
			        SUM(bd_resumo_executivo_user[deposito]) &&
			        bd_resumo_executivo_user[userid] = EARLIER(bd_resumo_executivo_user[userid])
			    ),
			    bd_resumo_executivo_user[data],
			    ,
			    ASC,
			    DENSE
			)
		formatString: 0
		lineageTag: 944643eb-e31a-4a7e-80ed-475421fde3cc
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column ano_semana_user = WEEKNUM(bd_resumo_executivo_user[data], 2)
		formatString: 0
		lineageTag: a11fca8b-2e53-41c4-90fe-90a212189e0e
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column genero_formatado_user = ```
			
			VAR genero =
			    LOOKUPVALUE (
			        bd_users_dimensao_reduzida[genero],
			        bd_users_dimensao_reduzida[userid],
			        bd_resumo_executivo_user[userid]
			    )
			RETURN
			SWITCH(
			        genero,
			        "M", "Masculino",
			        "F", "Feminino",
			        "O", "Outros"
			    )
			
			```
		lineageTag: 7a48a447-2926-4d0b-a1a7-33344a697a30
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column faixa_idade_user = ```
			
			    LOOKUPVALUE (
			        bd_users_dimensao_reduzida[faixa_idade],
			        bd_users_dimensao_reduzida[userid],
			        bd_resumo_executivo_user[userid]
			    )
			```
		lineageTag: aa8b39c6-57bf-4f9b-b46f-6f27b22f1899
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column status_ativo_90d
		dataType: int64
		formatString: 0
		lineageTag: 4be46948-07d4-4e37-bd66-662be9c2cf3b
		summarizeBy: sum
		sourceColumn: status_ativo_90d

		annotation SummarizationSetBy = Automatic

	column media_l30d
		dataType: double
		lineageTag: f7fc68e3-5a4f-4ea3-8bfc-b85d3492b422
		summarizeBy: sum
		sourceColumn: media_l30d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column tier_l30d
		dataType: int64
		formatString: 0
		lineageTag: fff08b3d-3db7-4ad7-a712-48ae7765e9bb
		summarizeBy: sum
		sourceColumn: tier_l30d

		annotation SummarizationSetBy = Automatic

	column tier_high_lifetime
		dataType: int64
		formatString: 0
		lineageTag: 5e35dfa6-5ac1-4e9d-8eaf-f12e21958275
		summarizeBy: sum
		sourceColumn: tier_high_lifetime

		annotation SummarizationSetBy = Automatic

	column media_high_lifetime
		dataType: int64
		formatString: 0
		lineageTag: d72db228-1c1d-47e2-9940-b48a76df0453
		summarizeBy: sum
		sourceColumn: media_high_lifetime

		annotation SummarizationSetBy = Automatic

	column SemanaAnoNum = WEEKNUM(bd_resumo_executivo_user[data], 2)
		formatString: 0
		lineageTag: c1d9d0b5-c061-47f1-aa4c-f0bd161d5113
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column data_replica = bd_resumo_executivo_user[data]
		formatString: General Date
		lineageTag: 138b9dab-4d9c-4a3f-84ea-134470e8ef1d
		summarizeBy: none

		variation Variation
			isDefault
			relationship: 220dc4cf-3e4e-4363-a020-14d3ef62bf3e
			defaultHierarchy: LocalDateTable_9e55a2c4-5112-4a57-83e8-ab3ca2692cb5.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column FTD_YearMonth = ```
			
			VAR numMes = MONTH ( [FTD_Date] )        -- número do mês (1-12)
			RETURN
			    YEAR ( [FTD_Date] ) & "-" & FORMAT ( numMes, "00" )
			
			```
		lineageTag: d5693781-501a-4f66-93f6-43127b26a50f
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column AnoMes_FTD_Cohort = ```
			
			VAR FirstDayFTD =
			        DATE ( YEAR ( [FTD_Date] )
			             , MONTH ( [FTD_Date] )
			             , 1 )                                    -- 1º dia do mês do FTD
			VAR FirstDayData =
			        DATE ( YEAR ( bd_resumo_executivo_user[data] )
			             , MONTH ( bd_resumo_executivo_user[data] )
			             , 1 )                                    -- 1º dia do mês do Data
			RETURN
			    DATEDIFF ( FirstDayFTD            -- data inicial
			             , FirstDayData           -- data final
			             , MONTH )                -- unidade de diferença
			
			```
		formatString: 0
		lineageTag: 10ed6b72-557b-4a0e-bdf7-4174d874340a
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column filtro_mes = ```
			
			FORMAT ( [data], "MMMM" )
			
			```
		lineageTag: 09367cd4-bed7-410d-9064-41656bc319bc
		summarizeBy: none
		sortByColumn: filtro_mes_num

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column filtro_mes_num =
			
			MONTH(bd_resumo_executivo_user[data])
		formatString: 0
		lineageTag: 71b51ddd-d5de-43da-9eb9-86b2e8e89aa2
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Conta_nova_mes = ```
			
			VAR MesCriacao =
			    CALCULATE (
			        MIN ( bd_resumo_executivo_user[data_replica] ),
			        bd_resumo_executivo_user[contas_novas] = 1,
			        ALLEXCEPT ( bd_resumo_executivo_user, bd_resumo_executivo_user[userid] )
			    )
			RETURN
			IF (
			    YEAR ( bd_resumo_executivo_user[data_replica] ) = YEAR ( MesCriacao ) &&
			    MONTH ( bd_resumo_executivo_user[data_replica] ) = MONTH ( MesCriacao ),
			    1,
			    0
			)
			
			```
		formatString: 0
		lineageTag: a0d99cbc-4bbd-4086-9b95-540f7d221eb5
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Conta_nova_dia = ```
			
			VAR DataCriacao =
			    CALCULATE (
			        MIN ( bd_resumo_executivo_user[data_replica] ),
			        bd_resumo_executivo_user[contas_novas] = 1,
			        ALLEXCEPT ( bd_resumo_executivo_user, bd_resumo_executivo_user[userid] )
			    )
			RETURN
			IF (
			    bd_resumo_executivo_user[data_replica] = DataCriacao,
			    1,
			    0
			)
			
			```
		formatString: 0
		lineageTag: d213b7ae-1e53-4f08-987c-cff5158e12e2
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Conta_nova_mes_2 = ```
			
			VAR DataCriacaoUsuario =
			    /* ↳ pega a data real de cadastro do usuário                        */
			    /* Se houver relacionamento                                     */
			    RELATED ( bd_users_dimensao_reduzida[dt_criacao_brt] )
			    /* Sem relacionamento?  Descomente a linha abaixo e comente a RELATED:
			    LOOKUPVALUE (
			        bd_users_dimensao_reduzida[dt_criacao_brt],
			        bd_users_dimensao_reduzida[userid], bd_resumo_executivo_user[userid]
			    )
			    */
			
			VAR DataLinha = bd_resumo_executivo_user[data_replica]
			
			/* Alinhar ambas as datas ao 1º dia do mês */
			VAR InicioMesCriacao =
			    DATE ( YEAR ( DataCriacaoUsuario ),
			           MONTH ( DataCriacaoUsuario ), 1 )
			
			VAR InicioDataLinha =
			    DATE ( YEAR ( DataLinha ),
			           MONTH ( DataLinha ), 1 )
			
			/* Diferença em meses entre “mês de criação” e “mês da linha”        */
			VAR DiffMeses =
			    DATEDIFF (
			        InicioMesCriacao,
			        InicioDataLinha,
			        MONTH
			    )
			
			RETURN
			SWITCH (
			    TRUE(),
			    /* Mês do cadastro OU mês imediatamente posterior → 1            */
			    DiffMeses IN { 0, 1 }, 1,
			
			    /* Dois ou mais meses depois do cadastro → 0 (legado)            */
			    DiffMeses >= 2, 0,
			
			    /* Mês anterior ao cadastro (ou dados inválidos) → BLANK()       */
			    BLANK()
			)
			
			
			```
		lineageTag: f6c4d269-88dd-4b4e-bb70-e1dce36b10c5
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Status_Deposito = ```
			
			IF (
			    [contas_depositantes] = 1,
			    "Com Depósito",
			    "Sem Depósito"
			)
			
			```
		lineageTag: 74d3a05d-1282-4846-bfdf-7e8ebc2f9af8
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Conta_nova_mes_3 = ```
			
			VAR DataCriacaoUsuario =
			    RELATED ( bd_users_dimensao_reduzida[dt_criacao_brt] )
			    /*
			    LOOKUPVALUE (
			        bd_users_dimensao_reduzida[dt_criacao_brt],
			        bd_users_dimensao_reduzida[userid], bd_resumo_executivo_user[userid]
			    )
			    */
			
			VAR DataLinha = bd_resumo_executivo_user[data_replica]
			
			VAR InicioMesCriacao =
			    DATE ( YEAR ( DataCriacaoUsuario ), MONTH ( DataCriacaoUsuario ), 1 )
			
			VAR InicioDataLinha =
			    DATE ( YEAR ( DataLinha ), MONTH ( DataLinha ), 1 )
			
			VAR DiffMeses =
			    DATEDIFF (
			        InicioMesCriacao,
			        InicioDataLinha,
			        MONTH
			    )
			
			RETURN
			SWITCH (
			    TRUE(),
			    /* Mês do cadastro, +1 mês e +2 meses → 1 */
			    DiffMeses IN { 0, 1, 2 }, 1,
			
			    /* Três ou mais meses depois do cadastro → 0 */
			    DiffMeses >= 3, 0,
			
			    /* Mês anterior ao cadastro (ou dados inválidos) → BLANK() */
			    BLANK()
			)
			
			```
		formatString: 0
		lineageTag: f9ff38f5-7acd-43a9-9b17-f787e7fe8b53
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Conta_nova_mes_4 = ```
			
			VAR DataCriacaoUsuario =
			    RELATED ( bd_users_dimensao_reduzida[dt_criacao_brt] )
			    /*
			    LOOKUPVALUE (
			        bd_users_dimensao_reduzida[dt_criacao_brt],
			        bd_users_dimensao_reduzida[userid], bd_resumo_executivo_user[userid]
			    )
			    */
			
			VAR DataLinha = bd_resumo_executivo_user[data_replica]
			
			VAR InicioMesCriacao =
			    DATE ( YEAR ( DataCriacaoUsuario ), MONTH ( DataCriacaoUsuario ), 1 )
			
			VAR InicioDataLinha =
			    DATE ( YEAR ( DataLinha ), MONTH ( DataLinha ), 1 )
			
			VAR DiffMeses =
			    DATEDIFF (
			        InicioMesCriacao,
			        InicioDataLinha,
			        MONTH
			    )
			
			RETURN
			SWITCH (
			    TRUE(),
			    /* Mês do cadastro, +1 mês e +2 meses → 1 */
			    DiffMeses IN { 0, 1, 2, 3 }, 1,
			
			    /* Três ou mais meses depois do cadastro → 0 */
			    DiffMeses >= 4, 0,
			
			    /* Mês anterior ao cadastro (ou dados inválidos) → BLANK() */
			    BLANK()
			)
			
			```
		formatString: 0
		lineageTag: 88ec0cfc-8621-4757-a600-ff7e10c55053
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Conta_nova_mes_5 = ```
			
			VAR DataCriacaoUsuario =
			    RELATED ( bd_users_dimensao_reduzida[dt_criacao_brt] )
			    /*
			    LOOKUPVALUE (
			        bd_users_dimensao_reduzida[dt_criacao_brt],
			        bd_users_dimensao_reduzida[userid], bd_resumo_executivo_user[userid]
			    )
			    */
			
			VAR DataLinha = bd_resumo_executivo_user[data_replica]
			
			VAR InicioMesCriacao =
			    DATE ( YEAR ( DataCriacaoUsuario ), MONTH ( DataCriacaoUsuario ), 1 )
			
			VAR InicioDataLinha =
			    DATE ( YEAR ( DataLinha ), MONTH ( DataLinha ), 1 )
			
			VAR DiffMeses =
			    DATEDIFF (
			        InicioMesCriacao,
			        InicioDataLinha,
			        MONTH
			    )
			
			RETURN
			SWITCH (
			    TRUE(),
			    /* Mês do cadastro, +1 mês e +2 meses → 1 */
			    DiffMeses IN { 0, 1, 2, 3, 4 }, 1,
			
			    /* Três ou mais meses depois do cadastro → 0 */
			    DiffMeses >= 5, 0,
			
			    /* Mês anterior ao cadastro (ou dados inválidos) → BLANK() */
			    BLANK()
			)
			
			```
		formatString: 0
		lineageTag: e9b51ec2-ffc2-4202-9ed0-9f0f8a055852
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Conta_nova_mes_6 = ```
			
			VAR DataCriacaoUsuario =
			    RELATED ( bd_users_dimensao_reduzida[dt_criacao_brt] )
			    /*
			    LOOKUPVALUE (
			        bd_users_dimensao_reduzida[dt_criacao_brt],
			        bd_users_dimensao_reduzida[userid], bd_resumo_executivo_user[userid]
			    )
			    */
			
			VAR DataLinha = bd_resumo_executivo_user[data_replica]
			
			VAR InicioMesCriacao =
			    DATE ( YEAR ( DataCriacaoUsuario ), MONTH ( DataCriacaoUsuario ), 1 )
			
			VAR InicioDataLinha =
			    DATE ( YEAR ( DataLinha ), MONTH ( DataLinha ), 1 )
			
			VAR DiffMeses =
			    DATEDIFF (
			        InicioMesCriacao,
			        InicioDataLinha,
			        MONTH
			    )
			
			RETURN
			SWITCH (
			    TRUE(),
			    /* Mês do cadastro, +1 mês e +2 meses → 1 */
			    DiffMeses IN { 0, 1, 2, 3, 4, 5 }, 1,
			
			    /* Três ou mais meses depois do cadastro → 0 */
			    DiffMeses >= 6, 0,
			
			    /* Mês anterior ao cadastro (ou dados inválidos) → BLANK() */
			    BLANK()
			)
			
			```
		formatString: 0
		lineageTag: 50f749c1-b3f8-4547-bd52-9f57f9214d2b
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column utm_source_cadastro
		dataType: string
		lineageTag: 4da9a1bc-8a3d-4a2c-bd94-d4b319cab531
		summarizeBy: none
		sourceColumn: utm_source_cadastro

		annotation SummarizationSetBy = Automatic

	column utm_medium_cadastro
		dataType: string
		lineageTag: 0d24dbcd-80bb-474c-8730-97eb120d7dcb
		summarizeBy: none
		sourceColumn: utm_medium_cadastro

		annotation SummarizationSetBy = Automatic

	column utm_campaign_cadastro
		dataType: string
		lineageTag: 06f35103-6062-4727-9c40-a6a08d1943f1
		summarizeBy: none
		sourceColumn: utm_campaign_cadastro

		annotation SummarizationSetBy = Automatic

	column utm_content_cadastro
		dataType: string
		lineageTag: 0a2e1700-41ba-41a6-91fb-2f4667f8e3d6
		summarizeBy: none
		sourceColumn: utm_content_cadastro

		annotation SummarizationSetBy = Automatic

	column utm_term_cadastro
		dataType: string
		lineageTag: 05d373de-7240-4187-8225-fcbd7b055d5f
		summarizeBy: none
		sourceColumn: utm_term_cadastro

		annotation SummarizationSetBy = Automatic

	column utm_source_deposito
		dataType: string
		lineageTag: bf956ce8-f81d-4cd6-a2db-d7fa411a257b
		summarizeBy: none
		sourceColumn: utm_source_deposito

		annotation SummarizationSetBy = Automatic

	column utm_medium_deposito
		dataType: string
		lineageTag: 3012da6c-9948-4163-aa24-f7ef12800880
		summarizeBy: none
		sourceColumn: utm_medium_deposito

		annotation SummarizationSetBy = Automatic

	column utm_campaign_deposito
		dataType: string
		lineageTag: 750165ae-e6d3-4fd2-902d-2d3df0465c7d
		summarizeBy: none
		sourceColumn: utm_campaign_deposito

		annotation SummarizationSetBy = Automatic

	column utm_content_deposito
		dataType: string
		lineageTag: 79f52392-71d3-441f-ae7a-fd7444ad3d03
		summarizeBy: none
		sourceColumn: utm_content_deposito

		annotation SummarizationSetBy = Automatic

	column utm_term_deposito
		dataType: string
		lineageTag: 386fed3a-4197-4c60-97c1-0ab9c5347140
		summarizeBy: none
		sourceColumn: utm_term_deposito

		annotation SummarizationSetBy = Automatic

	column Status_FreeSpin = ```
			
			IF (
			    [usuario_freespin_para_filtro] > 0,
			    "Com Free Spin",
			    "Sem Free Spin"
			)
			
			```
		lineageTag: 3ac5d32b-f88a-4240-b17f-dc909382096a
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column apostas_aberto
		dataType: double
		lineageTag: 9d879c93-5a7c-4ee8-9c09-c14711f0e585
		summarizeBy: sum
		sourceColumn: apostas_aberto

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition bd_resumo_executivo_user = m
		mode: import
		source =
				let
				    Fonte = AzureStorage.DataLake("https://kplakehouse.dfs.core.windows.net/gold/resumo_executivo_por_user"),
				    #"Linhas Filtradas" = Table.SelectRows(Fonte, each ([Extension] = ".parquet")),
				    #"Arquivos Ocultos Filtrados1" = Table.SelectRows(#"Linhas Filtradas", each [Attributes]?[Hidden]? <> true),
				    #"Invocar Função Personalizada1" = Table.AddColumn(#"Arquivos Ocultos Filtrados1", "Transformar Arquivo (50)", each #"Transformar Arquivo (50)"([Content])),
				    #"Colunas Renomeadas1" = Table.RenameColumns(#"Invocar Função Personalizada1", {"Name", "Nome da Origem"}),
				    #"Outras Colunas Removidas1" = Table.SelectColumns(#"Colunas Renomeadas1", {"Nome da Origem", "Transformar Arquivo (50)"}),
				    #"Coluna de Tabela Expandida1" = Table.ExpandTableColumn(#"Outras Colunas Removidas1", "Transformar Arquivo (50)", Table.ColumnNames(#"Transformar Arquivo (50)"(#"Arquivo de Amostra (50)"))),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Coluna de Tabela Expandida1",{{"Nome da Origem", type text}, {"userid", type text}, {"data", type date}, {"utm_source_cadastro", type text}, {"utm_medium_cadastro", type text}, {"utm_campaign_cadastro", type text}, {"utm_content_cadastro", type text}, {"utm_term_cadastro", type text}, {"utm_source_deposito", type text}, {"utm_medium_deposito", type text}, {"utm_campaign_deposito", type text}, {"utm_content_deposito", type text}, {"utm_term_deposito", type text}, {"usuarios_migrados", Int64.Type}, {"contas_novas", Int64.Type}, {"contas_depositantes", Int64.Type}, {"clientes_ativos", Int64.Type}, {"contas_ftd", Int64.Type}, {"deposito", type number}, {"qtd_depositos", Int64.Type}, {"qtd_saques", Int64.Type}, {"qtd_aposta_cassino", Int64.Type}, {"qtd_aposta_sportsbook", Int64.Type}, {"qtd_aposta_lb", Int64.Type}, {"saques", type number}, {"total_vip_proprio", type number}, {"total_vip_referral", type number}, {"total_vip_programa", type number}, {"total_crazy_friday", type number}, {"migracao_saldo", type number}, {"ajuste_saldo_manual", type number}, {"aposta_cassino", type number}, {"aposta_sportsbook", type number}, {"aposta_lb", type number}, {"premio_cassino", type number}, {"premio_sportsbook", type number}, {"premio_lb", type number}, {"ggr_cassino", type number}, {"ggr_sportsbook", type number}, {"ggr_lb", type number}, {"ngr", type number}, {"reward", type number}, {"premios_freespins", type number}, {"qtd_usuarios_com_premio_freespins", Int64.Type}, {"saldo_conta", type number}, {"hora_atualizacao", type datetime}, {"status_ativo_90d", Int64.Type}, {"media_l30d", type number}, {"tier_l30d", Int64.Type}, {"tier_high_lifetime", Int64.Type}, {"media_high_lifetime", Int64.Type}}),
				    #"Valor Substituído" = Table.ReplaceValue(#"Tipo Alterado","0","none",Replacer.ReplaceText,{"utm_source_deposito", "utm_medium_deposito", "utm_campaign_deposito", "utm_content_deposito", "utm_term_deposito"}),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Valor Substituído",{{"apostas_aberto", type number}})
				in
				    #"Tipo Alterado1"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

