table bd_softswiss_categoria
	lineageTag: 3ebf1023-aa2a-4c4e-a610-263aae568f18

	column 'Nome da Origem'
		dataType: string
		lineageTag: 9bcc82a1-3b9d-4ae4-954d-aad9b12f94e8
		summarizeBy: none
		sourceColumn: Nome da Origem

		annotation SummarizationSetBy = Automatic

	column data
		dataType: dateTime
		formatString: Long Date
		lineageTag: 1684c332-b8b7-4603-a680-9346c44c336d
		summarizeBy: none
		sourceColumn: data

		variation Variation
			isDefault
			relationship: f1ed1dc4-6aea-4058-9d41-81d8c065f238
			defaultHierarchy: LocalDateTable_470a688d-9f3a-417f-b519-857c00b46eb4.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column nivel_categoria
		dataType: string
		lineageTag: 79552d10-80c5-407c-83da-ff3959755d90
		summarizeBy: none
		sourceColumn: nivel_categoria

		annotation SummarizationSetBy = Automatic

	column categoria
		dataType: string
		lineageTag: 7b7204fa-3bc4-4a8f-b696-0bfebeedbdcf
		summarizeBy: none
		sourceColumn: categoria

		annotation SummarizationSetBy = Automatic

	column total_bet_amount
		dataType: double
		lineageTag: c2f49dbb-094a-40d4-9f28-24fbe1797490
		summarizeBy: sum
		sourceColumn: total_bet_amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column total_win_amount
		dataType: double
		lineageTag: dff0d605-840d-4cf6-a4a6-cd2b4369a5c4
		summarizeBy: sum
		sourceColumn: total_win_amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column total_bet_rollback
		dataType: double
		lineageTag: 769694a2-d421-4103-9ef1-01cd5955477d
		summarizeBy: sum
		sourceColumn: total_bet_rollback

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column total_win_rollback
		dataType: double
		lineageTag: 3a1e8755-e7d9-4ae7-a7f1-5646b90c4661
		summarizeBy: sum
		sourceColumn: total_win_rollback

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column qtd_rodadas
		dataType: int64
		formatString: 0
		lineageTag: 3880a09d-10a8-414f-858a-0597bb775d2f
		summarizeBy: sum
		sourceColumn: qtd_rodadas

		annotation SummarizationSetBy = Automatic

	column status_ativo_90d
		dataType: int64
		formatString: 0
		lineageTag: 15e4f0fd-fce1-457d-80f1-b914e9af022d
		summarizeBy: sum
		sourceColumn: status_ativo_90d

		annotation SummarizationSetBy = Automatic

	column tier_l30d
		dataType: int64
		formatString: 0
		lineageTag: 4932f657-0cd2-47c6-9d4f-a1d67f2788ec
		summarizeBy: sum
		sourceColumn: tier_l30d

		annotation SummarizationSetBy = Automatic

	column media_l30d
		dataType: double
		lineageTag: 88a9c7c5-17e9-4bcc-a48c-877f069594f9
		summarizeBy: sum
		sourceColumn: media_l30d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column tier_high_lifetime
		dataType: int64
		formatString: 0
		lineageTag: cf14da5a-c08f-46fc-89c5-f0f30df2e1bc
		summarizeBy: sum
		sourceColumn: tier_high_lifetime

		annotation SummarizationSetBy = Automatic

	column media_high_lifetime
		dataType: double
		lineageTag: 133e1055-62f7-48b6-a095-9a0b653d2639
		summarizeBy: sum
		sourceColumn: media_high_lifetime

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column utm_campaign
		dataType: string
		lineageTag: eb4a3987-703f-4541-bcc7-40a0d9e72b69
		summarizeBy: none
		sourceColumn: utm_campaign

		annotation SummarizationSetBy = Automatic

	column utm_source
		dataType: string
		lineageTag: e2071b85-3171-4302-9a14-0a9bb2899871
		summarizeBy: none
		sourceColumn: utm_source

		annotation SummarizationSetBy = Automatic

	column utm_medium
		dataType: string
		lineageTag: e7e79c8a-29d5-4342-8a45-e744968b16f5
		summarizeBy: none
		sourceColumn: utm_medium

		annotation SummarizationSetBy = Automatic

	column utm_content
		dataType: string
		lineageTag: 17550b96-529b-459f-b0a7-89a7a262767a
		summarizeBy: none
		sourceColumn: utm_content

		annotation SummarizationSetBy = Automatic

	column utm_term
		dataType: string
		lineageTag: ad4d3469-66e0-4d9f-bc8d-2ca451cbbe1f
		summarizeBy: none
		sourceColumn: utm_term

		annotation SummarizationSetBy = Automatic

	column data_hora_atualizacao
		dataType: dateTime
		formatString: General Date
		lineageTag: b68aec70-bf0d-4aa0-9fb1-343bcebd109e
		summarizeBy: none
		sourceColumn: data_hora_atualizacao

		variation Variation
			isDefault
			relationship: 568442b1-c99a-4c57-9762-d7c35143ccc0
			defaultHierarchy: LocalDateTable_086af90c-2bd7-49c6-8fe8-157f5e1827ef.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column provider
		dataType: string
		lineageTag: 25416a1f-8121-4b92-aa37-a2e2cd47880a
		summarizeBy: none
		sourceColumn: provider

		annotation SummarizationSetBy = Automatic

	column producer
		dataType: string
		lineageTag: 416bf345-141a-4723-83ed-56911566806a
		summarizeBy: none
		sourceColumn: producer

		annotation SummarizationSetBy = Automatic

	partition bd_softswiss_categoria = m
		mode: import
		source =
				let
				    Fonte = AzureStorage.DataLake("https://kplakehouse.dfs.core.windows.net/gold/softswiss_categoria"),
				    #"Linhas Filtradas" = Table.SelectRows(Fonte, each ([Extension] = ".parquet")),
				    #"Arquivos Ocultos Filtrados1" = Table.SelectRows(#"Linhas Filtradas", each [Attributes]?[Hidden]? <> true),
				    #"Invocar Função Personalizada1" = Table.AddColumn(#"Arquivos Ocultos Filtrados1", "Transformar Arquivo (43)", each #"Transformar Arquivo (43)"([Content])),
				    #"Colunas Renomeadas1" = Table.RenameColumns(#"Invocar Função Personalizada1", {"Name", "Nome da Origem"}),
				    #"Outras Colunas Removidas1" = Table.SelectColumns(#"Colunas Renomeadas1", {"Nome da Origem", "Transformar Arquivo (43)"}),
				    #"Coluna de Tabela Expandida1" = Table.ExpandTableColumn(#"Outras Colunas Removidas1", "Transformar Arquivo (43)", Table.ColumnNames(#"Transformar Arquivo (43)"(#"Arquivo de Amostra (43)"))),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Coluna de Tabela Expandida1",{{"Nome da Origem", type text}, {"data", type date}, {"nivel_categoria", type text}, {"categoria", type text}, {"total_bet_amount", type number}, {"total_win_amount", type number}, {"total_bet_rollback", type number}, {"total_win_rollback", type number}, {"qtd_rodadas", Int64.Type}, {"status_ativo_90d", Int64.Type}, {"tier_l30d", Int64.Type}, {"media_l30d", type number}, {"tier_high_lifetime", Int64.Type}, {"media_high_lifetime", type number}, {"utm_campaign", type text}, {"utm_source", type text}, {"utm_medium", type text}, {"utm_content", type text}, {"utm_term", type text}, {"data_hora_atualizacao", type datetime}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

