table bd_softswiss
	lineageTag: 371dfc28-04f4-4056-9a14-a394f73d64b9

	measure total_aposta_com_outros = ```
			SUM(bd_softswiss[total_aposta_dispersao])
			
			```
		lineageTag: 3bb19844-f31e-414f-8d65-903ebbfa0b26

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure clientes_ativos_com_outros =
			
			CALCULATE(
			    DISTINCTCOUNT(bd_softswiss[userid]),
			    bd_softswiss[total_bet_amount] > 0
			)
		formatString: 0
		lineageTag: 226736f5-4d1f-4556-8216-69e9ca1d1e55

	measure premio_rollback_com_outros = ```
			SUM(bd_softswiss[total_win_rollback])
			
			```
		formatString: 0
		lineageTag: f80bbae0-b206-46d9-b4f5-1099d7e591ff

	measure aposta_rollback_com_outros = ```
			SUM(bd_softswiss[total_bet_rollback])
			
			```
		lineageTag: 9c3dddc9-c1a8-4955-a030-7c8acdb2693a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Nome da Origem'
		dataType: string
		lineageTag: c824706d-1dc3-4adc-9e4a-694ce8255dde
		summarizeBy: none
		sourceColumn: Nome da Origem

		annotation SummarizationSetBy = Automatic

	column data
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6aa26f80-0f38-400e-9ee2-1ad53149ff68
		summarizeBy: none
		sourceColumn: data

		variation Variation
			isDefault
			relationship: 918b54a6-0a9c-4a0f-a7a3-d0ae31908461
			defaultHierarchy: LocalDateTable_8df97490-291b-446e-bcda-79f571aeaf47.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column uuid
		dataType: string
		lineageTag: d84a0fc1-ca52-4247-8a1d-59ffab0c5a67
		summarizeBy: none
		sourceColumn: uuid

		annotation SummarizationSetBy = Automatic

	column accountid
		dataType: string
		lineageTag: f85a2943-4ed0-4ad6-a75b-388ff6603a67
		summarizeBy: none
		sourceColumn: accountid

		annotation SummarizationSetBy = Automatic

	column userid
		dataType: string
		lineageTag: a32a5235-24e4-4287-9022-645df472620a
		summarizeBy: none
		sourceColumn: userid

		annotation SummarizationSetBy = Automatic

	column kp_game_id
		dataType: string
		lineageTag: 3231efbf-97aa-46d2-9c9b-cdb717822a59
		summarizeBy: none
		sourceColumn: kp_game_id

		annotation SummarizationSetBy = Automatic

	column total_bet_amount
		dataType: double
		lineageTag: 2d8a0f6f-0d68-429c-b055-f2ca1300fa88
		summarizeBy: sum
		sourceColumn: total_bet_amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column total_win_amount
		dataType: double
		lineageTag: cc027a83-660f-4556-8b48-1ef0ba1f1f9c
		summarizeBy: sum
		sourceColumn: total_win_amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column total_bet_rollback
		dataType: double
		lineageTag: 7d7d802f-4f5b-495c-8916-0a74575e24b3
		summarizeBy: sum
		sourceColumn: total_bet_rollback

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column total_win_rollback
		dataType: double
		formatString: 0
		lineageTag: b608f84f-a5be-434e-8007-2ef02e5df705
		summarizeBy: sum
		sourceColumn: total_win_rollback

		annotation SummarizationSetBy = Automatic

	column qtd_rodadas
		dataType: int64
		formatString: 0
		lineageTag: a72076df-83a1-4f7d-b8cf-3e384b665981
		summarizeBy: sum
		sourceColumn: qtd_rodadas

		annotation SummarizationSetBy = Automatic

	column game_aggregator_id
		dataType: string
		lineageTag: 1525cb4c-244c-4323-82ba-759bf336b223
		summarizeBy: none
		sourceColumn: game_aggregator_id

		annotation SummarizationSetBy = Automatic

	column provider
		dataType: string
		lineageTag: aabd456b-659d-4a8f-9504-41437b9bc09c
		summarizeBy: none
		sourceColumn: provider

		annotation SummarizationSetBy = Automatic

		annotation __PBI_SemanticLinks = [{"LinkTarget":{"TableName":"bd_softswiss","TableItemName":"provider (grupos)","ObjectType":4},"LinkType":"UsedInGroup"}]

	column description
		dataType: string
		lineageTag: ff1c8e19-e240-4bee-89d6-0a32359e6fb6
		summarizeBy: none
		sourceColumn: description

		annotation SummarizationSetBy = Automatic

	column category1
		dataType: string
		lineageTag: fa79598a-11b5-4fdf-9454-4ec501313fae
		summarizeBy: none
		sourceColumn: category1

		annotation SummarizationSetBy = Automatic

	column category2
		dataType: string
		lineageTag: 22b08d41-5168-4daf-b901-872e62be98b6
		summarizeBy: none
		sourceColumn: category2

		annotation SummarizationSetBy = Automatic

	column category3
		dataType: string
		lineageTag: 174887b8-b15d-432a-b3f5-fdd5bcc47d11
		summarizeBy: none
		sourceColumn: category3

		annotation SummarizationSetBy = Automatic

	column status_ativo_90d
		dataType: string
		lineageTag: 39852149-7451-4307-ba01-7d57d9a22f2e
		summarizeBy: none
		sourceColumn: status_ativo_90d

		annotation SummarizationSetBy = Automatic

	column media_l30d
		dataType: string
		lineageTag: 516c193a-2921-4bc8-93b0-790ac959281b
		summarizeBy: none
		sourceColumn: media_l30d

		annotation SummarizationSetBy = Automatic

	column tier_l30d
		dataType: int64
		formatString: 0
		lineageTag: d75adc97-8306-488f-907b-cb5a1bd198fe
		summarizeBy: sum
		sourceColumn: tier_l30d

		annotation SummarizationSetBy = Automatic

	column tier_high_lifetime
		dataType: int64
		formatString: 0
		lineageTag: dd66d8e1-56f2-43ec-937f-2feb56ee97cf
		summarizeBy: sum
		sourceColumn: tier_high_lifetime

		annotation SummarizationSetBy = Automatic

	column media_high_lifetime
		dataType: double
		lineageTag: 42b37483-e0b3-449e-8932-e2bab0575e53
		summarizeBy: sum
		sourceColumn: media_high_lifetime

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'provider (grupos)' =
			SWITCH(
				TRUE,
				ISBLANK('bd_softswiss'[provider]),
				"(Em branco)",
				'bd_softswiss'[provider] IN {"1x2gaming",
					"beterlive",
					"bfgames",
					"caleta",
					"endorphina",
					"ezugi",
					"habanero",
					"hacksaw",
					"kagaming",
					"platipus",
					"playngo",
					"relax",
					"rubyplay",
					"softswiss",
					"spnmnl",
					"technology",
					"wazdan",
					"yggdrasil"},
				"Outros",
				'bd_softswiss'[provider]
			)
		lineageTag: c891c195-fc30-4861-b919-fbbb9e78961c
		summarizeBy: none

		extendedProperty GroupingMetadata =
				{
				  "version": 0,
				  "groupedColumns": [
				    {
				      "Column": {
				        "Expression": {
				          "SourceRef": {
				            "Entity": "bd_softswiss"
				          }
				        },
				        "Property": "provider"
				      }
				    }
				  ]
				}

		annotation GroupingDesignState = {"Version":0,"Sources":[{"Name":"b","Entity":"bd_softswiss"}],"GroupedColumns":[{"Column":{"Expression":{"SourceRef":{"Source":"b"}},"Property":"provider"}}],"GroupItems":[{"DisplayName":"(Em branco)","BlankDefaultPlaceholder":true},{"DisplayName":"Outros","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"b"}},"Property":"provider"}}],"Values":[[{"Literal":{"Value":"'1x2gaming'"}}],[{"Literal":{"Value":"'beterlive'"}}],[{"Literal":{"Value":"'bfgames'"}}],[{"Literal":{"Value":"'caleta'"}}],[{"Literal":{"Value":"'endorphina'"}}],[{"Literal":{"Value":"'ezugi'"}}],[{"Literal":{"Value":"'habanero'"}}],[{"Literal":{"Value":"'hacksaw'"}}],[{"Literal":{"Value":"'kagaming'"}}],[{"Literal":{"Value":"'platipus'"}}],[{"Literal":{"Value":"'playngo'"}}],[{"Literal":{"Value":"'relax'"}}],[{"Literal":{"Value":"'rubyplay'"}}],[{"Literal":{"Value":"'softswiss'"}}],[{"Literal":{"Value":"'spnmnl'"}}],[{"Literal":{"Value":"'technology'"}}],[{"Literal":{"Value":"'wazdan'"}}],[{"Literal":{"Value":"'yggdrasil'"}}]]}}}]}

		annotation SummarizationSetBy = Automatic

	column category_full
		dataType: string
		lineageTag: 515e16e0-796b-4621-a2ce-63959e492140
		summarizeBy: none
		sourceColumn: category_full

		annotation SummarizationSetBy = Automatic

	column total_aposta_dispersao
		dataType: double
		lineageTag: e536b1c5-e7dc-428b-bf84-923660cf72e1
		summarizeBy: sum
		sourceColumn: total_aposta_dispersao

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LinkUserID = "https://admin-ai.kingpanda.com/users?userid=" & bd_softswiss[userid]
		lineageTag: f07f0e89-a502-418f-ba6c-28a9684a0b83
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column ggr_dispersao
		dataType: double
		lineageTag: a44fc1f4-e017-4111-bf84-a801b0fc95b7
		summarizeBy: sum
		sourceColumn: ggr_dispersao

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column utm_source
		dataType: string
		lineageTag: 5a00210b-bb63-4e51-9f44-0bb63759ab58
		summarizeBy: none
		sourceColumn: utm_source

		annotation SummarizationSetBy = Automatic

	column utm_medium
		dataType: string
		lineageTag: c5e2952f-efea-412e-8d0a-28780cce092d
		summarizeBy: none
		sourceColumn: utm_medium

		annotation SummarizationSetBy = Automatic

	column utm_campaign
		dataType: string
		lineageTag: 0b65eea1-a23a-4e55-9f9d-adf6ae35477d
		summarizeBy: none
		sourceColumn: utm_campaign

		annotation SummarizationSetBy = Automatic

	column utm_content
		dataType: string
		lineageTag: f52cbaa3-78da-4d70-b1c1-8dc5b8914072
		summarizeBy: none
		sourceColumn: utm_content

		annotation SummarizationSetBy = Automatic

	column utm_term
		dataType: string
		lineageTag: 6296cbb1-1559-448b-a1f2-96a62f6122da
		summarizeBy: none
		sourceColumn: utm_term

		annotation SummarizationSetBy = Automatic

	column Total_Aposta_por_Description = ```
			
			VAR _desc = bd_softswiss[description]          -- valor desta linha
			RETURN
			CALCULATE (
			    SUM ( bd_softswiss[total_aposta_dispersao] ),
			    FILTER (                                     
			        ALLSELECTED ( bd_softswiss ),                     -- ignora o contexto de linha
			        bd_softswiss[description] = _desc         -- mantém apenas linhas com o mesmo description
			    )
			)
			
			
			```
		lineageTag: 06a4fa0c-f76f-457a-ab64-00729931a1c3
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Total_GGR_por_Description = ```
			
			VAR _desc = bd_softswiss[description]          -- valor desta linha
			RETURN
			CALCULATE (
			    SUM ( bd_softswiss[ggr_dispersao] ),
			    FILTER (                                     
			        ALLSELECTED ( bd_softswiss ),                     -- ignora o contexto de linha
			        bd_softswiss[description] = _desc         -- mantém apenas linhas com o mesmo description
			    )
			)
			
			
			```
		lineageTag: 08a4caeb-5ee5-42a3-83f5-27366133c3f7
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Total_Aposta_por_User = ```
			
			VAR _user = bd_softswiss[userid]          
			RETURN
			CALCULATE (
			    SUM ( bd_softswiss[total_aposta_dispersao] ),
			    FILTER (                                     
			        ALLSELECTED ( bd_softswiss ),                    
			        bd_softswiss[userid] = _user         
			    )
			)
			
			```
		lineageTag: 5342f090-84ce-40d9-befb-aaf0315ebef7
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Total_GGR_por_User = ```
			
			VAR _user = bd_softswiss[userid]          
			RETURN
			CALCULATE (
			    SUM ( bd_softswiss[ggr_dispersao] ),
			    FILTER (                                     
			        ALLSELECTED ( bd_softswiss ),                    
			        bd_softswiss[userid] = _user         
			    )
			)
			
			```
		lineageTag: 7430ff06-577e-4bee-b6f2-ae71578826ae
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column hora_atualizacao
		dataType: dateTime
		formatString: General Date
		lineageTag: cd8486b1-5e33-43ae-9796-ee0199705720
		summarizeBy: none
		sourceColumn: hora_atualizacao

		variation Variation
			isDefault
			relationship: ca863ac9-4dc4-4bb9-abe1-d3ac62f2824a
			defaultHierarchy: LocalDateTable_5b84aaf9-abcf-4b49-9c81-82ca4ce87f57.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column producer
		dataType: string
		lineageTag: 3ec06f71-04d8-4905-a658-81ebcd908468
		summarizeBy: none
		sourceColumn: producer

		annotation SummarizationSetBy = Automatic

	partition bd_softswiss = m
		mode: import
		source =
				let
				    Fonte = AzureStorage.DataLake("https://kplakehouse.dfs.core.windows.net/gold/softswiss"),
				    #"Linhas Filtradas" = Table.SelectRows(Fonte, each ([Extension] = ".parquet")),
				    #"Arquivos Ocultos Filtrados1" = Table.SelectRows(#"Linhas Filtradas", each [Attributes]?[Hidden]? <> true),
				    #"Invocar Função Personalizada1" = Table.AddColumn(#"Arquivos Ocultos Filtrados1", "Transformar Arquivo (11)", each #"Transformar Arquivo (11)"([Content])),
				    #"Colunas Renomeadas1" = Table.RenameColumns(#"Invocar Função Personalizada1", {"Name", "Nome da Origem"}),
				    #"Outras Colunas Removidas1" = Table.SelectColumns(#"Colunas Renomeadas1", {"Nome da Origem", "Transformar Arquivo (11)"}),
				    #"Coluna de Tabela Expandida1" = Table.ExpandTableColumn(#"Outras Colunas Removidas1", "Transformar Arquivo (11)", Table.ColumnNames(#"Transformar Arquivo (11)"(#"Arquivo de Amostra (11)"))),
				    #"Personalização Adicionada" = Table.AddColumn(#"Coluna de Tabela Expandida1", "total_aposta_dispersao", each [total_bet_amount] - [total_bet_rollback]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Personalização Adicionada",{{"total_bet_amount", type number}, {"total_win_amount", type number}, {"total_bet_rollback", type number}, {"total_win_rollback", type number}, {"total_aposta_dispersao", type number}, {"media_high_lifetime", type number}}),
				    #"Personalização Adicionada1" = Table.AddColumn(#"Tipo Alterado", "ggr_dispersao", each ([total_bet_amount] - [total_bet_rollback]) - ([total_win_amount] - [total_win_rollback])),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Personalização Adicionada1",{{"ggr_dispersao", type number}, {"qtd_rodadas", Int64.Type}, {"tier_high_lifetime", Int64.Type}, {"tier_l30d", Int64.Type}, {"data", type date}, {"hora_atualizacao", type datetime}})
				in
				    #"Tipo Alterado1"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

