table bd_timeline
	lineageTag: ceb796ef-d712-452c-a242-bd3d07a3fd14

	column utm_source
		dataType: string
		lineageTag: 96d6647e-06ff-4c93-90e3-b009f155af18
		summarizeBy: none
		sourceColumn: utm_source

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column utm_medium
		dataType: string
		lineageTag: 84bdaa7f-ae3c-4c5f-83c1-cea92cedb917
		summarizeBy: none
		sourceColumn: utm_medium

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column utm_content
		dataType: string
		lineageTag: b84bab4b-b7e7-402c-96af-ea6c41b8e327
		summarizeBy: none
		sourceColumn: utm_content

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column utm_term
		dataType: string
		lineageTag: 12b11d2a-a7ee-4a4b-a6bc-290499415e3c
		summarizeBy: none
		sourceColumn: utm_term

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column utm_campaign
		dataType: string
		lineageTag: 1f877b51-47b9-47b1-81db-49acca821bd8
		summarizeBy: none
		sourceColumn: utm_campaign

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column data_base
		dataType: dateTime
		formatString: Long Date
		lineageTag: 5cb4054c-ac20-4d93-a452-ab45192d5b6c
		summarizeBy: none
		sourceColumn: data_base

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column qtd_ftd
		dataType: int64
		formatString: 0
		lineageTag: 96db6957-7ba6-4eb4-8683-8774afba9f90
		summarizeBy: sum
		sourceColumn: qtd_ftd

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column qtd_depositantes_1d
		dataType: int64
		formatString: 0
		lineageTag: 1d0cf6f1-8f60-483f-8769-51bea1e3e7ea
		summarizeBy: sum
		sourceColumn: qtd_depositantes_1d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column qtd_depositantes_3d
		dataType: int64
		formatString: 0
		lineageTag: 54931316-21b1-448f-adc3-105bd8887875
		summarizeBy: sum
		sourceColumn: qtd_depositantes_3d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column qtd_depositantes_7d
		dataType: int64
		formatString: 0
		lineageTag: fa798c2d-00f0-49f0-94d0-19b6bd3edff0
		summarizeBy: sum
		sourceColumn: qtd_depositantes_7d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column qtd_depositantes_15d
		dataType: int64
		formatString: 0
		lineageTag: f50d66e6-365a-48a3-a209-1f8d25a7d5b9
		summarizeBy: sum
		sourceColumn: qtd_depositantes_15d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column qtd_depositantes_30d
		dataType: int64
		formatString: 0
		lineageTag: 145b2e81-6856-44c1-9fac-d5ffbebebd83
		summarizeBy: sum
		sourceColumn: qtd_depositantes_30d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column qtd_depositantes_60d
		dataType: int64
		formatString: 0
		lineageTag: 2bf0fd49-73d0-46ad-948b-bcae07c73910
		summarizeBy: sum
		sourceColumn: qtd_depositantes_60d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column qtd_depositantes_90d
		dataType: int64
		formatString: 0
		lineageTag: 413f5904-9a1f-4644-ac92-75cf711b514b
		summarizeBy: sum
		sourceColumn: qtd_depositantes_90d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column qtd_apostadores_1d
		dataType: int64
		formatString: 0
		lineageTag: a85159b7-0bed-4c72-8c1e-b840e6f97a2b
		summarizeBy: sum
		sourceColumn: qtd_apostadores_1d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column qtd_apostadores_3d
		dataType: int64
		formatString: 0
		lineageTag: 29ac1c6b-9915-47af-843b-7722cc8a54cb
		summarizeBy: sum
		sourceColumn: qtd_apostadores_3d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column qtd_apostadores_7d
		dataType: int64
		formatString: 0
		lineageTag: 2702fd7f-722a-4e5e-b3c5-0c1506684546
		summarizeBy: sum
		sourceColumn: qtd_apostadores_7d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column qtd_apostadores_15d
		dataType: int64
		formatString: 0
		lineageTag: f4594d6d-750e-40ad-afff-cacd89ffeeb5
		summarizeBy: sum
		sourceColumn: qtd_apostadores_15d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column qtd_apostadores_30d
		dataType: int64
		formatString: 0
		lineageTag: aec6f86b-afda-46ad-87cc-d80d703e4219
		summarizeBy: sum
		sourceColumn: qtd_apostadores_30d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column qtd_apostadores_60d
		dataType: int64
		formatString: 0
		lineageTag: 6831a970-0ac4-4b96-8f29-94db43c39b72
		summarizeBy: sum
		sourceColumn: qtd_apostadores_60d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column qtd_apostadores_90d
		dataType: int64
		formatString: 0
		lineageTag: 402b117f-475f-414e-a8b6-f8cd534d520c
		summarizeBy: sum
		sourceColumn: qtd_apostadores_90d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column deposito_1d
		dataType: double
		lineageTag: 789be1c6-06a3-469d-917d-debe8710b038
		summarizeBy: sum
		sourceColumn: deposito_1d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column deposito_3d
		dataType: double
		lineageTag: 0d77c683-4230-4dd0-91f8-3bbc8f7e2e65
		summarizeBy: sum
		sourceColumn: deposito_3d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column deposito_7d
		dataType: double
		lineageTag: 4b1c82af-f862-4b6d-91f7-2b199b5d409a
		summarizeBy: sum
		sourceColumn: deposito_7d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column deposito_15d
		dataType: double
		lineageTag: ea04fa94-a1f7-4c6a-a3ae-e60546c8cb12
		summarizeBy: sum
		sourceColumn: deposito_15d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column deposito_30d
		dataType: double
		lineageTag: 8361e016-0cc7-4693-a4cb-1a8ec0edc74a
		summarizeBy: sum
		sourceColumn: deposito_30d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column deposito_60d
		dataType: double
		lineageTag: 4d6b29a5-87d6-440b-8856-e7aaed72f3b8
		summarizeBy: sum
		sourceColumn: deposito_60d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column deposito_90d
		dataType: double
		lineageTag: 55810378-ab9f-4cef-84b3-1102baf90a5f
		summarizeBy: sum
		sourceColumn: deposito_90d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column aposta_cassino_1d
		dataType: double
		lineageTag: eecff5e0-39c2-44c3-9c23-2810adac0bec
		summarizeBy: sum
		sourceColumn: aposta_cassino_1d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column aposta_cassino_3d
		dataType: double
		lineageTag: 630fc662-fa27-4061-9505-c2a851f8cfbc
		summarizeBy: sum
		sourceColumn: aposta_cassino_3d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column aposta_cassino_7d
		dataType: double
		lineageTag: e068011b-0178-49c0-aa48-8ec9a806b821
		summarizeBy: sum
		sourceColumn: aposta_cassino_7d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column aposta_cassino_15d
		dataType: double
		lineageTag: e4f3ec0d-1935-423e-b44b-f695fa05cdf9
		summarizeBy: sum
		sourceColumn: aposta_cassino_15d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column aposta_cassino_30d
		dataType: double
		lineageTag: ae8bb21a-c7eb-409d-952f-00bc76d1d4c9
		summarizeBy: sum
		sourceColumn: aposta_cassino_30d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column aposta_cassino_60d
		dataType: double
		lineageTag: 53104612-105c-46d2-a842-a9be09fe06f6
		summarizeBy: sum
		sourceColumn: aposta_cassino_60d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column aposta_cassino_90d
		dataType: double
		lineageTag: 0abee6ce-ae17-4a2b-a945-bd60597b92cd
		summarizeBy: sum
		sourceColumn: aposta_cassino_90d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column premio_cassino_1d
		dataType: double
		lineageTag: 9fdf1184-ec9f-4890-bfbd-6b8a03b0538a
		summarizeBy: sum
		sourceColumn: premio_cassino_1d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column premio_cassino_3d
		dataType: double
		lineageTag: 81c90119-5224-4db1-845f-f53a4496199a
		summarizeBy: sum
		sourceColumn: premio_cassino_3d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column premio_cassino_7d
		dataType: double
		lineageTag: ef8384f2-089b-47b0-9453-b55e8193fcdc
		summarizeBy: sum
		sourceColumn: premio_cassino_7d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column premio_cassino_15d
		dataType: double
		lineageTag: ee4c3d28-d49d-4721-aac3-2554a6423d82
		summarizeBy: sum
		sourceColumn: premio_cassino_15d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column premio_cassino_30d
		dataType: double
		lineageTag: 67cc0514-e5ae-4d3a-95d0-de479e12a3e8
		summarizeBy: sum
		sourceColumn: premio_cassino_30d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column premio_cassino_60d
		dataType: double
		lineageTag: 3a8c147d-8674-42ed-827c-c77db3f2b40b
		summarizeBy: sum
		sourceColumn: premio_cassino_60d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column premio_cassino_90d
		dataType: double
		lineageTag: a4fe9300-3fe2-4703-9fe5-3d76fdab8e6c
		summarizeBy: sum
		sourceColumn: premio_cassino_90d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ggr_cassino_1d
		dataType: double
		lineageTag: 3da1bb5c-5736-4854-ae96-d81a5aa5b4b3
		summarizeBy: sum
		sourceColumn: ggr_cassino_1d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ggr_cassino_3d
		dataType: double
		lineageTag: 7287c3b7-139a-4c1a-aa0c-65349838da08
		summarizeBy: sum
		sourceColumn: ggr_cassino_3d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ggr_cassino_7d
		dataType: double
		lineageTag: ce63834f-fe4c-48a1-a1f2-787a44ce379b
		summarizeBy: sum
		sourceColumn: ggr_cassino_7d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ggr_cassino_15d
		dataType: double
		lineageTag: 5d360811-da44-410e-a759-07b88365dfe9
		summarizeBy: sum
		sourceColumn: ggr_cassino_15d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ggr_cassino_30d
		dataType: double
		lineageTag: 0e17214a-30b6-4886-8840-8df84642f75b
		summarizeBy: sum
		sourceColumn: ggr_cassino_30d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ggr_cassino_60d
		dataType: double
		lineageTag: 92c34b61-91d8-4e6d-b849-39f70bba9096
		summarizeBy: sum
		sourceColumn: ggr_cassino_60d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ggr_cassino_90d
		dataType: double
		lineageTag: fb1e3149-f083-4b67-ad29-aff3b46cae1e
		summarizeBy: sum
		sourceColumn: ggr_cassino_90d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column aposta_sportsbook_1d
		dataType: double
		lineageTag: 644d93ff-c613-40f6-a44a-1c6a9584d3bf
		summarizeBy: sum
		sourceColumn: aposta_sportsbook_1d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column aposta_sportsbook_3d
		dataType: double
		lineageTag: 0e1c1419-a752-4014-855d-72c4bd623b08
		summarizeBy: sum
		sourceColumn: aposta_sportsbook_3d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column aposta_sportsbook_7d
		dataType: double
		lineageTag: 1c1fd2e8-df85-4bbd-9093-c22ee8f117c6
		summarizeBy: sum
		sourceColumn: aposta_sportsbook_7d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column aposta_sportsbook_15d
		dataType: double
		lineageTag: 629774af-1405-4bbb-a149-8c0cd0ca66e6
		summarizeBy: sum
		sourceColumn: aposta_sportsbook_15d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column aposta_sportsbook_30d
		dataType: double
		lineageTag: ddedd921-0e04-4f07-b6fa-504e25493d4f
		summarizeBy: sum
		sourceColumn: aposta_sportsbook_30d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column aposta_sportsbook_60d
		dataType: double
		lineageTag: 2785a174-47c5-47c3-8986-7c8042626ed2
		summarizeBy: sum
		sourceColumn: aposta_sportsbook_60d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column aposta_sportsbook_90d
		dataType: double
		lineageTag: fd739a96-b18e-455b-b102-1ead2ea8fe4b
		summarizeBy: sum
		sourceColumn: aposta_sportsbook_90d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column premio_sportsbook_1d
		dataType: double
		lineageTag: fe1a751e-89d6-454c-9df2-b8a568a70924
		summarizeBy: sum
		sourceColumn: premio_sportsbook_1d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column premio_sportsbook_3d
		dataType: double
		lineageTag: 65727cf7-bd68-404a-9967-826ea130622f
		summarizeBy: sum
		sourceColumn: premio_sportsbook_3d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column premio_sportsbook_7d
		dataType: double
		lineageTag: e87b2f75-11f8-49f8-b124-11de53faa25c
		summarizeBy: sum
		sourceColumn: premio_sportsbook_7d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column premio_sportsbook_15d
		dataType: double
		lineageTag: 30c2ac11-dc20-47d9-bb23-28cf7166b1b2
		summarizeBy: sum
		sourceColumn: premio_sportsbook_15d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column premio_sportsbook_30d
		dataType: double
		lineageTag: f1316cff-b58b-41bd-bf00-2625ec7e376a
		summarizeBy: sum
		sourceColumn: premio_sportsbook_30d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column premio_sportsbook_60d
		dataType: double
		lineageTag: 15be4705-40ae-4cff-b9ea-481834eca0b5
		summarizeBy: sum
		sourceColumn: premio_sportsbook_60d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column premio_sportsbook_90d
		dataType: double
		lineageTag: a1799469-f94c-462f-a216-5b6adcc6b742
		summarizeBy: sum
		sourceColumn: premio_sportsbook_90d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ggr_sportsbook_1d
		dataType: double
		lineageTag: 85549b1b-e747-4b42-9fab-97a4c1fd8443
		summarizeBy: sum
		sourceColumn: ggr_sportsbook_1d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ggr_sportsbook_3d
		dataType: double
		lineageTag: 0a6c0cff-817e-4406-a7b4-dc50d2e18936
		summarizeBy: sum
		sourceColumn: ggr_sportsbook_3d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ggr_sportsbook_7d
		dataType: double
		lineageTag: 152ef558-cadf-4588-a38e-5a28d765b7f6
		summarizeBy: sum
		sourceColumn: ggr_sportsbook_7d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ggr_sportsbook_15d
		dataType: double
		lineageTag: d0138e5d-2c3f-4945-a883-c9194e50712a
		summarizeBy: sum
		sourceColumn: ggr_sportsbook_15d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ggr_sportsbook_30d
		dataType: double
		lineageTag: e4c80b11-1bec-4c20-88ec-2256e620bd63
		summarizeBy: sum
		sourceColumn: ggr_sportsbook_30d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ggr_sportsbook_60d
		dataType: double
		lineageTag: 4a68f95f-deef-4941-a790-8930391d3517
		summarizeBy: sum
		sourceColumn: ggr_sportsbook_60d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ggr_sportsbook_90d
		dataType: double
		lineageTag: 24f7c964-8c10-4536-9c9b-bb5da063ec11
		summarizeBy: sum
		sourceColumn: ggr_sportsbook_90d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column aposta_lb_1d
		dataType: double
		formatString: 0
		lineageTag: 1d2f1096-e145-424f-8674-cf17cf0f3641
		summarizeBy: sum
		sourceColumn: aposta_lb_1d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column aposta_lb_3d
		dataType: double
		formatString: 0
		lineageTag: c9011ee3-38db-4362-ba67-8a2c677ff880
		summarizeBy: sum
		sourceColumn: aposta_lb_3d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column aposta_lb_7d
		dataType: double
		formatString: 0
		lineageTag: 4e99dcce-8c2a-4764-9cae-496164e486f0
		summarizeBy: sum
		sourceColumn: aposta_lb_7d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column aposta_lb_15d
		dataType: double
		formatString: 0
		lineageTag: 26bad871-5004-45ff-8349-b3fe71941c93
		summarizeBy: sum
		sourceColumn: aposta_lb_15d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column aposta_lb_30d
		dataType: double
		formatString: 0
		lineageTag: 161d1ce5-36e3-417a-b184-781618257434
		summarizeBy: sum
		sourceColumn: aposta_lb_30d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column aposta_lb_60d
		dataType: double
		formatString: 0
		lineageTag: 55353f6e-47be-4eae-8848-45c3b158f332
		summarizeBy: sum
		sourceColumn: aposta_lb_60d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column aposta_lb_90d
		dataType: double
		formatString: 0
		lineageTag: ca72f020-b6bc-4e4a-a9d4-93bb08b17561
		summarizeBy: sum
		sourceColumn: aposta_lb_90d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column premio_lb_1d
		dataType: double
		lineageTag: fcb96780-a44d-4ab6-9c8e-bcdf716db023
		summarizeBy: sum
		sourceColumn: premio_lb_1d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column premio_lb_3d
		dataType: double
		lineageTag: 6e522c54-570d-4cc1-b5e9-f959c1af513f
		summarizeBy: sum
		sourceColumn: premio_lb_3d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column premio_lb_7d
		dataType: double
		lineageTag: 762289bb-3028-4994-a29a-3332f55835f1
		summarizeBy: sum
		sourceColumn: premio_lb_7d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column premio_lb_15d
		dataType: double
		lineageTag: 4846c602-7a6d-4a96-8ec4-7a30f5a5a033
		summarizeBy: sum
		sourceColumn: premio_lb_15d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column premio_lb_30d
		dataType: double
		lineageTag: 5bafab82-eaf2-4549-8605-d2988381f700
		summarizeBy: sum
		sourceColumn: premio_lb_30d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column premio_lb_60d
		dataType: double
		lineageTag: 66f111f2-35e3-4f42-8bc5-94b3b8ddfb37
		summarizeBy: sum
		sourceColumn: premio_lb_60d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column premio_lb_90d
		dataType: double
		lineageTag: 9f655e01-a4b5-4829-81cc-756c4b87e6dd
		summarizeBy: sum
		sourceColumn: premio_lb_90d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ggr_lb_1d
		dataType: double
		lineageTag: fae09b74-06c2-47e4-8380-87f99ec81e36
		summarizeBy: sum
		sourceColumn: ggr_lb_1d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ggr_lb_3d
		dataType: double
		lineageTag: 2132a34c-8a8a-4afb-8c3a-f0405f78e25d
		summarizeBy: sum
		sourceColumn: ggr_lb_3d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ggr_lb_7d
		dataType: double
		lineageTag: 963ec075-58c0-4ea4-8611-eac61886fa1c
		summarizeBy: sum
		sourceColumn: ggr_lb_7d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ggr_lb_15d
		dataType: double
		lineageTag: 8427a7af-8080-4dd3-a52a-dd4547eaaa87
		summarizeBy: sum
		sourceColumn: ggr_lb_15d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ggr_lb_30d
		dataType: double
		lineageTag: 26711581-b6a2-4275-8785-853953de102e
		summarizeBy: sum
		sourceColumn: ggr_lb_30d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ggr_lb_60d
		dataType: double
		lineageTag: 8b31ed69-d3b2-4490-8023-2f327b100329
		summarizeBy: sum
		sourceColumn: ggr_lb_60d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ggr_lb_90d
		dataType: double
		lineageTag: bc35fd82-c276-49fb-9070-00015bb212df
		summarizeBy: sum
		sourceColumn: ggr_lb_90d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column aposta_total_1d
		dataType: double
		lineageTag: f2cc48b4-0e5b-4ee8-afb7-416b7c34abef
		summarizeBy: sum
		sourceColumn: aposta_total_1d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column aposta_total_3d
		dataType: double
		lineageTag: 571361c7-c28a-4852-a7e0-3ae552644f1a
		summarizeBy: sum
		sourceColumn: aposta_total_3d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column aposta_total_7d
		dataType: double
		lineageTag: 3afe8b9a-0b2e-43a6-8ba9-499ff1fccb26
		summarizeBy: sum
		sourceColumn: aposta_total_7d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column aposta_total_15d
		dataType: double
		lineageTag: df253b42-0b53-4cd3-8540-34a8db6f5aaa
		summarizeBy: sum
		sourceColumn: aposta_total_15d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column aposta_total_30d
		dataType: double
		lineageTag: 167726ca-0adf-44ec-a6de-74d827212f4d
		summarizeBy: sum
		sourceColumn: aposta_total_30d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column aposta_total_60d
		dataType: double
		lineageTag: 224012d7-8d8c-4027-b954-277a5ae4c6de
		summarizeBy: sum
		sourceColumn: aposta_total_60d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column aposta_total_90d
		dataType: double
		lineageTag: 4d95eb87-f809-472a-8935-00711841ee02
		summarizeBy: sum
		sourceColumn: aposta_total_90d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ggr_proj_1d
		dataType: double
		lineageTag: ae7093e9-e517-4e00-ba5a-8b5c841a1352
		summarizeBy: sum
		sourceColumn: ggr_proj_1d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ggr_proj_3d
		dataType: double
		lineageTag: 4ef72ab6-9bb6-4d6f-b7c7-be3a807d8524
		summarizeBy: sum
		sourceColumn: ggr_proj_3d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ggr_proj_7d
		dataType: double
		lineageTag: 35db9b17-fc55-4467-87af-bc4bcf8c7f5f
		summarizeBy: sum
		sourceColumn: ggr_proj_7d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ggr_proj_15d
		dataType: double
		lineageTag: 132de489-55eb-43c5-9548-49c929a67199
		summarizeBy: sum
		sourceColumn: ggr_proj_15d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ggr_proj_30d
		dataType: double
		lineageTag: 214d8d43-b677-472e-b914-46ce617c095a
		summarizeBy: sum
		sourceColumn: ggr_proj_30d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ggr_proj_60d
		dataType: double
		lineageTag: 36d7a925-7b43-409c-8cdc-7a6074d738e4
		summarizeBy: sum
		sourceColumn: ggr_proj_60d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ggr_proj_90d
		dataType: double
		lineageTag: e763df13-9ad7-47b0-afcd-51f7d655d9de
		summarizeBy: sum
		sourceColumn: ggr_proj_90d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ggr_real_1d
		dataType: double
		lineageTag: 3fe5e5f6-7b27-41eb-a509-d0b63eda5f20
		summarizeBy: sum
		sourceColumn: ggr_real_1d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ggr_real_3d
		dataType: double
		lineageTag: 783ba443-e3e2-4da4-a2a4-859d88f1d0ec
		summarizeBy: sum
		sourceColumn: ggr_real_3d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ggr_real_7d
		dataType: double
		lineageTag: ea8fc1d2-af7d-4524-bd9a-9c64a28b4190
		summarizeBy: sum
		sourceColumn: ggr_real_7d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ggr_real_15d
		dataType: double
		lineageTag: f1ab2892-78ec-47c4-b2ae-c30f5ebda388
		summarizeBy: sum
		sourceColumn: ggr_real_15d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ggr_real_30d
		dataType: double
		lineageTag: cae028be-e852-4d3d-9d57-06404353fbc0
		summarizeBy: sum
		sourceColumn: ggr_real_30d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ggr_real_60d
		dataType: double
		lineageTag: 2f893ef7-3a52-4c64-b2d5-ec17b8f6a501
		summarizeBy: sum
		sourceColumn: ggr_real_60d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ggr_real_90d
		dataType: double
		lineageTag: 93bf48a0-1b3f-467e-adac-79909ac81f04
		summarizeBy: sum
		sourceColumn: ggr_real_90d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column hora_atualizacao
		dataType: dateTime
		formatString: General Date
		lineageTag: d0644b39-0851-4972-99d5-7535e17981c4
		summarizeBy: none
		sourceColumn: hora_atualizacao

		variation Variation
			isDefault
			relationship: 41b2652b-0b75-4256-ad32-3d164e3d3399
			defaultHierarchy: LocalDateTable_8af22df3-65b1-4e25-8db2-b79b1bcd5403.'Hierarquia de datas'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SemanaAno = WEEKNUM(bd_timeline[data_base], 2)
		formatString: 0
		lineageTag: 55c397fb-0a48-46b5-bc59-c7c81881648f
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column data_base_replica = bd_timeline[data_base]
		formatString: General Date
		lineageTag: 831086b6-d0f4-4ff7-ada5-473b5e560de8
		summarizeBy: none

		variation Variation
			isDefault
			relationship: b7619dbd-ada5-4324-a5e9-cc28fdb88fe2
			defaultHierarchy: LocalDateTable_f6d625a2-308b-403d-958a-76c6e6db915e.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column qtd_depositantes_120d
		dataType: int64
		formatString: 0
		lineageTag: 8150bbe8-10fe-4bc2-b9d0-c14ff0d458c5
		summarizeBy: sum
		sourceColumn: qtd_depositantes_120d

		annotation SummarizationSetBy = Automatic

	column qtd_depositantes_150d
		dataType: int64
		formatString: 0
		lineageTag: 966b88c0-f060-46d7-8827-13f3fdbd573a
		summarizeBy: sum
		sourceColumn: qtd_depositantes_150d

		annotation SummarizationSetBy = Automatic

	column qtd_depositantes_180d
		dataType: int64
		formatString: 0
		lineageTag: 4bce6fb7-4cdc-496b-b44d-2a98029ff616
		summarizeBy: sum
		sourceColumn: qtd_depositantes_180d

		annotation SummarizationSetBy = Automatic

	column qtd_depositantes_210d
		dataType: int64
		formatString: 0
		lineageTag: c5dae541-5b02-471d-b0de-1006ce8866ad
		summarizeBy: sum
		sourceColumn: qtd_depositantes_210d

		annotation SummarizationSetBy = Automatic

	column qtd_apostadores_120d
		dataType: int64
		formatString: 0
		lineageTag: 0f826189-8bc9-46e6-8caa-645e0f233685
		summarizeBy: sum
		sourceColumn: qtd_apostadores_120d

		annotation SummarizationSetBy = Automatic

	column qtd_apostadores_150d
		dataType: int64
		formatString: 0
		lineageTag: c6379b1b-7ee2-40c3-b707-6a94495765c3
		summarizeBy: sum
		sourceColumn: qtd_apostadores_150d

		annotation SummarizationSetBy = Automatic

	column qtd_apostadores_180d
		dataType: int64
		formatString: 0
		lineageTag: f66bb5ef-c3e8-4e49-ae82-1d6789da6c37
		summarizeBy: sum
		sourceColumn: qtd_apostadores_180d

		annotation SummarizationSetBy = Automatic

	column qtd_apostadores_210d
		dataType: int64
		formatString: 0
		lineageTag: 909ff559-ebff-44c3-82b3-d5766b86b9cf
		summarizeBy: sum
		sourceColumn: qtd_apostadores_210d

		annotation SummarizationSetBy = Automatic

	column deposito_120d
		dataType: double
		lineageTag: d1d647fb-cd94-48bd-87fb-16e3c0f50167
		summarizeBy: sum
		sourceColumn: deposito_120d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column deposito_150d
		dataType: double
		lineageTag: eccc39f5-e386-4834-b272-21a8aa151f97
		summarizeBy: sum
		sourceColumn: deposito_150d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column deposito_180d
		dataType: double
		lineageTag: af3dbdd1-fd0e-4efc-9559-09603714fc7a
		summarizeBy: sum
		sourceColumn: deposito_180d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column deposito_210d
		dataType: double
		lineageTag: c3232413-9659-4876-a898-aecef0d64580
		summarizeBy: sum
		sourceColumn: deposito_210d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column aposta_cassino_120d
		dataType: double
		lineageTag: 540da5b1-32fa-49ae-8d81-106a5c6b38cb
		summarizeBy: sum
		sourceColumn: aposta_cassino_120d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column aposta_cassino_150d
		dataType: double
		lineageTag: aac87973-eb78-461f-ad98-b4872f4c21e4
		summarizeBy: sum
		sourceColumn: aposta_cassino_150d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column aposta_cassino_180d
		dataType: double
		lineageTag: aa30b6ef-0a9b-4283-b640-1f4898296dcb
		summarizeBy: sum
		sourceColumn: aposta_cassino_180d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column aposta_cassino_210d
		dataType: double
		lineageTag: 325bbd8e-4108-4cd5-9916-5c31bc7659dd
		summarizeBy: sum
		sourceColumn: aposta_cassino_210d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column premio_cassino_120d
		dataType: double
		lineageTag: 53f26720-e3db-442d-bf93-84d4f96a8f7b
		summarizeBy: sum
		sourceColumn: premio_cassino_120d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column premio_cassino_150d
		dataType: double
		lineageTag: d737f70d-2cd2-4452-8cbe-fdf7b1f177dc
		summarizeBy: sum
		sourceColumn: premio_cassino_150d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column premio_cassino_180d
		dataType: double
		lineageTag: 07c503d6-52e9-496c-9415-e12041290f41
		summarizeBy: sum
		sourceColumn: premio_cassino_180d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column premio_cassino_210d
		dataType: double
		lineageTag: 214bac34-ea3c-4ddf-98d9-175616a3b005
		summarizeBy: sum
		sourceColumn: premio_cassino_210d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ggr_cassino_120d
		dataType: double
		lineageTag: 705ea30d-b1ed-471e-bd0d-48b9c05b1eae
		summarizeBy: sum
		sourceColumn: ggr_cassino_120d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ggr_cassino_150d
		dataType: double
		lineageTag: 91925c0e-15f6-4119-a734-66cefac66d0d
		summarizeBy: sum
		sourceColumn: ggr_cassino_150d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ggr_cassino_180d
		dataType: double
		lineageTag: 462bccf4-20d3-4fb8-90d2-f1c2e568582d
		summarizeBy: sum
		sourceColumn: ggr_cassino_180d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ggr_cassino_210d
		dataType: double
		lineageTag: cda14d58-1ad1-4b63-ab7f-be110ed10d78
		summarizeBy: sum
		sourceColumn: ggr_cassino_210d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column aposta_sportsbook_120d
		dataType: double
		lineageTag: 604d8001-9ae9-478d-9ba9-313582dd060b
		summarizeBy: sum
		sourceColumn: aposta_sportsbook_120d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column aposta_sportsbook_150d
		dataType: double
		lineageTag: eb997b90-a249-4259-85fc-41ac8042ae54
		summarizeBy: sum
		sourceColumn: aposta_sportsbook_150d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column aposta_sportsbook_180d
		dataType: double
		lineageTag: cff13ca0-b702-4474-95d7-40cc2d4a6e23
		summarizeBy: sum
		sourceColumn: aposta_sportsbook_180d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column aposta_sportsbook_210d
		dataType: double
		lineageTag: 3c70de6a-85f2-4f94-90f4-359375224ad5
		summarizeBy: sum
		sourceColumn: aposta_sportsbook_210d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column premio_sportsbook_120d
		dataType: double
		lineageTag: a3dfdb9e-3eef-4f1d-9da5-45133195babb
		summarizeBy: sum
		sourceColumn: premio_sportsbook_120d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column premio_sportsbook_150d
		dataType: double
		lineageTag: f176c58a-c02e-42e5-8646-4e3c616c9de3
		summarizeBy: sum
		sourceColumn: premio_sportsbook_150d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column premio_sportsbook_180d
		dataType: double
		lineageTag: 20711c0a-d79d-4c5a-a99c-9bca0c7082ea
		summarizeBy: sum
		sourceColumn: premio_sportsbook_180d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column premio_sportsbook_210d
		dataType: double
		lineageTag: c2f69a43-a14d-4396-a0a2-2e49c1453bb7
		summarizeBy: sum
		sourceColumn: premio_sportsbook_210d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ggr_sportsbook_120d
		dataType: double
		lineageTag: 6ca8e157-e947-47ed-b2c4-23a104f33c00
		summarizeBy: sum
		sourceColumn: ggr_sportsbook_120d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ggr_sportsbook_150d
		dataType: double
		lineageTag: c88f77ac-3166-4663-ae34-94e0ac071727
		summarizeBy: sum
		sourceColumn: ggr_sportsbook_150d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ggr_sportsbook_180d
		dataType: double
		lineageTag: 7d7d98ac-bc00-4127-a0b4-c0880ec94917
		summarizeBy: sum
		sourceColumn: ggr_sportsbook_180d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ggr_sportsbook_210d
		dataType: double
		lineageTag: b0db6398-6c31-4f17-b0fc-c743118bd535
		summarizeBy: sum
		sourceColumn: ggr_sportsbook_210d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column aposta_lb_120d
		dataType: double
		lineageTag: c18960a8-3125-4d6b-9d85-1b907c64cc52
		summarizeBy: sum
		sourceColumn: aposta_lb_120d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column aposta_lb_150d
		dataType: double
		lineageTag: 8a098512-f1ff-4267-8d99-afc5cf547ce2
		summarizeBy: sum
		sourceColumn: aposta_lb_150d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column aposta_lb_180d
		dataType: double
		lineageTag: dfeafc3f-8041-47a4-9c57-1841c93ff1b6
		summarizeBy: sum
		sourceColumn: aposta_lb_180d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column aposta_lb_210d
		dataType: double
		lineageTag: e2b297b1-1e1d-4410-b87a-c329f8b47582
		summarizeBy: sum
		sourceColumn: aposta_lb_210d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column premio_lb_120d
		dataType: double
		lineageTag: 70be4987-ef6a-46ba-b721-fd3b969cc56e
		summarizeBy: sum
		sourceColumn: premio_lb_120d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column premio_lb_150d
		dataType: double
		lineageTag: 7a55866e-7d4e-4e33-b8c2-bc8f242af76c
		summarizeBy: sum
		sourceColumn: premio_lb_150d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column premio_lb_180d
		dataType: double
		lineageTag: 5faaa89a-4b22-4ce3-90c6-a23d55c73948
		summarizeBy: sum
		sourceColumn: premio_lb_180d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column premio_lb_210d
		dataType: double
		lineageTag: f297afc3-571e-4ebd-860f-7f2591b6d965
		summarizeBy: sum
		sourceColumn: premio_lb_210d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ggr_lb_120d
		dataType: double
		lineageTag: 4a2c3232-87b4-468f-b3e8-df70164c1697
		summarizeBy: sum
		sourceColumn: ggr_lb_120d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ggr_lb_150d
		dataType: double
		lineageTag: b7f3f7cf-c8a3-483e-b6ff-c950fe5dd8b2
		summarizeBy: sum
		sourceColumn: ggr_lb_150d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ggr_lb_180d
		dataType: double
		lineageTag: 727b286a-ca7c-488c-aad5-d88f8109e309
		summarizeBy: sum
		sourceColumn: ggr_lb_180d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ggr_lb_210d
		dataType: double
		lineageTag: e84c1057-c1db-4067-b3d0-37ee7dee3021
		summarizeBy: sum
		sourceColumn: ggr_lb_210d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column aposta_total_120d
		dataType: double
		lineageTag: b02bd954-784d-43cd-859b-e97e0d9da69a
		summarizeBy: sum
		sourceColumn: aposta_total_120d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column aposta_total_150d
		dataType: double
		lineageTag: 36034cd3-fdbe-4a90-94e6-c3402972851f
		summarizeBy: sum
		sourceColumn: aposta_total_150d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column aposta_total_180d
		dataType: double
		lineageTag: 66f5b62d-5234-4af5-9e30-8414e418b6e5
		summarizeBy: sum
		sourceColumn: aposta_total_180d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column aposta_total_210d
		dataType: double
		lineageTag: 9d7496d1-246a-4b14-a539-60f66c88a472
		summarizeBy: sum
		sourceColumn: aposta_total_210d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ggr_proj_120d
		dataType: double
		lineageTag: 3ac62c32-7ac4-48e1-bda5-dcb7787077b4
		summarizeBy: sum
		sourceColumn: ggr_proj_120d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ggr_proj_150d
		dataType: double
		lineageTag: 24067c43-96b9-43fc-8ae0-938364682005
		summarizeBy: sum
		sourceColumn: ggr_proj_150d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ggr_proj_180d
		dataType: double
		lineageTag: 42682f83-2371-4e6a-b6d1-35eaff265a46
		summarizeBy: sum
		sourceColumn: ggr_proj_180d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ggr_proj_210d
		dataType: double
		lineageTag: abd0cb45-e2cb-43f6-bd83-49f76e4b1243
		summarizeBy: sum
		sourceColumn: ggr_proj_210d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ggr_real_120d
		dataType: double
		lineageTag: 1bb29e2f-2e81-43b6-810e-5e58b71e2b28
		summarizeBy: sum
		sourceColumn: ggr_real_120d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ggr_real_150d
		dataType: double
		lineageTag: 64988100-5258-4fd1-88d5-66bf348385f8
		summarizeBy: sum
		sourceColumn: ggr_real_150d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ggr_real_180d
		dataType: double
		lineageTag: bc4d5d3a-3662-4cd7-9622-025a5b05b19d
		summarizeBy: sum
		sourceColumn: ggr_real_180d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ggr_real_210d
		dataType: double
		lineageTag: 290abfa2-0972-4b7a-a28c-71a1d7bd8c33
		summarizeBy: sum
		sourceColumn: ggr_real_210d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ngr_1d
		dataType: double
		lineageTag: de379615-9eda-4172-8e04-f12998e72f33
		summarizeBy: sum
		sourceColumn: ngr_1d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ngr_3d
		dataType: double
		lineageTag: 6438738b-572a-4bbe-883c-520a2a74c09c
		summarizeBy: sum
		sourceColumn: ngr_3d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ngr_7d
		dataType: double
		lineageTag: 0bbb0fcc-cb97-4b15-87cd-2339e7774cb8
		summarizeBy: sum
		sourceColumn: ngr_7d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ngr_15d
		dataType: double
		lineageTag: 69ed1fec-9c10-4451-93f8-4c5e49684e72
		summarizeBy: sum
		sourceColumn: ngr_15d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ngr_30d
		dataType: double
		lineageTag: 02c47a92-fd0a-400b-a9f7-33e488735ed4
		summarizeBy: sum
		sourceColumn: ngr_30d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ngr_60d
		dataType: double
		lineageTag: 4a8e6d6f-2ffc-482b-a230-a93e5ba7e21c
		summarizeBy: sum
		sourceColumn: ngr_60d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ngr_90d
		dataType: double
		lineageTag: b5ba58ef-d052-4915-beb7-60a9e3d0cff8
		summarizeBy: sum
		sourceColumn: ngr_90d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ngr_120d
		dataType: double
		lineageTag: b533f445-013b-4e89-9167-adb62d4c4e8c
		summarizeBy: sum
		sourceColumn: ngr_120d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ngr_150d
		dataType: double
		lineageTag: efb3a634-b94e-4278-9167-caa99e14824e
		summarizeBy: sum
		sourceColumn: ngr_150d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ngr_180d
		dataType: double
		lineageTag: bf7ee69c-7c3f-4195-92c4-5e8d618b4376
		summarizeBy: sum
		sourceColumn: ngr_180d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ngr_210d
		dataType: double
		lineageTag: fb47b2f5-2b56-4074-8e55-fab9093fa745
		summarizeBy: sum
		sourceColumn: ngr_210d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition bd_timeline = m
		mode: import
		source =
				let
				    // 1. Conecta diretamente na subpasta resumo_executivo
				    Source = AzureStorage.DataLake(
				        "https://kplakehouse.dfs.core.windows.net/gold/timeline",
				        [HierarchicalNavigation = true]
				    ),
				
				    // 2. Filtra apenas arquivos .parquet
				    ParquetFiles = Table.SelectRows(
				        Source,
				        each [Extension] = ".parquet"
				    ),
				
				    // 3. Pega o primeiro arquivo da lista
				    FirstFile = ParquetFiles{0}[Content],
				
				    // 4. Carrega o Parquet como uma tabela
				    Data = Parquet.Document(FirstFile)
				in
				    Data

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

