table bd_users_dimensao_reduzida
	lineageTag: 3a7ed785-8db6-4ee9-afb3-f9c7b6859418

	column 'Nome da Origem'
		dataType: string
		lineageTag: 0df421d7-da21-42c6-bab1-a6e799a42b53
		summarizeBy: none
		sourceColumn: Nome da Origem

		annotation SummarizationSetBy = Automatic

	column userid
		dataType: string
		lineageTag: 6343f6ca-6d11-4324-a482-323694d1c00e
		summarizeBy: none
		sourceColumn: userid

		annotation SummarizationSetBy = Automatic

	column dt_ftd_brt
		dataType: dateTime
		formatString: Long Date
		lineageTag: 86af9338-f7dd-4ce1-a74e-53f340d99d3e
		summarizeBy: none
		sourceColumn: dt_ftd_brt

		variation Variation
			isDefault
			relationship: a2468331-69df-41bc-92de-7bb976688d42
			defaultHierarchy: LocalDateTable_bae50e4c-002f-4b00-b96d-ad74213ad9b8.'Hierarquia de datas'

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column dt_criacao_brt
		dataType: dateTime
		formatString: General Date
		lineageTag: c6820a61-b27a-499f-ad49-3f46cb884208
		summarizeBy: none
		sourceColumn: dt_criacao_brt

		variation Variation
			isDefault
			relationship: 2d26e2a0-a8fc-4941-919e-27bfe992758a
			defaultHierarchy: LocalDateTable_fce94ea7-b4c9-4e8c-a8be-1855be6e183c.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column genero
		dataType: string
		lineageTag: 59c66a75-963b-4f5d-ab75-2f2c1701bc1a
		summarizeBy: none
		sourceColumn: genero

		annotation SummarizationSetBy = Automatic

	column utm_source
		dataType: string
		lineageTag: 05513619-f313-4319-8381-3a9808027154
		summarizeBy: none
		sourceColumn: utm_source

		annotation SummarizationSetBy = Automatic

	column utm_campaign
		dataType: string
		lineageTag: b8c1043f-e6db-4428-a74a-539c60197650
		summarizeBy: none
		sourceColumn: utm_campaign

		annotation SummarizationSetBy = Automatic

	column utm_medium
		dataType: string
		lineageTag: 7b782d1e-093f-4ef3-8ee1-30c582d11261
		summarizeBy: none
		sourceColumn: utm_medium

		annotation SummarizationSetBy = Automatic

	column utm_content
		dataType: string
		lineageTag: ebab21aa-619c-40e2-b26a-bf4990c3890d
		summarizeBy: none
		sourceColumn: utm_content

		annotation SummarizationSetBy = Automatic

	column utm_term
		dataType: string
		lineageTag: e8018d78-aa21-42b0-a874-502bc8557a6e
		summarizeBy: none
		sourceColumn: utm_term

		annotation SummarizationSetBy = Automatic

	column codigo_cidade
		dataType: string
		lineageTag: 311f488e-ae72-4aea-93b7-763b77f163c4
		summarizeBy: none
		sourceColumn: codigo_cidade

		annotation SummarizationSetBy = Automatic

	column cidade
		dataType: string
		lineageTag: 9b558fb5-f729-48f8-86a0-cda5d82124b9
		summarizeBy: none
		sourceColumn: cidade

		annotation SummarizationSetBy = Automatic

	column idade_anos
		dataType: int64
		formatString: 0
		lineageTag: ca30c4b8-69ae-4837-98d5-74a668e7f64b
		summarizeBy: sum
		sourceColumn: idade_anos

		annotation SummarizationSetBy = Automatic

	column faixa_idade
		dataType: string
		lineageTag: 5f45b281-512f-4e7b-a1d9-723e4bac173a
		summarizeBy: none
		sourceColumn: faixa_idade

		annotation SummarizationSetBy = Automatic

	column influencer
		dataType: int64
		formatString: 0
		lineageTag: 3f79c0da-0a19-411f-8053-62fe3d059ee0
		summarizeBy: sum
		sourceColumn: influencer

		annotation SummarizationSetBy = Automatic

	column admin
		dataType: int64
		formatString: 0
		lineageTag: 06599f06-809b-4b76-8351-f05eec7c01f5
		summarizeBy: sum
		sourceColumn: admin

		annotation SummarizationSetBy = Automatic

	column migrado
		dataType: int64
		formatString: 0
		lineageTag: 3b9f4004-28f9-49df-8956-5f1c1854aa1f
		summarizeBy: sum
		sourceColumn: migrado

		annotation SummarizationSetBy = Automatic

	column primeiro_nome
		dataType: string
		lineageTag: c727ac94-cb7e-4ee9-acd3-24ad94c2af62
		summarizeBy: none
		sourceColumn: primeiro_nome

		annotation SummarizationSetBy = Automatic

	column Dia_Semana_Num = WEEKDAY ( [dt_ftd_brt], 2 )
		formatString: 0
		lineageTag: 0e165b4a-795a-4044-b4a5-3d7f4e488432
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column dia_da_semana =
			
			SWITCH (
			    [Dia_Semana_Num],
			    1, "Segunda",
			    2, "Terça",
			    3, "Quarta",
			    4, "Quinta",
			    5, "Sexta",
			    6, "Sábado",
			    7, "Domingo"
			)
		lineageTag: 62e86c69-b34c-4546-b5fb-e82aa7b0f76c
		summarizeBy: none
		sortByColumn: Dia_Semana_Num

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Hora_FTD_Formatada = FORMAT(HOUR('bd_users_dimensao_reduzida'[dt_ftd_brt]), "00") & ":00"
		lineageTag: 16b9de7f-b9ec-4772-82a2-823fec62f549
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column ano_semana_dimensao = ```
			
			VAR numSemana = WEEKNUM ( [dt_ftd_brt], 2 )                
			RETURN
			YEAR ( [dt_ftd_brt] ) & "-" & FORMAT ( numSemana, "00" )
			
			```
		lineageTag: f9103478-1545-4d25-8f53-06fd9a139306
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Bloco_Horario_FTD = ```
			
			VAR h = HOUR ( 'bd_users_dimensao_reduzida'[dt_ftd_brt] )
			RETURN
			    SWITCH (
			        TRUE(),
			        h < 6,          "Madrugada (00h-06h)",
			        h < 12,         "Manhã (06h-12h)",
			        h < 18,         "Tarde (12h-18h)",
			                        "Noite (18h-23h)"
			    )
			
			```
		lineageTag: 3703b1bc-ae69-44a8-af49-6daff021e41c
		summarizeBy: none
		sortByColumn: order_bloco_ftd

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column order_bloco_ftd = ```
			
			VAR h = HOUR ( 'bd_users_dimensao_reduzida'[dt_ftd_brt] )
			RETURN
			    SWITCH (
			        TRUE(),
			        h < 6,          1,
			        h < 12,         2,
			        h < 18,         3,
			                        4
			    )
			
			```
		formatString: 0
		lineageTag: 955e4ef5-dba4-4c3f-9727-08648103664f
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column SemanaAnoDim = WEEKNUM(bd_users_dimensao_reduzida[dt_ftd_brt], 2)
		formatString: 0
		lineageTag: 0ad91624-ec8c-4d4e-bab3-6fbd41e87d2d
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Hora_Created_Formatada = FORMAT(HOUR('bd_users_dimensao_reduzida'[dt_criacao_brt]), "00") & ":00"
		lineageTag: 6001a2e9-0aae-4f1f-b018-927a85a8f185
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Dia_Semana_Num_Created = WEEKDAY ( [dt_criacao_brt], 2 )
		formatString: 0
		lineageTag: 11df7064-88ca-4e5c-ad51-7954b5aea717
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column dia_da_semana_created =
			
			SWITCH (
			    [Dia_Semana_Num_Created],
			    1, "Segunda",
			    2, "Terça",
			    3, "Quarta",
			    4, "Quinta",
			    5, "Sexta",
			    6, "Sábado",
			    7, "Domingo"
			)
		lineageTag: 59e02dca-64b2-4376-93fc-43c779184970
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column data_replica = bd_users_dimensao_reduzida[dt_ftd_brt]
		formatString: General Date
		lineageTag: 634fc838-1c7d-4e3c-959f-0116a01416a0
		summarizeBy: none

		variation Variation
			isDefault
			relationship: efaa32c5-671f-4395-a8c8-4aec5bba653b
			defaultHierarchy: LocalDateTable_1e1479ce-99c8-46f6-ac80-d0ebe90e061c.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	partition bd_users_dimensao_reduzida = m
		mode: import
		source =
				let
				    Fonte = AzureStorage.DataLake("https://kplakehouse.dfs.core.windows.net/gold/users_dimensao_reduzida"),
				    #"Linhas Filtradas" = Table.SelectRows(Fonte, each ([Extension] = ".parquet")),
				    #"Arquivos Ocultos Filtrados1" = Table.SelectRows(#"Linhas Filtradas", each [Attributes]?[Hidden]? <> true),
				    #"Invocar Função Personalizada1" = Table.AddColumn(#"Arquivos Ocultos Filtrados1", "Transformar Arquivo (12)", each #"Transformar Arquivo (12)"([Content])),
				    #"Colunas Renomeadas1" = Table.RenameColumns(#"Invocar Função Personalizada1", {"Name", "Nome da Origem"}),
				    #"Outras Colunas Removidas1" = Table.SelectColumns(#"Colunas Renomeadas1", {"Nome da Origem", "Transformar Arquivo (12)"}),
				    #"Coluna de Tabela Expandida1" = Table.ExpandTableColumn(#"Outras Colunas Removidas1", "Transformar Arquivo (12)", Table.ColumnNames(#"Transformar Arquivo (12)"(#"Arquivo de Amostra (12)"))),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Coluna de Tabela Expandida1",{{"Nome da Origem", type text}, {"userid", type text}, {"dt_ftd_brt", type any}, {"dt_criacao_brt", type datetime}, {"genero", type any}, {"utm_source", type text}, {"utm_campaign", type text}, {"utm_medium", type text}, {"utm_content", type text}, {"utm_term", type text}, {"codigo_cidade", type any}, {"cidade", type any}, {"idade_anos", Int64.Type}, {"faixa_idade", type text}, {"influencer", Int64.Type}, {"admin", Int64.Type}, {"migrado", Int64.Type}, {"primeiro_nome", type text}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

