table dim_users
	lineageTag: 467d964a-7bc5-4b80-b9fb-2c54a1103e2b

	column userid
		dataType: string
		lineageTag: 96dfdb0d-3696-43d1-bd0b-a86a811e42a2
		summarizeBy: none
		sourceColumn: userid

		annotation SummarizationSetBy = Automatic

	column data
		dataType: dateTime
		formatString: Long Date
		lineageTag: f62e7b46-2210-43a6-a19e-181a46774f90
		summarizeBy: none
		sourceColumn: data

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column usuarios_migrados
		dataType: int64
		formatString: 0
		lineageTag: d616387f-29a3-410b-ac16-da0d3201f6e7
		summarizeBy: sum
		sourceColumn: usuarios_migrados

		annotation SummarizationSetBy = Automatic

	column tier_l30d
		dataType: int64
		formatString: 0
		lineageTag: d562ab20-f818-44b8-89bb-5e95eebbdbbf
		summarizeBy: sum
		sourceColumn: tier_l30d

		annotation SummarizationSetBy = Automatic

	column tier_high_lifetime
		dataType: int64
		formatString: 0
		lineageTag: 54095c09-994b-4f33-a700-937a866cfcb6
		summarizeBy: sum
		sourceColumn: tier_high_lifetime

		annotation SummarizationSetBy = Automatic

	column hora_atualizacao
		dataType: dateTime
		formatString: General Date
		lineageTag: b6392d64-7be7-40d5-a970-461088230c2a
		summarizeBy: none
		sourceColumn: hora_atualizacao

		variation Variation
			isDefault
			relationship: c23cbee5-bbac-4c00-b09b-aa3112c7f48f
			defaultHierarchy: LocalDateTable_9fba1887-4ad0-4a75-9bb2-5f10ed273e09.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column data_replica = dim_users[data]
		formatString: General Date
		lineageTag: 01111b6d-96e5-44ca-8364-6982b5be153b
		summarizeBy: none

		variation Variation
			isDefault
			relationship: bc7babab-e296-4f18-88b4-3eee2b952f76
			defaultHierarchy: LocalDateTable_4bf028e6-b8ad-49d1-9de9-3f0aa0d42643.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column ano_semana = WEEKNUM(dim_users[data], 2)
		formatString: 0
		lineageTag: 104e3496-7b95-489e-9d92-676a0fbe10c8
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column utm_source_cadastro
		dataType: string
		lineageTag: 84ee3d0b-4ff2-4c9a-be60-e50a2fedc07c
		summarizeBy: none
		sourceColumn: utm_source_cadastro

		annotation SummarizationSetBy = Automatic

	column utm_medium_cadastro
		dataType: string
		lineageTag: 3f032f49-10ae-4c80-ac59-75285cca373e
		summarizeBy: none
		sourceColumn: utm_medium_cadastro

		annotation SummarizationSetBy = Automatic

	column utm_campaign_cadastro
		dataType: string
		lineageTag: 0f91118e-756c-46a8-8ad2-d1a2d7c63a3a
		summarizeBy: none
		sourceColumn: utm_campaign_cadastro

		annotation SummarizationSetBy = Automatic

	column utm_content_cadastro
		dataType: string
		lineageTag: 6c932bf8-4394-428b-9414-49416b049272
		summarizeBy: none
		sourceColumn: utm_content_cadastro

		annotation SummarizationSetBy = Automatic

	column utm_term_cadastro
		dataType: string
		lineageTag: 79d914cb-9d3d-4e5f-8375-de3db8c48044
		summarizeBy: none
		sourceColumn: utm_term_cadastro

		annotation SummarizationSetBy = Automatic

	column utm_source_deposito
		dataType: string
		lineageTag: 55f549c0-c4cb-4a7b-9f25-2d4d4a4c601d
		summarizeBy: none
		sourceColumn: utm_source_deposito

		annotation SummarizationSetBy = Automatic

	column utm_medium_deposito
		dataType: string
		lineageTag: fb05e91e-e521-4a68-8884-587e0b10f063
		summarizeBy: none
		sourceColumn: utm_medium_deposito

		annotation SummarizationSetBy = Automatic

	column utm_campaign_deposito
		dataType: string
		lineageTag: 39f21460-7964-40f4-891e-6dab7a797058
		summarizeBy: none
		sourceColumn: utm_campaign_deposito

		annotation SummarizationSetBy = Automatic

	column utm_content_deposito
		dataType: string
		lineageTag: 2dfa36fb-b18f-4858-8f61-d1b49bf9c49c
		summarizeBy: none
		sourceColumn: utm_content_deposito

		annotation SummarizationSetBy = Automatic

	column utm_term_deposito
		dataType: string
		lineageTag: 8ebf3e50-0b59-44c3-9ad8-6a4d9a66f3f9
		summarizeBy: none
		sourceColumn: utm_term_deposito

		annotation SummarizationSetBy = Automatic

	column apostas_aberto
		dataType: string
		lineageTag: 9691f571-479b-4ee8-8795-9d4fcf261074
		summarizeBy: none
		sourceColumn: apostas_aberto

		annotation SummarizationSetBy = Automatic

	partition dim_users = m
		mode: import
		source =
				let
				    Fonte = AzureStorage.DataLake("https://kplakehouse.dfs.core.windows.net/gold/resumo_executivo_por_user"),
				    #"Linhas Filtradas" = Table.SelectRows(Fonte, each ([Extension] = ".parquet")),
				    #"Arquivos Ocultos Filtrados1" = Table.SelectRows(#"Linhas Filtradas", each [Attributes]?[Hidden]? <> true),
				    #"Invocar Função Personalizada1" = Table.AddColumn(#"Arquivos Ocultos Filtrados1", "Transformar Arquivo (14)", each #"Transformar Arquivo (14)"([Content])),
				    #"Colunas Renomeadas1" = Table.RenameColumns(#"Invocar Função Personalizada1", {"Name", "Nome da Origem"}),
				    #"Outras Colunas Removidas1" = Table.SelectColumns(#"Colunas Renomeadas1", {"Nome da Origem", "Transformar Arquivo (14)"}),
				    #"Coluna de Tabela Expandida1" = Table.ExpandTableColumn(#"Outras Colunas Removidas1", "Transformar Arquivo (14)", Table.ColumnNames(#"Transformar Arquivo (14)"(#"Arquivo de Amostra (14)"))),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Coluna de Tabela Expandida1",{{"Nome da Origem", type text}, {"userid", type text}, {"data", type date}, {"utm_source_cadastro", type text}, {"utm_medium_cadastro", type text}, {"utm_campaign_cadastro", type text}, {"utm_content_cadastro", type text}, {"utm_term_cadastro", type text}, {"utm_source_deposito", type text}, {"utm_medium_deposito", type text}, {"utm_campaign_deposito", type text}, {"utm_content_deposito", type text}, {"utm_term_deposito", type text}, {"usuarios_migrados", Int64.Type}, {"contas_novas", Int64.Type}, {"contas_depositantes", Int64.Type}, {"clientes_ativos", Int64.Type}, {"contas_ftd", Int64.Type}, {"deposito", Int64.Type}, {"qtd_depositos", Int64.Type}, {"qtd_saques", Int64.Type}, {"qtd_aposta_cassino", Int64.Type}, {"qtd_aposta_sportsbook", Int64.Type}, {"qtd_aposta_lb", Int64.Type}, {"saques", Int64.Type}, {"total_vip_proprio", Int64.Type}, {"total_vip_referral", Int64.Type}, {"total_vip_programa", Int64.Type}, {"total_crazy_friday", Int64.Type}, {"migracao_saldo", Int64.Type}, {"ajuste_saldo_manual", Int64.Type}, {"aposta_cassino", type number}, {"aposta_sportsbook", type number}, {"aposta_lb", Int64.Type}, {"premio_cassino", type number}, {"premio_sportsbook", Int64.Type}, {"premio_lb", Int64.Type}, {"ggr_cassino", type number}, {"ggr_sportsbook", type number}, {"ggr_lb", Int64.Type}, {"ngr", type number}, {"reward", type number}, {"premios_freespins", type number}, {"qtd_usuarios_com_premio_freespins", Int64.Type}, {"saldo_conta", type number}, {"hora_atualizacao", type datetime}, {"status_ativo_90d", Int64.Type}, {"media_l30d", type number}, {"tier_l30d", Int64.Type}, {"tier_high_lifetime", Int64.Type}, {"media_high_lifetime", Int64.Type}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Tipo Alterado",{"Nome da Origem", "contas_novas", "contas_depositantes", "clientes_ativos", "contas_ftd", "deposito", "qtd_depositos", "qtd_saques", "qtd_aposta_cassino", "qtd_aposta_sportsbook", "qtd_aposta_lb", "saques", "total_vip_proprio", "total_vip_referral", "total_vip_programa", "total_crazy_friday", "migracao_saldo", "ajuste_saldo_manual", "aposta_cassino", "aposta_sportsbook", "aposta_lb", "premio_cassino", "premio_sportsbook", "premio_lb", "ggr_cassino", "ggr_sportsbook", "ggr_lb", "ngr", "reward", "premios_freespins", "qtd_usuarios_com_premio_freespins", "saldo_conta", "status_ativo_90d", "media_l30d", "media_high_lifetime"}),
				    #"Colunas Reordenadas" = Table.ReorderColumns(#"Colunas Removidas",{"userid", "data", "utm_source_cadastro", "utm_medium_cadastro", "utm_campaign_cadastro", "utm_content_cadastro", "utm_term_cadastro", "utm_source_deposito", "utm_medium_deposito", "utm_campaign_deposito", "utm_content_deposito", "utm_term_deposito","usuarios_migrados", "tier_l30d", "tier_high_lifetime", "hora_atualizacao"})
				in
				    #"Colunas Reordenadas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

