table fato_aposta
	lineageTag: f7c23487-4d18-43ab-a712-4c04655830c4

	column 'Nome da Origem'
		dataType: string
		lineageTag: a2d3e185-eb60-4f7e-b171-f5a36c543941
		summarizeBy: none
		sourceColumn: Nome da Origem

		annotation SummarizationSetBy = Automatic

	column userid
		dataType: string
		lineageTag: 99fcd86e-6cae-4f56-87c2-4f2248ba82be
		summarizeBy: none
		sourceColumn: userid

		annotation SummarizationSetBy = Automatic

	column data
		dataType: dateTime
		formatString: Long Date
		lineageTag: 72ed8aa5-a654-4f8b-91fb-f0356ca69ca7
		summarizeBy: none
		sourceColumn: data

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column aposta_cassino
		dataType: double
		lineageTag: 5355e253-ea3b-4fcc-88ee-aaa0fb2f3456
		summarizeBy: sum
		sourceColumn: aposta_cassino

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column aposta_sportsbook
		dataType: double
		lineageTag: 705f7101-2acb-4e4f-935c-e2292a1bfb12
		summarizeBy: sum
		sourceColumn: aposta_sportsbook

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column aposta_lb
		dataType: int64
		formatString: 0
		lineageTag: 9a8cb593-0053-4c87-b749-7561ebbce6ac
		summarizeBy: sum
		sourceColumn: aposta_lb

		annotation SummarizationSetBy = Automatic

	column aposta_total
		dataType: double
		lineageTag: c554c0f1-de32-465a-a60d-765d14d1aabf
		summarizeBy: sum
		sourceColumn: aposta_total

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column status_ativo_90d
		dataType: int64
		formatString: 0
		lineageTag: 0d6e2d27-613c-4615-8eaf-e113eee9f84e
		summarizeBy: sum
		sourceColumn: status_ativo_90d

		annotation SummarizationSetBy = Automatic

	column media_l30d
		dataType: double
		lineageTag: e0fceae0-2759-4d4d-b2e8-61453d3ad1c2
		summarizeBy: sum
		sourceColumn: media_l30d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column tier_l30d
		dataType: int64
		formatString: 0
		lineageTag: 7017dc06-c864-4131-ae74-056465bea0b6
		summarizeBy: sum
		sourceColumn: tier_l30d

		annotation SummarizationSetBy = Automatic

	column tier_high_lifetime
		dataType: int64
		formatString: 0
		lineageTag: a247228d-1fd5-4341-bdd5-d0643cae6865
		summarizeBy: sum
		sourceColumn: tier_high_lifetime

		annotation SummarizationSetBy = Automatic

	column media_high_lifetime
		dataType: double
		lineageTag: b02e2cd4-ad1a-4d55-ac4e-daee2185b852
		summarizeBy: sum
		sourceColumn: media_high_lifetime

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column hora_atualizacao
		dataType: dateTime
		formatString: General Date
		lineageTag: 7b4fbe07-dd06-4f68-ad65-bc38e2d3bd8e
		summarizeBy: none
		sourceColumn: hora_atualizacao

		variation Variation
			isDefault
			relationship: d4c9c27c-fa3d-43de-a328-e38744a9b069
			defaultHierarchy: LocalDateTable_955f01c9-564e-4cf4-918a-a2d1968de102.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column data_replica = fato_aposta[data]
		formatString: General Date
		lineageTag: 24347e15-0181-4aee-811e-50767f7d209b
		summarizeBy: none

		variation Variation
			isDefault
			relationship: 6a255793-cfe5-4db2-9edc-6b5f6cdfa50f
			defaultHierarchy: LocalDateTable_5d31d01b-13a6-4a06-9c0b-109bddd6ebfe.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column ano_semana = WEEKNUM(fato_aposta[data], 2)
		formatString: 0
		lineageTag: 993aab12-e77c-4868-8a08-f87e2e3392b5
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition fato_aposta = m
		mode: import
		source =
				let
				    Fonte = AzureStorage.DataLake("https://kplakehouse.dfs.core.windows.net/gold/datasets_linkados/valor_apostas"),
				    #"Linhas Filtradas" = Table.SelectRows(Fonte, each ([Extension] = ".parquet")),
				    #"Arquivos Ocultos Filtrados1" = Table.SelectRows(#"Linhas Filtradas", each [Attributes]?[Hidden]? <> true),
				    #"Invocar Função Personalizada1" = Table.AddColumn(#"Arquivos Ocultos Filtrados1", "Transformar Arquivo (35)", each #"Transformar Arquivo (35)"([Content])),
				    #"Colunas Renomeadas1" = Table.RenameColumns(#"Invocar Função Personalizada1", {"Name", "Nome da Origem"}),
				    #"Outras Colunas Removidas1" = Table.SelectColumns(#"Colunas Renomeadas1", {"Nome da Origem", "Transformar Arquivo (35)"}),
				    #"Coluna de Tabela Expandida1" = Table.ExpandTableColumn(#"Outras Colunas Removidas1", "Transformar Arquivo (35)", Table.ColumnNames(#"Transformar Arquivo (35)"(#"Arquivo de Amostra (35)"))),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Coluna de Tabela Expandida1",{{"Nome da Origem", type text}, {"userid", type text}, {"data", type date}, {"aposta_cassino", type number}, {"aposta_sportsbook", type number}, {"aposta_lb", Int64.Type}, {"aposta_total", type number}, {"status_ativo_90d", Int64.Type}, {"media_l30d", type number}, {"tier_l30d", Int64.Type}, {"tier_high_lifetime", Int64.Type}, {"media_high_lifetime", type number}, {"hora_atualizacao", type datetime}}),
				    #"Linhas Filtradas1" = Table.SelectRows(#"Tipo Alterado", each [aposta_total] <> 0)
				in
				    #"Linhas Filtradas1"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

