table fato_ngr
	lineageTag: 9d711d0e-2b49-4d93-b0cc-80c3e1968093

	column 'Nome da Origem'
		dataType: string
		lineageTag: 3881c51f-e704-4978-a5e4-5d124eec2390
		summarizeBy: none
		sourceColumn: Nome da Origem

		annotation SummarizationSetBy = Automatic

	column userid
		dataType: string
		lineageTag: 4af013b1-4926-41bb-b178-219963318bd9
		summarizeBy: none
		sourceColumn: userid

		annotation SummarizationSetBy = Automatic

	column data
		dataType: dateTime
		formatString: Long Date
		lineageTag: 0b6de162-6a68-467a-863a-cf0adb5e91ec
		summarizeBy: none
		sourceColumn: data

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ngr
		dataType: double
		lineageTag: eb24f5db-6328-4898-a282-b86cca6bf3ca
		summarizeBy: sum
		sourceColumn: ngr

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column status_ativo_90d
		dataType: int64
		formatString: 0
		lineageTag: f5e2a48e-e4ea-4f54-bf38-1c232dd73afa
		summarizeBy: sum
		sourceColumn: status_ativo_90d

		annotation SummarizationSetBy = Automatic

	column media_l30d
		dataType: double
		lineageTag: 3b2c7a71-50d2-480e-9cb8-c0ea93ed39cf
		summarizeBy: sum
		sourceColumn: media_l30d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column tier_l30d
		dataType: int64
		formatString: 0
		lineageTag: 8aeb7cf9-40ba-4a42-b6eb-d4ab9fdf4e6a
		summarizeBy: sum
		sourceColumn: tier_l30d

		annotation SummarizationSetBy = Automatic

	column tier_high_lifetime
		dataType: int64
		formatString: 0
		lineageTag: 7a83d7e9-e769-46c4-bd61-bba58fac2c7d
		summarizeBy: sum
		sourceColumn: tier_high_lifetime

		annotation SummarizationSetBy = Automatic

	column media_high_lifetime
		dataType: double
		lineageTag: ee1be56b-d5cb-4d1a-b8d3-2be131583972
		summarizeBy: sum
		sourceColumn: media_high_lifetime

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column hora_atualizacao
		dataType: dateTime
		formatString: General Date
		lineageTag: ea38e42b-3b78-458b-b1c4-391bee4c0a42
		summarizeBy: none
		sourceColumn: hora_atualizacao

		variation Variation
			isDefault
			relationship: 74172862-febb-4665-9ec5-78df5757a0fa
			defaultHierarchy: LocalDateTable_7ff4230c-82f0-4923-a342-abc843a4aa18.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column data_replica = fato_ngr[data]
		formatString: General Date
		lineageTag: a3d7ea5c-1b86-4880-bb07-666ceaaeca63
		summarizeBy: none

		variation Variation
			isDefault
			relationship: 6068fe65-8832-4bf4-bb61-557a24122749
			defaultHierarchy: LocalDateTable_38445ea6-2816-4103-a6fc-304f9fc6b278.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column ano_semana = WEEKNUM(fato_ngr[data], 2)
		formatString: 0
		lineageTag: 578a17ea-b432-4f9f-9792-8ed37e76ad03
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition fato_ngr = m
		mode: import
		source =
				let
				    Fonte = AzureStorage.DataLake("https://kplakehouse.dfs.core.windows.net/gold/datasets_linkados/ngr"),
				    #"Linhas Filtradas" = Table.SelectRows(Fonte, each ([Extension] = ".parquet")),
				    #"Arquivos Ocultos Filtrados1" = Table.SelectRows(#"Linhas Filtradas", each [Attributes]?[Hidden]? <> true),
				    #"Invocar Função Personalizada1" = Table.AddColumn(#"Arquivos Ocultos Filtrados1", "Transformar Arquivo (32)", each #"Transformar Arquivo (32)"([Content])),
				    #"Colunas Renomeadas1" = Table.RenameColumns(#"Invocar Função Personalizada1", {"Name", "Nome da Origem"}),
				    #"Outras Colunas Removidas1" = Table.SelectColumns(#"Colunas Renomeadas1", {"Nome da Origem", "Transformar Arquivo (32)"}),
				    #"Coluna de Tabela Expandida1" = Table.ExpandTableColumn(#"Outras Colunas Removidas1", "Transformar Arquivo (32)", Table.ColumnNames(#"Transformar Arquivo (32)"(#"Arquivo de Amostra (32)"))),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Coluna de Tabela Expandida1",{{"Nome da Origem", type text}, {"userid", type text}, {"data", type date}, {"ngr", type number}, {"status_ativo_90d", Int64.Type}, {"media_l30d", type number}, {"tier_l30d", Int64.Type}, {"tier_high_lifetime", Int64.Type}, {"media_high_lifetime", type number}, {"hora_atualizacao", type datetime}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

