table fato_contas_novas
	lineageTag: 2415225a-bf3f-4792-bd4b-7e4203ae4937

	column userid
		dataType: string
		lineageTag: d4cbb4d4-565c-4548-9786-9af59596c095
		summarizeBy: none
		sourceColumn: userid

		annotation SummarizationSetBy = Automatic

	column data
		dataType: dateTime
		formatString: Long Date
		lineageTag: 1d1e1b4f-96ed-4ad2-9272-513de1beecce
		summarizeBy: none
		sourceColumn: data

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column contas_novas
		dataType: int64
		formatString: 0
		lineageTag: cd6b6442-a02b-404f-a1bf-c4ded71d6abb
		summarizeBy: sum
		sourceColumn: contas_novas

		annotation SummarizationSetBy = Automatic

	column status_ativo_90d
		dataType: int64
		formatString: 0
		lineageTag: 14d86c72-e819-4fc5-80bd-b3bc4909a48c
		summarizeBy: sum
		sourceColumn: status_ativo_90d

		annotation SummarizationSetBy = Automatic

	column media_l30d
		dataType: double
		lineageTag: 0132c969-1cf4-41b6-a691-a8b4d7f43e35
		summarizeBy: sum
		sourceColumn: media_l30d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column tier_l30d
		dataType: int64
		formatString: 0
		lineageTag: 068e0f45-1b6b-4055-9e7f-7da3c894cf0e
		summarizeBy: sum
		sourceColumn: tier_l30d

		annotation SummarizationSetBy = Automatic

	column tier_high_lifetime
		dataType: int64
		formatString: 0
		lineageTag: dd7dd37d-5af4-49f2-ac0a-e45250f1a51d
		summarizeBy: sum
		sourceColumn: tier_high_lifetime

		annotation SummarizationSetBy = Automatic

	column media_high_lifetime
		dataType: double
		lineageTag: 81a2b49f-45a1-4886-803a-5d953c376d08
		summarizeBy: sum
		sourceColumn: media_high_lifetime

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column hora_atualizacao
		dataType: dateTime
		formatString: General Date
		lineageTag: 72c8c8c6-c704-4745-92a7-a0df4468edca
		summarizeBy: none
		sourceColumn: hora_atualizacao

		variation Variation
			isDefault
			relationship: 4105efac-b8f2-4679-b2b6-08ed2224ae8a
			defaultHierarchy: LocalDateTable_622ba333-69ff-4952-8c02-293ebdbe1ad8.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column data_replica = fato_contas_novas[data]
		formatString: General Date
		lineageTag: 2d043fe9-9ec7-4a8a-8917-63f38fbc522f
		summarizeBy: none

		variation Variation
			isDefault
			relationship: bb90645d-7faa-4995-ba39-e4adaecca39d
			defaultHierarchy: LocalDateTable_613ee781-7b87-4c5e-99a5-0cdeaff25f4e.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column ano_semana = WEEKNUM(fato_contas_novas[data], 2)
		formatString: 0
		lineageTag: 1ec423ee-00b3-4ec2-834c-326608a55138
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition fato_contas_novas = m
		mode: import
		source =
				let
				    Fonte = AzureStorage.DataLake("https://kplakehouse.dfs.core.windows.net/gold/datasets_linkados/contas_novas"),
				    #"Linhas Filtradas" = Table.SelectRows(Fonte, each ([Extension] = ".parquet")),
				    #"Arquivos Ocultos Filtrados1" = Table.SelectRows(#"Linhas Filtradas", each [Attributes]?[Hidden]? <> true),
				    #"Invocar Função Personalizada1" = Table.AddColumn(#"Arquivos Ocultos Filtrados1", "Transformar Arquivo (38)", each #"Transformar Arquivo (38)"([Content])),
				    #"Colunas Renomeadas1" = Table.RenameColumns(#"Invocar Função Personalizada1", {"Name", "Nome da Origem"}),
				    #"Outras Colunas Removidas1" = Table.SelectColumns(#"Colunas Renomeadas1", {"Nome da Origem", "Transformar Arquivo (38)"}),
				    #"Coluna de Tabela Expandida1" = Table.ExpandTableColumn(#"Outras Colunas Removidas1", "Transformar Arquivo (38)", Table.ColumnNames(#"Transformar Arquivo (38)"(#"Arquivo de Amostra (38)"))),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Coluna de Tabela Expandida1",{{"Nome da Origem", type text}, {"userid", type text}, {"data", type date}, {"contas_novas", Int64.Type}, {"status_ativo_90d", Int64.Type}, {"media_l30d", type number}, {"tier_l30d", Int64.Type}, {"tier_high_lifetime", Int64.Type}, {"media_high_lifetime", type number}, {"hora_atualizacao", type datetime}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Tipo Alterado",{"Nome da Origem"})
				in
				    #"Colunas Removidas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

