table fato_contas_depositantes
	lineageTag: a34f366d-2daf-4abf-bae2-bb0d0f1c57e5

	column 'Nome da Origem'
		dataType: string
		lineageTag: b9cbd7de-c8de-433e-a340-8035a791d5b5
		summarizeBy: none
		sourceColumn: Nome da Origem

		annotation SummarizationSetBy = Automatic

	column userid
		dataType: string
		lineageTag: 1129cb20-bbfb-4265-a340-6dceda54c8b0
		summarizeBy: none
		sourceColumn: userid

		annotation SummarizationSetBy = Automatic

	column data
		dataType: dateTime
		formatString: Long Date
		lineageTag: fe88a8d6-334d-48f8-9287-0d561471a323
		summarizeBy: none
		sourceColumn: data

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column contas_depositantes
		dataType: int64
		formatString: 0
		lineageTag: 64d9d4e1-ff3e-4a5c-b6f4-8eed8b21ac1f
		summarizeBy: sum
		sourceColumn: contas_depositantes

		annotation SummarizationSetBy = Automatic

	column status_ativo_90d
		dataType: int64
		formatString: 0
		lineageTag: 172aabaf-5a87-4b81-9b63-8169ea4951d9
		summarizeBy: sum
		sourceColumn: status_ativo_90d

		annotation SummarizationSetBy = Automatic

	column media_l30d
		dataType: double
		lineageTag: e716437d-0ae5-4356-9305-1d59544cc4f7
		summarizeBy: sum
		sourceColumn: media_l30d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column tier_l30d
		dataType: int64
		formatString: 0
		lineageTag: 9391a5f1-0d4d-43ce-b24c-6941364e285e
		summarizeBy: sum
		sourceColumn: tier_l30d

		annotation SummarizationSetBy = Automatic

	column tier_high_lifetime
		dataType: int64
		formatString: 0
		lineageTag: 0d47f986-91f4-4cac-a347-60782530505e
		summarizeBy: sum
		sourceColumn: tier_high_lifetime

		annotation SummarizationSetBy = Automatic

	column media_high_lifetime
		dataType: double
		lineageTag: 91ba49a9-003e-46b7-8151-3b2747120e99
		summarizeBy: sum
		sourceColumn: media_high_lifetime

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column hora_atualizacao
		dataType: dateTime
		formatString: General Date
		lineageTag: b86161da-45f9-4daf-ac4f-e05e05092215
		summarizeBy: none
		sourceColumn: hora_atualizacao

		variation Variation
			isDefault
			relationship: cb1e66ae-4cdb-4c24-866c-d57599e546f5
			defaultHierarchy: LocalDateTable_79ac44fc-2d4b-4448-bf42-03d05edc5dc3.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column data_replica = fato_contas_depositantes[data]
		formatString: General Date
		lineageTag: f4862f2c-fb37-44cf-8c16-9af061b3c75d
		summarizeBy: none

		variation Variation
			isDefault
			relationship: e1e3cbf0-a8fc-4e5c-9590-99829634ddf9
			defaultHierarchy: LocalDateTable_b88546b1-994d-47fd-b258-2355e1078847.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column ano_semana = WEEKNUM(fato_contas_depositantes[data], 2)
		formatString: 0
		lineageTag: b4c80d73-9bee-4c06-a2ca-ba6068037f01
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition fato_contas_depositantes = m
		mode: import
		source =
				let
				    Fonte = AzureStorage.DataLake("https://kplakehouse.dfs.core.windows.net/gold/datasets_linkados/contas_depositantes"),
				    #"Linhas Filtradas" = Table.SelectRows(Fonte, each ([Extension] = ".parquet")),
				    #"Arquivos Ocultos Filtrados1" = Table.SelectRows(#"Linhas Filtradas", each [Attributes]?[Hidden]? <> true),
				    #"Invocar Função Personalizada1" = Table.AddColumn(#"Arquivos Ocultos Filtrados1", "Transformar Arquivo (29)", each #"Transformar Arquivo (29)"([Content])),
				    #"Colunas Renomeadas1" = Table.RenameColumns(#"Invocar Função Personalizada1", {"Name", "Nome da Origem"}),
				    #"Outras Colunas Removidas1" = Table.SelectColumns(#"Colunas Renomeadas1", {"Nome da Origem", "Transformar Arquivo (29)"}),
				    #"Coluna de Tabela Expandida1" = Table.ExpandTableColumn(#"Outras Colunas Removidas1", "Transformar Arquivo (29)", Table.ColumnNames(#"Transformar Arquivo (29)"(#"Arquivo de Amostra (29)"))),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Coluna de Tabela Expandida1",{{"Nome da Origem", type text}, {"userid", type text}, {"data", type date}, {"contas_depositantes", Int64.Type}, {"status_ativo_90d", Int64.Type}, {"media_l30d", type number}, {"tier_l30d", Int64.Type}, {"tier_high_lifetime", Int64.Type}, {"media_high_lifetime", type number}, {"hora_atualizacao", type datetime}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

