table fato_ggr
	lineageTag: e36491b6-4e84-43b4-b0a6-8082dcf02e70

	column 'Nome da Origem'
		dataType: string
		lineageTag: 3ed2cd45-71d7-4f51-85de-10289908d34e
		summarizeBy: none
		sourceColumn: Nome da Origem

		annotation SummarizationSetBy = Automatic

	column userid
		dataType: string
		lineageTag: a7e5e7b6-d630-4c67-b203-5bc56fc376af
		summarizeBy: none
		sourceColumn: userid

		annotation SummarizationSetBy = Automatic

	column data
		dataType: dateTime
		formatString: Long Date
		lineageTag: 252dde92-b38f-4a7e-9bd1-8b6d7ecb4be5
		summarizeBy: none
		sourceColumn: data

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ggr_cassino
		dataType: double
		lineageTag: ba1769c1-b2dc-485f-9d84-20fa94c21f9f
		summarizeBy: sum
		sourceColumn: ggr_cassino

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ggr_sportsbook
		dataType: double
		lineageTag: 30164534-9774-4e2a-8b5a-b8d87bd4cd12
		summarizeBy: sum
		sourceColumn: ggr_sportsbook

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ggr_lb
		dataType: double
		lineageTag: 839e8331-24fe-43f5-9f1e-a0a90317a0a4
		summarizeBy: sum
		sourceColumn: ggr_lb

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ggr_total
		dataType: double
		lineageTag: 59e527d6-d080-4d4b-bc76-b38bb1ada4d4
		summarizeBy: sum
		sourceColumn: ggr_total

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column status_ativo_90d
		dataType: int64
		formatString: 0
		lineageTag: bdef8e92-bee9-4bee-aa0e-efba5864a46c
		summarizeBy: sum
		sourceColumn: status_ativo_90d

		annotation SummarizationSetBy = Automatic

	column media_l30d
		dataType: double
		lineageTag: 7f204b1a-f292-470e-9a19-d94fda6681d3
		summarizeBy: sum
		sourceColumn: media_l30d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column tier_l30d
		dataType: int64
		formatString: 0
		lineageTag: b6f16724-3d28-49d8-88ac-79fd133d28a5
		summarizeBy: sum
		sourceColumn: tier_l30d

		annotation SummarizationSetBy = Automatic

	column tier_high_lifetime
		dataType: int64
		formatString: 0
		lineageTag: e0f315c0-0411-408c-b2e5-6aa842518247
		summarizeBy: sum
		sourceColumn: tier_high_lifetime

		annotation SummarizationSetBy = Automatic

	column media_high_lifetime
		dataType: double
		lineageTag: 59561860-2e77-47ef-8aec-5cb9f5a262c7
		summarizeBy: sum
		sourceColumn: media_high_lifetime

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column hora_atualizacao
		dataType: dateTime
		formatString: General Date
		lineageTag: a2329f31-5c6d-404e-8710-9872936225df
		summarizeBy: none
		sourceColumn: hora_atualizacao

		variation Variation
			isDefault
			relationship: 11772c66-d9a2-4e3e-8832-c1e81c1aee31
			defaultHierarchy: LocalDateTable_a26bdd00-dc3b-45b0-8f08-44d045ef6292.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column data_replica = fato_ggr[data]
		formatString: General Date
		lineageTag: 4728b9ee-fc45-4920-943d-3b8ad5037d8d
		summarizeBy: none

		variation Variation
			isDefault
			relationship: 2fcd4b16-511e-4373-b2aa-f3f46dd3f379
			defaultHierarchy: LocalDateTable_fac0b45c-88a0-4dca-aee1-a1f804fdd056.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column ano_semana = WEEKNUM(fato_ggr[data], 2)
		formatString: 0
		lineageTag: 271e472f-9144-45cf-8457-3e7e717e51e5
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition fato_ggr = m
		mode: import
		source =
				let
				    Fonte = AzureStorage.DataLake("https://kplakehouse.dfs.core.windows.net/gold/datasets_linkados/ggr"),
				    #"Linhas Filtradas" = Table.SelectRows(Fonte, each ([Extension] = ".parquet")),
				    #"Arquivos Ocultos Filtrados1" = Table.SelectRows(#"Linhas Filtradas", each [Attributes]?[Hidden]? <> true),
				    #"Invocar Função Personalizada1" = Table.AddColumn(#"Arquivos Ocultos Filtrados1", "Transformar Arquivo (36)", each #"Transformar Arquivo (36)"([Content])),
				    #"Colunas Renomeadas1" = Table.RenameColumns(#"Invocar Função Personalizada1", {"Name", "Nome da Origem"}),
				    #"Outras Colunas Removidas1" = Table.SelectColumns(#"Colunas Renomeadas1", {"Nome da Origem", "Transformar Arquivo (36)"}),
				    #"Coluna de Tabela Expandida1" = Table.ExpandTableColumn(#"Outras Colunas Removidas1", "Transformar Arquivo (36)", Table.ColumnNames(#"Transformar Arquivo (36)"(#"Arquivo de Amostra (36)"))),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Coluna de Tabela Expandida1",{{"Nome da Origem", type text}, {"userid", type text}, {"data", type date}, {"ggr_cassino", type number}, {"ggr_sportsbook", type number}, {"ggr_lb", type number}, {"ggr_total", type number}, {"status_ativo_90d", Int64.Type}, {"media_l30d", type number}, {"tier_l30d", Int64.Type}, {"tier_high_lifetime", Int64.Type}, {"media_high_lifetime", type number}, {"hora_atualizacao", type datetime}}),
				    #"Linhas Filtradas1" = Table.SelectRows(#"Tipo Alterado", each [ggr_total] <> 0)
				in
				    #"Linhas Filtradas1"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

