table fato_netcash
	lineageTag: 9e345c1b-70f1-47ef-b9fb-c421a4139bea

	column 'Nome da Origem'
		dataType: string
		lineageTag: 6909b14d-c4ff-4d95-a1ee-ea827ca34a25
		summarizeBy: none
		sourceColumn: Nome da Origem

		annotation SummarizationSetBy = Automatic

	column userid
		dataType: string
		lineageTag: c9cfd2c7-fc8c-40b3-9105-083743222bd7
		summarizeBy: none
		sourceColumn: userid

		annotation SummarizationSetBy = Automatic

	column data
		dataType: dateTime
		formatString: Long Date
		lineageTag: 7bd59af9-bcc6-440d-ad93-46321891f409
		summarizeBy: none
		sourceColumn: data

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column deposito
		dataType: double
		lineageTag: 9d441595-b51f-4a81-9847-c325076be23d
		summarizeBy: sum
		sourceColumn: deposito

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ngr
		dataType: double
		lineageTag: f585cc22-13d3-4be9-b0b1-cceb853fbcfd
		summarizeBy: sum
		sourceColumn: ngr

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column status_ativo_90d
		dataType: int64
		formatString: 0
		lineageTag: f7cee691-048f-412c-a307-c3a89917c834
		summarizeBy: sum
		sourceColumn: status_ativo_90d

		annotation SummarizationSetBy = Automatic

	column media_l30d
		dataType: double
		lineageTag: 034cc822-4fac-4db2-b9e9-36b47efc3c63
		summarizeBy: sum
		sourceColumn: media_l30d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column tier_l30d
		dataType: int64
		formatString: 0
		lineageTag: 749e876a-c82b-4c4f-bd47-8efbed8ae0ad
		summarizeBy: sum
		sourceColumn: tier_l30d

		annotation SummarizationSetBy = Automatic

	column tier_high_lifetime
		dataType: int64
		formatString: 0
		lineageTag: 191792bc-336c-4bff-a892-a073af7f9bc6
		summarizeBy: sum
		sourceColumn: tier_high_lifetime

		annotation SummarizationSetBy = Automatic

	column media_high_lifetime
		dataType: double
		lineageTag: ce720cc0-9627-4264-9881-56eb60413797
		summarizeBy: sum
		sourceColumn: media_high_lifetime

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column hora_atualizacao
		dataType: dateTime
		formatString: General Date
		lineageTag: 1dedb39d-075d-44a6-a431-f4e3e40578f1
		summarizeBy: none
		sourceColumn: hora_atualizacao

		variation Variation
			isDefault
			relationship: aab1eee6-d122-41f2-9f28-265cc5c3849a
			defaultHierarchy: LocalDateTable_52392ea2-d9b6-4070-b610-2c9b9823b98b.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column ano_semana = WEEKNUM(fato_netcash[data], 2)
		formatString: 0
		lineageTag: ad91a013-ef20-4ac6-9ad5-063d7ac8ede5
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column data_replica = fato_netcash[data]
		formatString: General Date
		lineageTag: 39ca8ca6-0b68-4074-b200-5e5affa0a392
		summarizeBy: none

		variation Variation
			isDefault
			relationship: b55ea04d-686e-4e13-ba0c-01116a54924d
			defaultHierarchy: LocalDateTable_a3f70299-38cc-41f9-bb6b-e2105a157a1e.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	partition fato_netcash = m
		mode: import
		source =
				let
				    Fonte = AzureStorage.DataLake("https://kplakehouse.dfs.core.windows.net/gold/datasets_linkados/netcash"),
				    #"Linhas Filtradas" = Table.SelectRows(Fonte, each ([Extension] = ".parquet")),
				    #"Arquivos Ocultos Filtrados1" = Table.SelectRows(#"Linhas Filtradas", each [Attributes]?[Hidden]? <> true),
				    #"Invocar Função Personalizada1" = Table.AddColumn(#"Arquivos Ocultos Filtrados1", "Transformar Arquivo (47)", each #"Transformar Arquivo (47)"([Content])),
				    #"Colunas Renomeadas1" = Table.RenameColumns(#"Invocar Função Personalizada1", {"Name", "Nome da Origem"}),
				    #"Outras Colunas Removidas1" = Table.SelectColumns(#"Colunas Renomeadas1", {"Nome da Origem", "Transformar Arquivo (47)"}),
				    #"Coluna de Tabela Expandida1" = Table.ExpandTableColumn(#"Outras Colunas Removidas1", "Transformar Arquivo (47)", Table.ColumnNames(#"Transformar Arquivo (47)"(#"Arquivo de Amostra (47)"))),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Coluna de Tabela Expandida1",{{"Nome da Origem", type text}, {"userid", type text}, {"data", type date}, {"deposito", type number}, {"ngr", type number}, {"status_ativo_90d", Int64.Type}, {"media_l30d", type number}, {"tier_l30d", Int64.Type}, {"tier_high_lifetime", Int64.Type}, {"media_high_lifetime", type number}, {"hora_atualizacao", type datetime}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

