table fato_deposito
	lineageTag: df56abe5-20c2-4052-bda0-d8160dbaab9a

	column 'Nome da Origem'
		dataType: string
		lineageTag: 42ea4af6-9eb0-4c06-928a-95c748cfb1e7
		summarizeBy: none
		sourceColumn: Nome da Origem

		annotation SummarizationSetBy = Automatic

	column userid
		dataType: string
		lineageTag: b7367547-1d1f-4209-bfb9-19ea134369de
		summarizeBy: none
		sourceColumn: userid

		annotation SummarizationSetBy = Automatic

	column data
		dataType: dateTime
		formatString: Long Date
		lineageTag: ef5b463b-c072-4cf7-b7ad-1c3192ed48e6
		summarizeBy: none
		sourceColumn: data

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column deposito
		dataType: double
		lineageTag: 6d06baa8-0e08-43b1-882a-610283a6009f
		summarizeBy: sum
		sourceColumn: deposito

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column status_ativo_90d
		dataType: int64
		formatString: 0
		lineageTag: 611f179e-67ac-4768-896c-3496e72b8099
		summarizeBy: sum
		sourceColumn: status_ativo_90d

		annotation SummarizationSetBy = Automatic

	column media_l30d
		dataType: double
		lineageTag: b83216a8-9315-44c3-ad4d-86c4c164863d
		summarizeBy: sum
		sourceColumn: media_l30d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column tier_l30d
		dataType: int64
		formatString: 0
		lineageTag: b4894397-cd1e-48da-ae7a-897459bdab31
		summarizeBy: sum
		sourceColumn: tier_l30d

		annotation SummarizationSetBy = Automatic

	column tier_high_lifetime
		dataType: int64
		formatString: 0
		lineageTag: 2c1d7ff9-ce6e-4cd2-8dc3-f71f2f4f9630
		summarizeBy: sum
		sourceColumn: tier_high_lifetime

		annotation SummarizationSetBy = Automatic

	column media_high_lifetime
		dataType: double
		lineageTag: 3c05b53c-4c98-452c-b96d-fd0d77467b1a
		summarizeBy: sum
		sourceColumn: media_high_lifetime

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column hora_atualizacao
		dataType: dateTime
		formatString: General Date
		lineageTag: b7628aeb-d72b-44b9-970d-a4b47922fa5b
		summarizeBy: none
		sourceColumn: hora_atualizacao

		variation Variation
			isDefault
			relationship: e82fca10-e527-4e9a-a413-2fdd41ad9954
			defaultHierarchy: LocalDateTable_76dbad9d-e87f-4b9c-9b28-d752d38d450a.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column data_replica = fato_deposito[data]
		formatString: General Date
		lineageTag: 1b3d906a-a0e8-45b0-8499-8f06829dadc6
		summarizeBy: none

		variation Variation
			isDefault
			relationship: 85701718-b9a8-4bd3-95a2-f4c98a12980a
			defaultHierarchy: LocalDateTable_7a218738-3a71-4876-8535-01bdda277bab.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column ano_semana = WEEKNUM(fato_deposito[data], 2)
		formatString: 0
		lineageTag: bda4d69e-9a62-48f9-86b8-7ea3c1a5dc38
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition fato_deposito = m
		mode: import
		source =
				let
				    Fonte = AzureStorage.DataLake("https://kplakehouse.dfs.core.windows.net/gold/datasets_linkados/deposito"),
				    #"Linhas Filtradas" = Table.SelectRows(Fonte, each ([Extension] = ".parquet")),
				    #"Arquivos Ocultos Filtrados1" = Table.SelectRows(#"Linhas Filtradas", each [Attributes]?[Hidden]? <> true),
				    #"Invocar Função Personalizada1" = Table.AddColumn(#"Arquivos Ocultos Filtrados1", "Transformar Arquivo (26)", each #"Transformar Arquivo (26)"([Content])),
				    #"Colunas Renomeadas1" = Table.RenameColumns(#"Invocar Função Personalizada1", {"Name", "Nome da Origem"}),
				    #"Outras Colunas Removidas1" = Table.SelectColumns(#"Colunas Renomeadas1", {"Nome da Origem", "Transformar Arquivo (26)"}),
				    #"Coluna de Tabela Expandida1" = Table.ExpandTableColumn(#"Outras Colunas Removidas1", "Transformar Arquivo (26)", Table.ColumnNames(#"Transformar Arquivo (26)"(#"Arquivo de Amostra (26)"))),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Coluna de Tabela Expandida1",{{"Nome da Origem", type text}, {"userid", type text}, {"data", type date}, {"deposito", type number}, {"status_ativo_90d", Int64.Type}, {"media_l30d", type number}, {"tier_l30d", Int64.Type}, {"tier_high_lifetime", Int64.Type}, {"media_high_lifetime", type number}, {"hora_atualizacao", type datetime}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

