table medidas
	lineageTag: 8413c12b-0984-4fb8-8e83-173a5eaab60f

	measure qtd_deposito_fact = SUM(fato_qtd_depositos[qtd_depositos])
		formatString: 0
		lineageTag: c7495772-6366-4aa4-90ee-bae21486857d

	measure txx =
			
			VAR Percentual =
			    SELECTEDVALUE ( 'Taxa %'[Taxa %], 0 )
			RETURN
			CALCULATE(
			    'Valor Depósito'[Valor Valor Depósito] *
			    Percentual / 100
			)
		lineageTag: 838641be-e748-4bad-a489-510bbee5f47a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Qtd_Usuarios_Unicos_Deposito = ```
			
			COUNTROWS(
			    DISTINCT(bd_depositos[userid])
			)
			
			```
		formatString: 0
		lineageTag: 1fdced92-4ded-4b39-886c-b5b315b45305

	column 'Brand Color' = ```
			"__BRAND_HEX__"
			
			```
		lineageTag: ec43c35e-7900-4d23-99c6-743e13d56756
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition medidas = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Coluna 1" = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Coluna 1", type text}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Tipo Alterado",{"Coluna 1"})
				in
				    #"Colunas Removidas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

