table 'Taxa %'
	lineageTag: 8080b18b-33d7-4adb-8f0e-0f947d9f12cb

	measure 'Valor Taxa %' = SELECTEDVALUE('Taxa %'[Taxa %], 0)
		formatString: 0.0
		lineageTag: 012c3711-213d-4c5a-a088-4b8cccce17c4

	column 'Taxa %'
		formatString: 0.0
		lineageTag: 00ab6e42-82a2-4832-99f3-03145b6319b3
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition 'Taxa %' = calculated
		mode: import
		source = GENERATESERIES(0.0, 100.0, 0.1)

	annotation PBI_Id = 44889292ed2d4e5c8cda6bb48a0b72d1

