table Top5_Aposta_Rollback
	lineageTag: 9bf0b2b9-1875-442f-898b-095fd515ce1d

	measure 'Aposta Rollback (Top 5 dinâmico c/ “Outros”)' = ```
			
			/* ------------------------------------------------------------------ */
			/* 1. Monta a lista já filtrada de provedores e calcula seu total     */
			VAR Base =
			    SUMMARIZE (
			        VALUES ( 'bd_softswiss'[provider] ),         -- mantém filtro atual
			        'bd_softswiss'[provider],
			        "ApostaRollback", [aposta_rollback_com_outros]
			    )
			
			/* 2. Pega os 5 maiores valores dentro desse subconjunto              */
			VAR TopTable =
			    TOPN ( 5, Base, [ApostaRollback], DESC )
			
			/* 3. Converte em tabela de 1 coluna para comparação/EXCEPT           */
			VAR TopProv =
			    SELECTCOLUMNS ( TopTable, "provider", [provider] )
			
			/* 4. Quem é a linha que o visual está pedindo no momento?            */
			VAR SelProv =
			    SELECTEDVALUE ( Top5_Aposta_Rollback[provider] )
			
			/* 5. SelProv está ou não no Top 5?                                   */
			VAR IsInTop =
			    CONTAINS ( TopProv, [provider], SelProv )
			
			/* ------------------------------------------------------------------ */
			RETURN
			SWITCH (
			    TRUE(),
			
			    /* --- Linha “Outros” -------------------------------------------- */
			    SelProv = "Outros",
			        CALCULATE (
			            [aposta_rollback_com_outros],
			            KEEPFILTERS (
			                EXCEPT (                       -- tudo que não for Top 5
			                    VALUES ( 'bd_softswiss'[provider] ),
			                    TopProv
			                )
			            )
			        ),
			
			    /* --- Linha que faz parte do Top 5 ------------------------------ */
			    IsInTop,
			        CALCULATE (
			            [aposta_rollback_com_outros],
			            'bd_softswiss'[provider] = SelProv
			        ),
			
			    /* --- Qualquer outra linha (não Top 5 nem “Outros”) ------------- */
			    BLANK()
			)
			
			```
		lineageTag: 3a30f405-4466-4060-b1b3-ec0636b38637

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column provider
		lineageTag: cd3efcaf-c031-4400-8fc5-ff53c2ff21df
		summarizeBy: none
		isNameInferred
		sourceColumn: [provider]

		annotation SummarizationSetBy = Automatic

	partition Top5_Aposta_Rollback = calculated
		mode: import
		source = ```
				
				UNION (
				    SELECTCOLUMNS (
				        DISTINCT ( 'bd_softswiss'[provider] ),   -- um por provedor
				        "provider", 'bd_softswiss'[provider]
				    ),
				    DATATABLE (                                   -- adiciona a linha “Outros”
				        "provider", STRING, { { "Outros" } }
				    )
				)
				
				```

	annotation PBI_Id = 809ac429752944eebf8667ee1953c268

