table Top5_Premio_Rollback
	lineageTag: ffaafa12-19cc-4645-82fd-f4528086313b

	measure 'Prêmio Rollback (Top 5 dinâmico c/"Outros")' = ```
			
			/* ------------------------------------------------------------------ */
			/* 1. Monta a lista já filtrada de provedores e calcula seu total     */
			VAR Base =
			    SUMMARIZE (
			        VALUES ( 'bd_softswiss'[provider] ),         -- mantém filtro atual
			        'bd_softswiss'[provider],
			        "PremioRollback", [premio_rollback_com_outros]
			    )
			
			/* 2. Pega os 5 maiores valores dentro desse subconjunto              */
			VAR TopTable =
			    TOPN ( 5, Base, [PremioRollback], DESC )
			
			/* 3. Converte em tabela de 1 coluna para comparação/EXCEPT           */
			VAR TopProv =
			    SELECTCOLUMNS ( TopTable, "provider", [provider] )
			
			/* 4. Quem é a linha que o visual está pedindo no momento?            */
			VAR SelProv =
			    SELECTEDVALUE ( Top5_Premio_Rollback[provider] )
			
			/* 5. SelProv está ou não no Top 5?                                   */
			VAR IsInTop =
			    CONTAINS ( TopProv, [provider], SelProv )
			
			/* ------------------------------------------------------------------ */
			RETURN
			SWITCH (
			    TRUE(),
			
			    /* --- Linha “Outros” -------------------------------------------- */
			    SelProv = "Outros",
			        CALCULATE (
			            [premio_rollback_com_outros],
			            KEEPFILTERS (
			                EXCEPT (                       -- tudo que não for Top 5
			                    VALUES ( 'bd_softswiss'[provider] ),
			                    TopProv
			                )
			            )
			        ),
			
			    /* --- Linha que faz parte do Top 5 ------------------------------ */
			    IsInTop,
			        CALCULATE (
			            [premio_rollback_com_outros],
			            'bd_softswiss'[provider] = SelProv
			        ),
			
			    /* --- Qualquer outra linha (não Top 5 nem “Outros”) ------------- */
			    BLANK()
			)
			
			```
		lineageTag: 78826e18-9ed7-4ef4-b1bf-62be001a5471

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column provider
		lineageTag: 9536c3e5-a3ef-41d2-95f2-be67f9b0034b
		summarizeBy: none
		isNameInferred
		sourceColumn: [provider]

		annotation SummarizationSetBy = Automatic

	partition Top5_Premio_Rollback = calculated
		mode: import
		source =
				
				UNION (
				    SELECTCOLUMNS (
				        DISTINCT ( 'bd_softswiss'[provider] ),   -- um por provedor
				        "provider", 'bd_softswiss'[provider]
				    ),
				    DATATABLE (                                   -- adiciona a linha “Outros”
				        "provider", STRING, { { "Outros" } }
				    )
				)

	annotation PBI_Id = 77e3b845e78e414fb0cdda915d7c52d9

