table Top5_Clientes_Ativos
	lineageTag: 67bf472e-ccc7-4dd4-832e-80ba1bec39ce

	measure 'Clientes Ativos (Top 5 dinâmico c/"Outros")' = ```
			
			/* ------------------------------------------------------------------ */
			/* 1. Monta a lista já filtrada de provedores e calcula seu total     */
			VAR Base =
			    SUMMARIZE (
			        VALUES ( 'bd_softswiss'[provider] ),         -- mantém filtro atual
			        'bd_softswiss'[provider],
			        "ClientesAtivos", [clientes_ativos_com_outros]
			    )
			
			/* 2. Pega os 5 maiores valores dentro desse subconjunto              */
			VAR TopTable =
			    TOPN ( 5, Base, [ClientesAtivos], DESC )
			
			/* 3. Converte em tabela de 1 coluna para comparação/EXCEPT           */
			VAR TopProv =
			    SELECTCOLUMNS ( TopTable, "provider", [provider] )
			
			/* 4. Quem é a linha que o visual está pedindo no momento?            */
			VAR SelProv =
			    SELECTEDVALUE ( Top5_Clientes_Ativos[provider] )
			
			/* 5. SelProv está ou não no Top 5?                                   */
			VAR IsInTop =
			    CONTAINS ( TopProv, [provider], SelProv )
			
			/* ------------------------------------------------------------------ */
			RETURN
			SWITCH (
			    TRUE(),
			
			    /* --- Linha “Outros” -------------------------------------------- */
			    SelProv = "Outros",
			        CALCULATE (
			            [clientes_ativos_com_outros],
			            KEEPFILTERS (
			                EXCEPT (                       -- tudo que não for Top 5
			                    VALUES ( 'bd_softswiss'[provider] ),
			                    TopProv
			                )
			            )
			        ),
			
			    /* --- Linha que faz parte do Top 5 ------------------------------ */
			    IsInTop,
			        CALCULATE (
			            [clientes_ativos_com_outros],
			            'bd_softswiss'[provider] = SelProv
			        ),
			
			    /* --- Qualquer outra linha (não Top 5 nem “Outros”) ------------- */
			    BLANK()
			)
			
			```
		formatString: 0
		lineageTag: 03aefd69-77e8-4af0-9459-adff86b215b9

	column provider
		lineageTag: f122ef82-44f9-4df2-b1b1-35e6145f660f
		summarizeBy: none
		isNameInferred
		sourceColumn: [provider]

		annotation SummarizationSetBy = Automatic

	partition Top5_Clientes_Ativos = calculated
		mode: import
		source =
				
				UNION (
				    SELECTCOLUMNS (
				        DISTINCT ( 'bd_softswiss'[provider] ),   -- um por provedor
				        "provider", 'bd_softswiss'[provider]
				    ),
				    DATATABLE (                                   -- adiciona a linha “Outros”
				        "provider", STRING, { { "Outros" } }
				    )
				)

	annotation PBI_Id = 27c77087b0c04ccd9bfab2d7e7bc398c

