table Top5_TotalAposta_producer
	lineageTag: 426595d8-305e-4a05-8027-e6d803ed6aab

	measure 'Total Aposta (Top5 dinâmico)' = ```
			
			VAR Base =
			    SUMMARIZE (                          -- cria provedor + total do contexto
			        ALLSELECTED ( 'bd_softswiss'[producer] ),
			        'bd_softswiss'[producer],
			        "TotalAposta", [total_aposta_com_outros]
			    )
			
			VAR TopTable =                          -- mantém só os 5 maiores
			    TOPN ( 5, Base, [TotalAposta], DESC )
			
			/* ► Novo passo: extrai APENAS a coluna provider  ◄ */
			VAR TopProv =
			    SELECTCOLUMNS ( TopTable,            -- agora vira tabela de 1 coluna
			        "producer", [producer] )
			
			VAR SelProv =
			    SELECTEDVALUE ( Top5_TotalAposta_producer[producer] ) -- provedor/“Outros” clicado
			
			RETURN
			SWITCH (
			    TRUE(),
			    /* --- Bloco “Outros” ----------------------------------------------- */
			    SelProv = "Outros",
			        CALCULATE (
			            [total_aposta_com_outros],
			            /* aplica filtro-tabela com EXCEPT (ambas 1 coluna) */
			            KEEPFILTERS (
			                EXCEPT (
			                    ALLSELECTED ( 'bd_softswiss'[producer] ),   -- universo
			                    TopProv                                     -- tira Top 5
			                )
			            )
			        ),
			    /* --- Quando é um provedor específico ------------------------------ */
			    CALCULATE (
			        [total_aposta_com_outros],
			        'bd_softswiss'[producer] = SelProv
			    )
			)
			
			```
		lineageTag: 1e9e045f-dd4b-4108-a0ef-f29d77ac6e93

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Aposta Producer(Top 5 dinâmico c/"Outros")' = ```
			
			/* ------------------------------------------------------------------ */
			/* 1. Monta a lista já filtrada de provedores e calcula seu total     */
			VAR Base =
			    SUMMARIZE (
			        VALUES ( 'bd_softswiss'[producer] ),         -- mantém filtro atual
			        'bd_softswiss'[producer],
			        "TotalAposta", [total_aposta_com_outros]
			    )
			
			/* 2. Pega os 5 maiores valores dentro desse subconjunto              */
			VAR TopTable =
			    TOPN ( 5, Base, [TotalAposta], DESC )
			
			/* 3. Converte em tabela de 1 coluna para comparação/EXCEPT           */
			VAR TopProv =
			    SELECTCOLUMNS ( TopTable, "producer", [producer] )
			
			/* 4. Quem é a linha que o visual está pedindo no momento?            */
			VAR SelProv =
			    SELECTEDVALUE ( Top5_TotalAposta_producer[producer] )
			
			/* 5. SelProv está ou não no Top 5?                                   */
			VAR IsInTop =
			    CONTAINS ( TopProv, [producer], SelProv )
			
			/* ------------------------------------------------------------------ */
			RETURN
			SWITCH (
			    TRUE(),
			
			    /* --- Linha “Outros” -------------------------------------------- */
			    SelProv = "Outros",
			        CALCULATE (
			            [total_aposta_com_outros],
			            KEEPFILTERS (
			                EXCEPT (                       -- tudo que não for Top 5
			                    VALUES ( 'bd_softswiss'[producer] ),
			                    TopProv
			                )
			            )
			        ),
			
			    /* --- Linha que faz parte do Top 5 ------------------------------ */
			    IsInTop,
			        CALCULATE (
			            [total_aposta_com_outros],
			            'bd_softswiss'[producer] = SelProv
			        ),
			
			    /* --- Qualquer outra linha (não Top 5 nem “Outros”) ------------- */
			    BLANK()
			)
			
			```
		lineageTag: e8f1217a-453e-4319-9b96-74dd57421a39

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column producer
		lineageTag: 3953db04-9c7d-4605-ac64-62a2e82e64d7
		summarizeBy: none
		isNameInferred
		sourceColumn: [producer]

		annotation SummarizationSetBy = Automatic

	partition Top5_TotalAposta_producer = calculated
		mode: import
		source =
				
				UNION (
				    SELECTCOLUMNS (
				        DISTINCT ( 'bd_softswiss'[producer] ),   -- um por provedor
				        "producer", 'bd_softswiss'[producer]
				    ),
				    DATATABLE (                                   -- adiciona a linha “Outros”
				        "producer", STRING, { { "Outros" } }
				    )
				)

	annotation PBI_Id = 431a80677ac94c809fe113c8a785630f

